// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package latex

import (
	"strings"
	"testing"
)

func TestInline(t *testing.T) {
	cases := map[string]string{
		`n`:                           "𝑛",
		`O(n \log n)`:                 "𝑂(𝑛 log 𝑛)",
		`x^2 + y_i`:                   "𝑥² + 𝑦ᵢ",
		`\frac{a}{b}`:                 "𝑎/𝑏",
		`\frac{n(n+1)}{2}`:            "𝑛(𝑛 + 1)/2",
		`\sum_{i=1}^{n} i`:            "∑ᵢ₌₁ⁿ 𝑖",
		`\mathbb{R}^n \to \mathbb{N}`: "ℝⁿ → ℕ",
		`a \le b \neq c`:              "𝑎 ≤ 𝑏 ≠ 𝑐",
		`\sqrt{x+1}`:                  "√(𝑥 + 1)",
		`e^{-x}`:                      "𝑒⁻ˣ",
		`x^{q+1}`:                     "𝑥^(𝑞+1)",
		`\alpha\beta`:                 "αβ",
		`f'(x)`:                       "𝑓′(𝑥)",
		`\text{if } x > 0`:            "if 𝑥 > 0",
		`-x`:                          "−𝑥",
		`h`:                           "ℎ",
		`\int_0^1 x\,dx`:              "∫₀¹ 𝑥 𝑑𝑥",
		`\frac{a+b}{c}`:               "(𝑎 + 𝑏)/𝑐",
		`\hat{x} + \bar{y}`:           "𝑥\u0302 + 𝑦\u0304",
	}
	for src, want := range cases {
		if got := Inline(src); got != want {
			t.Errorf("Inline(%q) = %q, want %q", src, got, want)
		}
	}
}

func TestDisplay(t *testing.T) {
	for _, src := range []string{
		`\frac{-b \pm \sqrt{b^2 - 4ac}}{2a}`,
		`\sum_{i=1}^{n} i = \frac{n(n+1)}{2}`,
		`T(n) = \begin{cases} 1 & n = 1 \\ 2T(n/2) + n & \text{otherwise} \end{cases}`,
		`A = \begin{pmatrix} a & b \\ c & d \end{pmatrix}, \quad \left( \frac{x}{y} \right)^2`,
		`\begin{aligned} a &= b + c \\ &= d \end{aligned}`,
		`\lim_{x \to \infty} \frac{1}{x} = 0 \qquad \int_0^1 x\,dx = \frac{1}{2}`,
		`\sqrt{\frac{a}{b}} + \binom{n}{k}`,
	} {
		out := Render(src, Options{Display: true})
		t.Logf("%s\n%s", src, strings.Join(out, "\n"))
		if len(out) == 0 {
			t.Errorf("no output for %q", src)
		}
	}
}

func TestMalformedDoesNotPanic(t *testing.T) {
	for _, src := range []string{``, `}`, `{`, `\frac`, `\frac{a}`, `x^`, `_`, `\left(`, `\right)`, `\begin{cases}`, `\end{x}`, `a & b \\`, `\sqrt[`, `\`} {
		Render(src, Options{Display: true})
		Render(src, Options{})
	}
}
