// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package latex

import (
	"strings"
	"unicode"
)

type kind int

const (
	kChar      kind = iota // literal character(s) from the source
	kSym                   // a Unicode symbol produced by a command
	kGroup                 // {...}
	kScript                // kids[0] is the base; sub/sup hold the scripts
	kFrac                  // kids: numerator, denominator
	kBinom                 // kids: top, bottom
	kSqrt                  // kids: radicand[, index]
	kFont                  // text: font name; kids: content
	kText                  // text: upright literal text
	kOp                    // text: upright operator name (sin, log)
	kLimOp                 // text: operator that takes limits (lim, max)
	kAccent                // text: combining mark; kids: content
	kMatrix                // env + rows
	kLeftRight             // left, right delimiters around kids
	kSpace                 // text: literal spaces
	kBoxed
)

type node struct {
	kind        kind
	text        string
	kids        []*node
	sub, sup    *node
	env         string
	rows        [][]*node
	left, right string
}

type parser struct {
	src []rune
	pos int
}

func (p *parser) eof() bool { return p.pos >= len(p.src) }

func (p *parser) peek() rune {
	if p.eof() {
		return 0
	}
	return p.src[p.pos]
}

func (p *parser) skipSpace() {
	for !p.eof() && unicode.IsSpace(p.peek()) {
		p.pos++
	}
}

// command reads the name after a backslash.
func (p *parser) command() string {
	p.pos++ // backslash
	start := p.pos
	for !p.eof() && unicode.IsLetter(p.peek()) {
		p.pos++
	}
	if p.pos == start && !p.eof() {
		p.pos++
	}
	name := string(p.src[start:p.pos])
	if !p.eof() && p.peek() == '*' && len(name) > 1 {
		p.pos++
	}
	return name
}

// peekCommand returns the next command name without consuming it.
func (p *parser) peekCommand() string {
	if p.peek() != '\\' {
		return ""
	}
	save := p.pos
	name := p.command()
	p.pos = save
	return name
}

// rawGroup reads {...} verbatim, for \text and environment names.
func (p *parser) rawGroup() string {
	p.skipSpace()
	if p.peek() != '{' {
		return ""
	}
	p.pos++
	depth, start := 1, p.pos
	for !p.eof() {
		switch p.peek() {
		case '\\':
			p.pos++
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				s := string(p.src[start:p.pos])
				p.pos++
				return s
			}
		}
		p.pos++
	}
	return string(p.src[start:min(p.pos, len(p.src))])
}

// rows parses cells separated by & and rows separated by \\ until a
// terminator: '}' , \end, \right or end of input.
func (p *parser) parseRows() [][]*node {
	rows := [][]*node{{}}
	for {
		cell := &node{kind: kGroup, kids: p.parseSeq()}
		last := len(rows) - 1
		rows[last] = append(rows[last], cell)
		switch {
		case p.peek() == '&':
			p.pos++
		case p.peekCommand() == "\\":
			p.command()
			if p.skipSpace(); p.peek() == '[' { // \\[2pt]
				for !p.eof() && p.peek() != ']' {
					p.pos++
				}
				p.pos++
			}
			rows = append(rows, nil)
		default:
			// Drop a trailing empty row left by a final \\.
			if n := len(rows) - 1; n > 0 && len(rows[n]) == 1 && len(rows[n][0].kids) == 0 {
				rows = rows[:n]
			}
			return rows
		}
	}
}

// parseSeq parses atoms until something a caller must handle.
func (p *parser) parseSeq() []*node {
	var out []*node
	for !p.eof() {
		c := p.peek()
		if c == '}' || c == '&' {
			break
		}
		if c == '\\' {
			if n := p.peekCommand(); n == "\\" || n == "end" || n == "right" {
				break
			}
		}
		if c == '^' || c == '_' {
			p.pos++
			arg := p.parseArg()
			var base *node
			if n := len(out); n > 0 && out[n-1].kind != kSpace {
				base = out[n-1]
				out = out[:n-1]
			} else {
				base = &node{kind: kGroup}
			}
			if base.kind != kScript {
				base = &node{kind: kScript, kids: []*node{base}}
			}
			if c == '^' {
				if base.sup != nil { // x'^2 and friends: concatenate
					arg = &node{kind: kGroup, kids: []*node{base.sup, arg}}
				}
				base.sup = arg
			} else {
				base.sub = arg
			}
			out = append(out, base)
			continue
		}
		if c == '\'' {
			p.pos++
			out = append(out, &node{kind: kSym, text: "′"})
			continue
		}
		if a := p.parseAtom(); a != nil {
			out = append(out, a)
		}
	}
	return out
}

func (p *parser) parseArg() *node {
	p.skipSpace()
	if p.eof() {
		return &node{kind: kGroup}
	}
	if a := p.parseAtom(); a != nil {
		return a
	}
	return &node{kind: kGroup}
}

func (p *parser) delimiter() string {
	p.skipSpace()
	if p.eof() {
		return ""
	}
	if p.peek() == '\\' {
		name := p.command()
		if s, ok := symbols[name]; ok {
			return s
		}
		return ""
	}
	c := p.peek()
	p.pos++
	if c == '.' {
		return ""
	}
	return string(c)
}

func (p *parser) parseAtom() *node {
	c := p.peek()
	switch {
	case c == '{':
		p.pos++
		kids := p.parseSeq()
		if p.peek() == '}' {
			p.pos++
		}
		return &node{kind: kGroup, kids: kids}
	case c == '\\':
		return p.parseCommand()
	case unicode.IsSpace(c):
		p.skipSpace()
		return nil
	case c == '~':
		p.pos++
		return &node{kind: kSpace, text: " "}
	case c == '}' || c == '&':
		return nil
	}
	p.pos++
	return &node{kind: kChar, text: string(c)}
}

func (p *parser) parseCommand() *node {
	name := p.command()
	switch name {
	case "frac", "dfrac", "tfrac", "cfrac":
		return &node{kind: kFrac, kids: []*node{p.parseArg(), p.parseArg()}}
	case "binom", "dbinom", "tbinom", "choose":
		return &node{kind: kBinom, kids: []*node{p.parseArg(), p.parseArg()}}
	case "sqrt":
		p.skipSpace()
		var index *node
		if p.peek() == '[' {
			p.pos++
			start := p.pos
			for !p.eof() && p.peek() != ']' {
				p.pos++
			}
			index = parse(string(p.src[start:p.pos]))
			p.pos++
		}
		n := &node{kind: kSqrt, kids: []*node{p.parseArg()}}
		if index != nil {
			n.kids = append(n.kids, index)
		}
		return n
	case "text", "textrm", "mbox", "textit", "textbf", "texttt", "textsf", "operatorname":
		font := fontCommands[name]
		if font == "rm" || font == "" {
			return &node{kind: kText, text: p.rawGroup()}
		}
		return &node{kind: kFont, text: font, kids: []*node{{kind: kText, text: p.rawGroup()}}}
	case "left":
		n := &node{kind: kLeftRight, left: p.delimiter()}
		n.kids = []*node{rowsNode(p.parseRows())}
		if p.peekCommand() == "right" {
			p.command()
			n.right = p.delimiter()
		}
		return n
	case "right": // unmatched
		p.delimiter()
		return nil
	case "begin":
		env := strings.TrimSuffix(p.rawGroup(), "*")
		n := &node{kind: kMatrix, env: env}
		if env == "array" || env == "alignedat" || env == "tabular" {
			n.text = p.rawGroup()
		}
		n.rows = p.parseRows()
		if p.peekCommand() == "end" {
			p.command()
			p.rawGroup()
		}
		return n
	case "end":
		p.rawGroup()
		return nil
	case "overset", "stackrel":
		top, base := p.parseArg(), p.parseArg()
		return &node{kind: kScript, kids: []*node{base}, sup: top}
	case "underset":
		bottom, base := p.parseArg(), p.parseArg()
		return &node{kind: kScript, kids: []*node{base}, sub: bottom}
	case "overline", "underline":
		mark := "\u0305"
		if name == "underline" {
			mark = "\u0332"
		}
		return &node{kind: kAccent, text: mark, kids: []*node{p.parseArg()}}
	case "not":
		return &node{kind: kAccent, text: "\u0338", kids: []*node{p.parseArg()}}
	case "boxed", "fbox":
		return &node{kind: kBoxed, kids: []*node{p.parseArg()}}
	case "underbrace", "overbrace", "phantom", "mathstrut", "vphantom", "hphantom", "smash":
		arg := p.parseArg()
		if strings.Contains(name, "phantom") || name == "mathstrut" {
			return nil
		}
		return arg
	case "textcolor", "colorbox":
		p.rawGroup()
		return p.parseArg()
	case "color", "label", "vspace", "hspace":
		p.rawGroup()
		return nil
	case "tag":
		return &node{kind: kText, text: "  (" + p.rawGroup() + ")"}
	case "pmod":
		return &node{kind: kGroup, kids: []*node{{kind: kText, text: " (mod "}, p.parseArg(), {kind: kText, text: ")"}}}
	case "displaystyle", "textstyle", "scriptstyle", "limits", "nolimits", "nonumber", "notag",
		"big", "Big", "bigg", "Bigg", "bigl", "bigr", "Bigl", "Bigr", "biggl", "biggr", "Biggl",
		"Biggr", "bigm", "Bigm", "middle", "hline", "centering", "!", "allowbreak":
		return nil
	case ",", ":", ";", " ", "enspace", "thinspace":
		return &node{kind: kSpace, text: " "}
	case "quad":
		return &node{kind: kSpace, text: "  "}
	case "qquad":
		return &node{kind: kSpace, text: "    "}
	case "\\":
		return nil
	}
	if font, ok := fontCommands[name]; ok {
		return &node{kind: kFont, text: font, kids: []*node{p.parseArg()}}
	}
	if mark, ok := accents[name]; ok {
		return &node{kind: kAccent, text: string(mark), kids: []*node{p.parseArg()}}
	}
	if label, ok := limitOps[name]; ok {
		return &node{kind: kLimOp, text: label}
	}
	if functions[name] {
		if name == "bmod" {
			name = "mod"
		}
		return &node{kind: kOp, text: name}
	}
	if s, ok := symbols[name]; ok {
		return &node{kind: kSym, text: s}
	}
	return &node{kind: kText, text: "\\" + name}
}

// rowsNode wraps parsed rows: a plain group for the usual single cell, an
// implicit aligned environment when the source used & or \\ bare.
func rowsNode(rows [][]*node) *node {
	if len(rows) == 1 && len(rows[0]) == 1 {
		return rows[0][0]
	}
	return &node{kind: kMatrix, env: "aligned", rows: rows}
}

func parse(src string) *node {
	p := &parser{src: []rune(src)}
	rows := p.parseRows()
	for !p.eof() {
		// A stray terminator (unmatched }, \end, \right): skip it and carry
		// on in the same cell rather than losing the rest of the formula.
		switch p.peekCommand() {
		case "end":
			p.command()
			p.rawGroup()
		case "right":
			p.command()
			p.delimiter()
		default:
			p.pos++
		}
		more := p.parseRows()
		lastRow := rows[len(rows)-1]
		lastCell := lastRow[len(lastRow)-1]
		lastCell.kids = append(lastCell.kids, more[0][0].kids...)
		rows[len(rows)-1] = append(lastRow, more[0][1:]...)
		rows = append(rows, more[1:]...)
	}
	return rowsNode(rows)
}
