// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package latex

import (
	"strings"
	"unicode"
)

// Options control rendering.
type Options struct {
	Display bool // two-dimensional layout; otherwise everything fits one line
	Upright bool // keep Latin letters upright instead of math italic
}

// Render converts LaTeX math to lines of Unicode text.
func Render(src string, o Options) []string {
	b := ctx{display: o.Display, upright: o.Upright}.render(parse(strings.TrimSpace(src)))
	out := make([]string, len(b.lines))
	for i, l := range b.lines {
		out[i] = strings.TrimRight(l, " ")
	}
	if len(out) == 1 {
		out[0] = strings.TrimSpace(squeeze(out[0]))
	}
	return out
}

// Inline is Render for a single line.
func Inline(src string) string { return Render(src, Options{})[0] }

type ctx struct {
	display  bool
	upright  bool
	font     string // "" = default math italic
	inScript bool   // inside a sub/superscript: no operator spacing
}

// box is a block of text with a baseline row.
type box struct {
	lines []string
	base  int
}

func text(s string) box { return box{lines: []string{s}} }

func width(s string) int {
	n := 0
	for _, r := range s {
		if !unicode.Is(unicode.Mn, r) && !unicode.Is(unicode.Me, r) {
			n++
		}
	}
	return n
}

func (b box) width() int {
	w := 0
	for _, l := range b.lines {
		w = max(w, width(l))
	}
	return w
}

func (b box) height() int { return len(b.lines) }
func (b box) flat() bool  { return len(b.lines) == 1 }

func padRight(s string, w int) string { return s + strings.Repeat(" ", max(0, w-width(s))) }

func align(s string, w int, mode byte) string {
	gap := max(0, w-width(s))
	switch mode {
	case 'r':
		return strings.Repeat(" ", gap) + s
	case 'c':
		return strings.Repeat(" ", gap/2) + s + strings.Repeat(" ", gap-gap/2)
	}
	return s + strings.Repeat(" ", gap)
}

// hcat joins boxes left to right with their baselines aligned.
func hcat(boxes ...box) box {
	above, below := 0, 0
	for _, b := range boxes {
		above = max(above, b.base)
		below = max(below, b.height()-1-b.base)
	}
	lines := make([]string, above+below+1)
	for _, b := range boxes {
		w := b.width()
		for i := range lines {
			j := i - (above - b.base)
			s := ""
			if j >= 0 && j < b.height() {
				s = b.lines[j]
			}
			lines[i] += padRight(s, w)
		}
	}
	return box{lines: lines, base: above}
}

// vstack piles boxes, aligning each line; base selects the baseline box.
func vstack(mode byte, baseBox int, boxes ...box) box {
	w := 0
	for _, b := range boxes {
		w = max(w, b.width())
	}
	var out box
	for i, b := range boxes {
		if i == baseBox {
			out.base = len(out.lines) + b.base
		}
		for _, l := range b.lines {
			out.lines = append(out.lines, align(l, w, mode))
		}
	}
	return out
}

func squeeze(s string) string {
	for strings.Contains(s, "  ") {
		s = strings.ReplaceAll(s, "  ", " ")
	}
	return s
}

func (c ctx) render(n *node) box {
	if n == nil {
		return text("")
	}
	switch n.kind {
	case kChar:
		return text(c.chars(n.text))
	case kSym, kSpace:
		return text(n.text)
	case kText:
		return text(n.text)
	case kOp, kLimOp:
		return text(n.text)
	case kGroup:
		return c.seq(n.kids)
	case kFont:
		sub := c
		sub.font = n.text
		return sub.seq(n.kids)
	case kAccent:
		return c.accent(n)
	case kFrac:
		return c.frac(n)
	case kBinom:
		return c.binom(n)
	case kSqrt:
		return c.sqrt(n)
	case kScript:
		return c.scripts(n)
	case kLeftRight:
		return c.leftRight(n)
	case kMatrix:
		return c.matrix(n)
	case kBoxed:
		return c.boxed(n)
	}
	return text("")
}

// chars styles literal source characters for the current font.
func (c ctx) chars(s string) string {
	font := c.font
	if font == "" && !c.upright {
		font = "italic"
	}
	var sb strings.Builder
	for _, r := range s {
		switch {
		case r == '-':
			sb.WriteRune('−')
		case font == "rm" || font == "plain":
			sb.WriteRune(r)
		default:
			sb.WriteRune(styled(r, font))
		}
	}
	return sb.String()
}

func isOpen(n *node) bool {
	if n.kind == kChar || n.kind == kSym {
		return strings.ContainsAny(n.text, "([{⟨⌊⌈,;:") || spaced[n.text] || n.text == "+" || n.text == "-"
	}
	return n.kind == kSpace
}

// seq lays out siblings, adding the spacing TeX gives operators.
func (c ctx) seq(kids []*node) box {
	var boxes []box
	for i, k := range kids {
		b := c.render(k)
		if !c.inScript && b.flat() {
			s := b.lines[0]
			core := k
			if k.kind == kScript && len(k.kids) > 0 {
				core = k.kids[0]
			}
			switch {
			case (k.kind == kChar || k.kind == kSym) && (spaced[k.text] || k.text == "=" || k.text == "<" || k.text == ">"):
				s = " " + s + " "
			case k.kind == kChar && (k.text == "+" || k.text == "-"):
				if i > 0 && !isOpen(kids[i-1]) {
					s = " " + s + " "
				}
			case k.kind == kChar && (k.text == "," || k.text == ";"):
				s += " "
			case core.kind == kOp || core.kind == kLimOp || (core.kind == kSym && (bigOps[core.text] || integrals[core.text])):
				if i > 0 && !isOpen(kids[i-1]) {
					s = " " + s
				}
				if i+1 < len(kids) && !(kids[i+1].kind == kChar && strings.ContainsAny(kids[i+1].text, "(),")) {
					s += " "
				}
			}
			b.lines[0] = s
		} else if !c.inScript && (k.kind == kScript && k.kids[0].kind == kSym && bigOps[k.kids[0].text] || k.kind == kScript && k.kids[0].kind == kLimOp) {
			b = hcat(b, text(" "))
		}
		boxes = append(boxes, b)
	}
	if len(boxes) == 0 {
		return text("")
	}
	out := hcat(boxes...)
	if out.flat() {
		out.lines[0] = squeeze(out.lines[0])
	}
	return out
}

func (c ctx) accent(n *node) box {
	b := c.render(n.kids[0])
	if !b.flat() {
		return b
	}
	mark := n.text
	runes := []rune(b.lines[0])
	wide := mark == "\u0305" || mark == "\u0332"
	var sb strings.Builder
	for i, r := range runes {
		sb.WriteRune(r)
		if (wide && r != ' ') || (!wide && i == 0) {
			sb.WriteString(mark)
		}
	}
	return text(sb.String())
}

// needsParens reports whether a flattened operand would be misread without
// grouping.
func needsParens(s string) bool {
	if width(s) <= 1 {
		return false
	}
	depth := 0
	for _, r := range s {
		switch {
		case r == '(' || r == '[':
			depth++
		case r == ')' || r == ']':
			depth--
		case depth == 0 && (r == ' ' || r == '/' || r == '+' || r == '−' || r == '·'):
			return true
		}
	}
	return false
}

func paren(s string) string {
	if needsParens(s) {
		return "(" + s + ")"
	}
	return s
}

func (c ctx) frac(n *node) box {
	inner := c
	if !c.display || c.inScript {
		inner.display = false
		num, den := inner.render(n.kids[0]), inner.render(n.kids[1])
		return text(paren(strings.TrimSpace(num.lines[0])) + "/" + paren(strings.TrimSpace(den.lines[0])))
	}
	num, den := c.render(n.kids[0]), c.render(n.kids[1])
	w := max(num.width(), den.width()) + 2
	rule := text(strings.Repeat("─", w))
	out := vstack('c', 1, num, rule, den)
	return out
}

func (c ctx) binom(n *node) box {
	if !c.display || c.inScript {
		inner := c
		inner.display = false
		return text("C(" + inner.render(n.kids[0]).lines[0] + ", " + inner.render(n.kids[1]).lines[0] + ")")
	}
	body := vstack('c', 0, c.render(n.kids[0]), c.render(n.kids[1]))
	body.base = 0
	if body.height() == 2 {
		body.base = 1
	}
	return delimit("(", body, ")")
}

func (c ctx) sqrt(n *node) box {
	body := c.render(n.kids[0])
	root := "√"
	if len(n.kids) > 1 {
		plain := c
		plain.font, plain.inScript, plain.display = "plain", true, false
		idx := strings.TrimSpace(plain.render(n.kids[1]).lines[0])
		switch idx {
		case "2":
		case "3":
			root = "∛"
		case "4":
			root = "∜"
		default:
			if s, ok := mapAll(idx, superscripts); ok {
				root = s + "√"
			} else {
				root = idx + "√"
			}
		}
	}
	if body.flat() {
		s := strings.TrimSpace(body.lines[0])
		if width(s) > 1 {
			s = "(" + s + ")"
		}
		return text(root + s)
	}
	w := body.width()
	out := box{base: body.base + 1}
	pad := strings.Repeat(" ", width(root))
	out.lines = append(out.lines, pad+"┌"+strings.Repeat("─", w+2))
	for i, l := range body.lines {
		lead := pad
		if i == body.height()-1 {
			lead = root
		}
		out.lines = append(out.lines, lead+"│ "+padRight(l, w)+" ")
	}
	return out
}

func mapAll(s string, table map[rune]rune) (string, bool) {
	var sb strings.Builder
	for _, r := range s {
		m, ok := table[r]
		if !ok {
			return "", false
		}
		sb.WriteRune(m)
	}
	return sb.String(), s != ""
}

// script renders a sub- or superscript on one line: real Unicode scripts when
// every character has one, otherwise an explicit ^(...) or _(...).
func (c ctx) script(n *node, table map[rune]rune, marker string) string {
	if n == nil {
		return ""
	}
	plain := c
	plain.font, plain.inScript, plain.display = "plain", true, false
	if c.font != "" && c.font != "italic" {
		plain.font = c.font // keep \mathbf{x}^{\mathbf{T}} distinctions honest
	}
	if s, ok := mapAll(strings.TrimSpace(plain.render(n).lines[0]), table); ok {
		return s
	}
	rich := c
	rich.inScript, rich.display = true, false
	s := strings.TrimSpace(rich.render(n).lines[0])
	if s == "" {
		return ""
	}
	if width(s) == 1 {
		return marker + s
	}
	return marker + "(" + s + ")"
}

func (c ctx) scripts(n *node) box {
	baseNode := n.kids[0]
	limits := c.display && !c.inScript &&
		(baseNode.kind == kLimOp || (baseNode.kind == kSym && bigOps[baseNode.text]))
	if limits {
		small := c
		small.display, small.inScript = false, true
		parts := []box{}
		baseIdx := 0
		if n.sup != nil {
			parts = append(parts, text(strings.TrimSpace(small.render(n.sup).lines[0])))
			baseIdx = 1
		}
		parts = append(parts, c.render(baseNode))
		if n.sub != nil {
			parts = append(parts, text(strings.TrimSpace(small.render(n.sub).lines[0])))
		}
		return vstack('c', baseIdx, parts...)
	}
	base := c.render(baseNode)
	sup := c.script(n.sup, superscripts, "^")
	sub := c.script(n.sub, subscripts, "_")
	if base.flat() {
		return text(base.lines[0] + sub + sup)
	}
	// Tall base: superscript at the top right, subscript at the bottom right.
	col := box{lines: make([]string, base.height()), base: base.base}
	col.lines[0] = sup
	col.lines[base.height()-1] += sub
	return hcat(base, col)
}

var integrals = map[string]bool{"∫": true, "∬": true, "∭": true, "∮": true}

var tall = map[string][4]string{ // top, middle, bottom, centre piece
	"(": {"⎛", "⎜", "⎝", "⎜"}, ")": {"⎞", "⎟", "⎠", "⎟"},
	"[": {"⎡", "⎢", "⎣", "⎢"}, "]": {"⎤", "⎥", "⎦", "⎥"},
	"{": {"⎧", "⎪", "⎩", "⎨"}, "}": {"⎫", "⎪", "⎭", "⎬"},
	"|": {"│", "│", "│", "│"}, "‖": {"║", "║", "║", "║"},
	"⌊": {"│", "│", "⎣", "│"}, "⌋": {"│", "│", "⎦", "│"},
	"⌈": {"⎡", "│", "│", "│"}, "⌉": {"⎤", "│", "│", "│"},
}

func delimiter(d string, h, base int) box {
	if d == "" {
		return text("")
	}
	parts, ok := tall[d]
	if h == 1 || !ok {
		b := box{lines: make([]string, h), base: base}
		for i := range b.lines {
			b.lines[i] = strings.Repeat(" ", width(d))
		}
		b.lines[base] = d
		return b
	}
	if h == 2 && (d == "{" || d == "}") {
		if d == "{" {
			return box{lines: []string{"⎰", "⎱"}, base: base}
		}
		return box{lines: []string{"⎱", "⎰"}, base: base}
	}
	b := box{lines: make([]string, h), base: base}
	for i := range b.lines {
		switch i {
		case 0:
			b.lines[i] = parts[0]
		case h - 1:
			b.lines[i] = parts[2]
		case h / 2:
			b.lines[i] = parts[3]
		default:
			b.lines[i] = parts[1]
		}
	}
	return b
}

func delimit(l string, body box, r string) box {
	return hcat(delimiter(l, body.height(), body.base), body, delimiter(r, body.height(), body.base))
}

func (c ctx) leftRight(n *node) box {
	return delimit(n.left, c.render(n.kids[0]), n.right)
}

func (c ctx) boxed(n *node) box {
	body := c.render(n.kids[0])
	if !c.display {
		return text("[" + body.lines[0] + "]")
	}
	w := body.width()
	out := box{base: body.base + 1}
	out.lines = append(out.lines, "┌"+strings.Repeat("─", w+2)+"┐")
	for _, l := range body.lines {
		out.lines = append(out.lines, "│ "+padRight(l, w)+" │")
	}
	out.lines = append(out.lines, "└"+strings.Repeat("─", w+2)+"┘")
	return out
}

func (c ctx) matrix(n *node) box {
	env := n.env
	delims := map[string][2]string{
		"pmatrix": {"(", ")"}, "bmatrix": {"[", "]"}, "Bmatrix": {"{", "}"},
		"vmatrix": {"|", "|"}, "Vmatrix": {"‖", "‖"}, "cases": {"{", ""},
		"smallmatrix": {"", ""},
	}[env]

	if !c.display || c.inScript {
		var rows []string
		for _, r := range n.rows {
			var cells []string
			for _, cell := range r {
				cells = append(cells, strings.TrimSpace(c.render(cell).lines[0]))
			}
			rows = append(rows, strings.Join(cells, " "))
		}
		return text(delims[0] + strings.Join(rows, "; ") + delims[1])
	}

	ncols := 0
	for _, r := range n.rows {
		ncols = max(ncols, len(r))
	}
	cells := make([][]box, len(n.rows))
	widths := make([]int, ncols)
	for i, r := range n.rows {
		cells[i] = make([]box, ncols)
		for j := range cells[i] {
			cells[i][j] = text("")
			if j < len(r) {
				b := c.render(r[j])
				for k := range b.lines {
					b.lines[k] = strings.TrimRight(b.lines[k], " ")
				}
				if b.flat() {
					b.lines[0] = strings.TrimSpace(b.lines[0])
				}
				cells[i][j] = b
			}
			widths[j] = max(widths[j], cells[i][j].width())
		}
	}

	colAlign := func(j int) byte {
		switch env {
		case "cases":
			return 'l'
		case "aligned", "align", "split", "eqnarray", "alignat", "alignedat", "flalign":
			if j%2 == 0 {
				return 'r'
			}
			return 'l'
		case "array":
			spec := strings.Map(func(r rune) rune {
				if r == 'l' || r == 'c' || r == 'r' {
					return r
				}
				return -1
			}, n.text)
			if j < len(spec) {
				return spec[j]
			}
		case "gathered", "gather", "equation", "multline":
			return 'c'
		}
		return 'c'
	}
	aligned := colAlign(0) == 'r' && env != "array"

	var rowBoxes []box
	for i := range cells {
		var parts []box
		for j, cell := range cells[i] {
			for k := range cell.lines {
				cell.lines[k] = align(cell.lines[k], widths[j], colAlign(j))
			}
			if j > 0 {
				gap := "  "
				if aligned && j%2 == 1 {
					gap = " "
				}
				parts = append(parts, text(gap))
			}
			parts = append(parts, cell)
		}
		rowBoxes = append(rowBoxes, hcat(parts...))
	}
	body := vstack('l', 0, rowBoxes...)
	body.base = (body.height() - 1) / 2
	return delimit(delims[0], body, delims[1])
}
