-- Code generated by litgo from litgo.lit.md; DO NOT EDIT.

-- Chunk editing and navigation: :Untangle, :RenameChunk, gd and K.
local M = {}

local function litgo()
  return require("litgo")
end

local function refresh(buf)
  require("litgo.render").refresh(buf)
end

--- The chunk the cursor is on: a reference, a chunk directive, or the body of
--- a chunk block. Asks litgo afresh so it is right even mid-edit.
local function chunk_at_cursor(buf)
  local analysis, err = litgo().query(buf, { "analyze", "--path", vim.api.nvim_buf_get_name(buf) })
  if not analysis then
    return nil, err
  end
  local pos = vim.api.nvim_win_get_cursor(0)
  local row, col = pos[1] - 1, pos[2]
  local on_line
  for _, c in ipairs(analysis.chunks or {}) do
    for _, r in ipairs(c.refs) do
      if r.line == row then
        if col >= r.col and col < r.end_col then
          return c, "ref"
        end
        on_line = on_line or c
      end
    end
  end
  if on_line then
    return on_line, "ref"
  end
  for _, c in ipairs(analysis.chunks or {}) do
    for _, d in ipairs(c.defs) do
      if row == d.directive or (row >= d.first - 1 and row <= d.last + 1) then
        return c, "def"
      end
    end
  end
  return nil, "the cursor is not on a chunk or a chunk reference"
end

--- :[range]Untangle [name]
--- A charwise visual selection that stops short of whole lines becomes an
--- inline reference (a block comment); anything else a whole-line one.
function M.untangle(buf, o)
  local args = {
    "untangle",
    "--path", vim.api.nvim_buf_get_name(buf),
    "--start", tostring(o.line1 - 1),
    "--end", tostring(o.line2 - 1),
  }
  local s, e = vim.api.nvim_buf_get_mark(buf, "<"), vim.api.nvim_buf_get_mark(buf, ">")
  local from_visual = o.range == 2 and s[1] == o.line1 and e[1] == o.line2
  if from_visual and vim.fn.visualmode() == "v" then
    local last = vim.api.nvim_buf_get_lines(buf, e[1] - 1, e[1], false)[1] or ""
    local end_col = math.min(e[2], math.max(#last - 1, 0))
    -- '> is the first byte of the last selected character; step past it.
    end_col = end_col + #vim.fn.strcharpart(last:sub(end_col + 1), 0, 1)
    if vim.o.selection == "exclusive" then
      end_col = math.min(e[2], #last)
    end
    vim.list_extend(args, { "--start-col", tostring(s[2]), "--end-col", tostring(end_col) })
  end
  if o.args and o.args ~= "" then
    vim.list_extend(args, { "--name", o.args })
  end

  local res, err = litgo().query(buf, args)
  if not res then
    vim.notify("litgo: " .. err, vim.log.levels.ERROR)
    return
  end
  litgo().apply_edits(buf, res.edits)
  local target = litgo().config.untangle.jump and res.def_line or res.ref_line
  vim.api.nvim_win_set_cursor(0, { target + 1, 0 })
  vim.cmd("normal! ^")
  refresh(buf)
  vim.notify(("litgo: ⟨%s⟩ → line %d   (:RenameChunk to rename)"):format(res.name, res.def_line + 1))
end

--- :RenameChunk [new name] — renames every definition and every reference.
function M.rename(buf, new_name)
  local chunk, err = chunk_at_cursor(buf)
  if not chunk then
    vim.notify("litgo: " .. err, vim.log.levels.WARN)
    return
  end
  local function apply(name)
    if not name or vim.trim(name) == "" or name == chunk.name then
      return
    end
    local res, rename_err = litgo().query(buf, {
      "rename", "--path", vim.api.nvim_buf_get_name(buf), "--from", chunk.name, "--to", name,
    })
    if not res then
      vim.notify("litgo: " .. rename_err, vim.log.levels.ERROR)
      return
    end
    litgo().apply_edits(buf, res.edits)
    refresh(buf)
    vim.notify(("litgo: ⟨%s⟩ → ⟨%s⟩ (%d place%s)"):format(chunk.name, res.name, #res.edits, #res.edits == 1 and "" or "s"))
  end
  if new_name and new_name ~= "" then
    apply(new_name)
  else
    vim.ui.input({ prompt = "Rename ⟨" .. chunk.name .. "⟩ to: ", default = chunk.name }, apply)
  end
end

--- gd: from a reference to its definition; from a definition to its uses.
--- The language server does this better, because it does it for Go as well:
--- on a chunk it answers for itself, and anywhere else in a block, for gopls.
function M.goto_chunk()
  local buf = vim.api.nvim_get_current_buf()
  if require("litgo.lsp").active(buf) then
    vim.lsp.buf.definition()
    return
  end
  local chunk, where = chunk_at_cursor(buf)
  if not chunk then
    pcall(vim.cmd, "normal! gd")
    return
  end
  vim.cmd("normal! m'")
  if where == "ref" then
    if #chunk.defs == 0 then
      vim.notify("litgo: ⟨" .. chunk.name .. "⟩ is not defined", vim.log.levels.WARN)
      return
    end
    vim.api.nvim_win_set_cursor(0, { chunk.defs[1].first + 1, 0 })
  elseif #chunk.refs == 1 then
    vim.api.nvim_win_set_cursor(0, { chunk.refs[1].line + 1, chunk.refs[1].col })
  elseif #chunk.refs == 0 then
    vim.notify("litgo: ⟨" .. chunk.name .. "⟩ is never used", vim.log.levels.WARN)
  else
    local items = {}
    for _, r in ipairs(chunk.refs) do
      items[#items + 1] = {
        bufnr = buf,
        lnum = r.line + 1,
        col = r.col + 1,
        text = vim.trim(vim.api.nvim_buf_get_lines(buf, r.line, r.line + 1, false)[1] or ""),
      }
    end
    vim.fn.setloclist(0, {}, " ", { title = "uses of ⟨" .. chunk.name .. "⟩", items = items })
    vim.cmd("lopen")
  end
  vim.cmd("normal! zvzz")
end

--- K: preview the chunk behind a reference without leaving the host block.
--- This too is the language server's if it is there: a chunk on a reference,
--- gopls's documentation on a name.
function M.hover()
  local buf = vim.api.nvim_get_current_buf()
  if require("litgo.lsp").active(buf) then
    vim.lsp.buf.hover()
    return
  end
  local chunk, where = chunk_at_cursor(buf)
  if not chunk or where ~= "ref" or #chunk.defs == 0 then
    pcall(vim.cmd, "normal! K")
    return
  end
  local lines = { "⟨" .. chunk.name .. "⟩ ≡", "```go" }
  for _, d in ipairs(chunk.defs) do
    vim.list_extend(lines, vim.api.nvim_buf_get_lines(buf, d.first, d.last + 1, false))
  end
  lines[#lines + 1] = "```"
  vim.lsp.util.open_floating_preview(lines, "markdown", { border = "rounded", focus_id = "litgo-chunk" })
end

return M
