-- Code generated by litgo from litgo.lit.md; DO NOT EDIT.

-- litgo.nvim: a tight loop for literate Go in .lit.md files.
--
-- The plugin is deliberately thin. Everything that knows about the format
-- lives in the `litgo` binary; Lua asks it questions (document on stdin, JSON
-- back) and turns the answers into extmarks, edits and diagnostics.
local M = {}

M.config = {
  bin = nil, -- path to the litgo binary; found on $PATH when nil
  render = {
    enabled = true,
    math = true,
    mermaid = true,
    tables = true, -- line up the columns of Markdown tables
    proofs = true, -- typeset the formulas of //@ annotations: ^ as ∧, <= as ≤, Forall as ∀
    chunks = true, -- show `// <<name>>` as ⟨name⟩ and chunk directives as ⟨name⟩ ≡
    conceal_source = true, -- hide diagram/display-math source while the cursor is elsewhere
    upright = false, -- true: keep math letters upright instead of 𝑖𝑡𝑎𝑙𝑖𝑐
    indent = 4,
    debounce_ms = 150,
  },
  run = {
    vet = false, -- also report `go vet` findings as warnings
    timeout = "60s", -- kill runaway programs; "" to disable
    jump = true, -- move the cursor to the first error
    focus = true, -- put the cursor in the output panel when the run ends, so q closes it
    on_save = false, -- :TangleCompileAndRun after every write (toggle with :LitWatch)
    panel_height = 12,
  },
  lsp = {
    enabled = true, -- run `litgo lsp`: chunk, syntax, type and proof errors as you type
    virtual_lines = true, -- show them under the offending line rather than beside it
    gopls = true, -- completion, hover, definitions, references, rename in Go blocks; or a path, or false
    settings = nil, -- gopls settings, e.g. { buildFlags = { "-tags=integration" } }
    completion = "auto", -- "auto": Neovim's own completion popup as you type, unless a
    -- completion plugin is loaded. true forces it on, false off.
  },
  weave = { open = true },
  scaffold = true, -- fill a new, empty .lit.md with a program that already runs
  untangle = { jump = false }, -- true: go to the new chunk to document it right away
  keymaps = {
    run = "<localleader>r",
    stop = "<localleader>s",
    tangle = "<localleader>t",
    weave = "<localleader>w",
    prove = "<localleader>p",
    untangle = "<localleader>u", -- visual mode
    rename = "<localleader>n",
    toggle_render = "<localleader>v",
    goto_chunk = "gd",
    hover = "K",
  },
}

local function plugin_root()
  local src = debug.getinfo(1, "S").source:sub(2)
  return vim.fn.fnamemodify(src, ":p:h:h:h")
end

local warned = false

--- Locate the litgo binary: explicit config, a build inside the plugin's own
--- checkout (what a plugin manager's build step produces), then $PATH.
function M.bin()
  if M._bin then
    return M._bin
  end
  local candidates = { plugin_root() .. "/bin/litgo", "litgo" }
  if M.config.bin then
    table.insert(candidates, 1, vim.fn.expand(M.config.bin))
  end
  for _, c in ipairs(candidates) do
    if c and vim.fn.executable(c) == 1 then
      M._bin = c
      return c
    end
  end
  if not warned then
    warned = true
    vim.notify(
      "litgo: binary not found. Run `go build -o bin/litgo .` in " .. plugin_root() .. ", or set `bin` in setup().",
      vim.log.levels.ERROR
    )
  end
end

--- Run litgo synchronously with the buffer on stdin; returns decoded JSON.
function M.query(buf, args)
  local bin = M.bin()
  if not bin then
    return nil, "litgo binary not found"
  end
  local cmd = vim.list_extend({ bin }, args)
  local text = table.concat(vim.api.nvim_buf_get_lines(buf, 0, -1, false), "\n") .. "\n"
  local res = vim.system(cmd, { stdin = text, text = true }):wait(5000)
  local ok, decoded = pcall(vim.json.decode, res.stdout or "")
  if not ok or type(decoded) ~= "table" then
    return nil, (res.stderr ~= "" and res.stderr) or "litgo returned no JSON"
  end
  if decoded.error then
    return nil, decoded.error
  end
  return decoded
end

--- Apply bottom-up line edits as a single undo step.
function M.apply_edits(buf, edits)
  for _, e in ipairs(edits) do
    vim.api.nvim_buf_set_lines(buf, e.start, e["end"], false, e.lines)
  end
end

function M.is_lit(buf)
  return vim.api.nvim_buf_get_name(buf):match("%.lit%.md$") ~= nil
end

local function define_highlights()
  local links = {
    LitgoMath = "Special",
    LitgoDiagram = "Function",
    LitgoTableRule = "Comment",
    LitgoChunk = "Title",
    LitgoFile = "Directory",
    LitgoInfo = "Comment",
    LitgoError = "DiagnosticError",
    LitgoOk = "DiagnosticOk",
  }
  for name, target in pairs(links) do
    vim.api.nvim_set_hl(0, name, { link = target, default = true })
  end
  local dark = vim.o.background ~= "light"
  local violet = dark and "#c792ea" or "#7c3aed"
  local faded = dark and "#a58fc4" or "#8b6fc0"
  for name, spec in pairs({
    LitgoProofKeyword = { fg = violet, bold = true },
    LitgoProof = { fg = faded },
    LitgoProofError = { fg = violet },
    LitgoProofWarn = { fg = faded, italic = true },
    LitgoProofUnderline = { undercurl = true, sp = violet },
  }) do
    spec.default = true
    vim.api.nvim_set_hl(0, name, spec)
  end
end

--- Is a line (0-based; the cursor's by default) inside a Go block?
function M.in_go_block(buf, line)
  buf = buf or 0
  if not M.is_lit(buf) then
    return false
  end
  line = line or (vim.api.nvim_win_get_cursor(0)[1] - 1)
  local lang, fence = nil, nil
  for _, l in ipairs(vim.api.nvim_buf_get_lines(buf, 0, line, false)) do
    local marks, rest = l:match("^%s*(``+`)%s*(.*)$")
    if marks then
      if not fence then
        fence, lang = marks, rest:match("^[%w_+-]*")
      elseif #marks >= #fence then
        fence, lang = nil, nil
      end
    end
  end
  return lang == "go"
end

--- Fill an empty .lit.md buffer with a program that runs.
local function scaffold(buf)
  if vim.api.nvim_buf_line_count(buf) > 1 or vim.api.nvim_buf_get_lines(buf, 0, 1, false)[1] ~= "" then
    return
  end
  local name = vim.api.nvim_buf_get_name(buf)
  local title = vim.fn.fnamemodify(name, ":t"):gsub("%.lit%.md$", "")
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, {
    "<!-- tangler: go -->",
    "<!-- package: main -->",
    "<!-- imports: fmt -->",
    "",
    "# " .. title,
    "",
    "```go",
    "func main() {",
    '\tfmt.Println("Hello from ' .. title .. '!")',
    "}",
    "```",
  })
end

--- Set up one .lit.md buffer: commands, keymaps, rendering.
function M.attach(buf)
  if vim.b[buf].litgo_attached or not M.is_lit(buf) then
    return
  end
  vim.b[buf].litgo_attached = true
  if M.config.scaffold then
    scaffold(buf)
  end

  local run = require("litgo.run")
  local chunks = require("litgo.chunks")
  local render = require("litgo.render")

  local function command(name, fn, opts)
    vim.api.nvim_buf_create_user_command(buf, name, fn, opts or {})
  end
  command("Tangle", function(o)
    run.tangle(buf, o.bang)
  end, { bang = true, desc = "Write the Go source (! overwrites files litgo did not generate)" })
  command("Weave", function(o)
    run.weave(buf, o.args)
  end, { nargs = "?", desc = "Write and open the woven PDF (or :Weave html)" })
  command("TangleCompileAndRun", function(o)
    run.run(buf, o.fargs)
  end, { nargs = "*", desc = "Tangle, compile and run; errors appear inline" })
  command("Prove", function()
    run.prove(buf)
  end, { desc = "Check the //@ annotations: contracts, invariants, termination" })
  command("LitStop", function()
    run.stop()
  end, { desc = "Kill the running program" })
  command("LitWatch", function()
    M.config.run.on_save = not M.config.run.on_save
    vim.notify("litgo: run on save " .. (M.config.run.on_save and "on" or "off"))
  end, { desc = "Toggle :TangleCompileAndRun on every write" })
  command("LitClear", function()
    run.clear(buf)
  end, { desc = "Clear compile and run diagnostics" })
  command("Untangle", function(o)
    chunks.untangle(buf, o)
  end, { range = true, nargs = "*", desc = "Move the selection into a named chunk at the bottom" })
  command("RenameChunk", function(o)
    chunks.rename(buf, o.args)
  end, { nargs = "*", desc = "Rename the chunk under the cursor everywhere" })
  command("LitRender", function()
    render.toggle(buf)
  end, { desc = "Toggle math, diagram and chunk rendering" })

  local keys = M.config.keymaps or {}
  local function map(mode, lhs, rhs, desc)
    if lhs and lhs ~= "" then
      vim.keymap.set(mode, lhs, rhs, { buffer = buf, silent = true, desc = "litgo: " .. desc })
    end
  end
  map("n", keys.run, "<cmd>TangleCompileAndRun<cr>", "tangle, compile and run")
  map("n", keys.stop, "<cmd>LitStop<cr>", "stop the program")
  map("n", keys.tangle, "<cmd>Tangle<cr>", "tangle")
  map("n", keys.weave, "<cmd>Weave<cr>", "weave")
  map("n", keys.prove, "<cmd>Prove<cr>", "prove the annotations")
  map("x", keys.untangle, ":Untangle<cr>", "untangle selection into a chunk")
  map("n", keys.rename, "<cmd>RenameChunk<cr>", "rename chunk")
  map("n", keys.toggle_render, "<cmd>LitRender<cr>", "toggle rendering")
  map("n", keys.goto_chunk, chunks.goto_chunk, "go to chunk definition / uses")
  map("n", keys.hover, chunks.hover, "preview chunk")

  vim.api.nvim_create_autocmd("BufWritePost", {
    buffer = buf,
    callback = function()
      if M.config.run.on_save then
        run.run(buf, {})
      end
    end,
  })

  run.attach(buf)
  render.attach(buf)
  require("litgo.lsp").start(buf)
end

function M.setup(opts)
  M.config = vim.tbl_deep_extend("force", M.config, opts or {})
  M._bin = nil
  define_highlights()
  require("litgo.proof").setup()
  local group = vim.api.nvim_create_augroup("litgo", { clear = true })
  vim.api.nvim_create_autocmd({ "BufReadPost", "BufNewFile", "BufWinEnter" }, {
    group = group,
    pattern = "*.lit.md",
    callback = function(ev)
      M.attach(ev.buf)
    end,
  })
  vim.api.nvim_create_autocmd("ColorScheme", { group = group, callback = define_highlights })
  for _, buf in ipairs(vim.api.nvim_list_bufs()) do
    if vim.api.nvim_buf_is_loaded(buf) then
      M.attach(buf)
    end
  end
end

return M
