-- Code generated by litgo from litgo.lit.md; DO NOT EDIT.

local M = {}

--- The completion plugins that drive completion themselves.
local engines = { "blink.cmp", "cmp", "coq" }

local function engine_loaded()
  for _, name in ipairs(engines) do
    if package.loaded[name] then
      return true
    end
  end
  return false
end

--- Turn Neovim's own completion on for this buffer, unless something else
--- is doing the job. Deferred to the first insert, because that is when a
--- lazily loaded completion plugin arrives.
local function complete_with(id, buf)
  vim.api.nvim_create_autocmd("InsertEnter", {
    buffer = buf,
    once = true,
    callback = function()
      vim.schedule(function()
        if not engine_loaded() and vim.api.nvim_buf_is_valid(buf) then
          vim.lsp.completion.enable(true, id, buf, { autotrigger = true })
        end
      end)
    end,
  })
end

local function litgo()
  return require("litgo")
end

--- What to tell the server about gopls: where it is, to do without ("off"),
--- or to look for itself ("").
local function gopls(want)
  if want == false then
    return "off"
  elseif type(want) == "string" then
    return vim.fn.expand(want)
  end
  local mason = vim.fn.stdpath("data") .. "/mason/bin/gopls"
  if vim.fn.executable("gopls") == 0 and vim.fn.executable(mason) == 1 then
    return mason
  end
  return ""
end

function M.start(buf)
  local cfg = litgo().config.lsp
  local bin = cfg.enabled and litgo().bin()
  if not bin then
    return
  end
  local name = vim.api.nvim_buf_get_name(buf)
  vim.lsp.start({
    name = "litgo",
    cmd = { bin, "lsp", "--gopls", gopls(cfg.gopls) },
    init_options = cfg.settings,
    root_dir = vim.fs.root(name, { "go.mod", ".git" }) or vim.fs.dirname(name),
    on_attach = function(client, bufnr)
      vim.diagnostic.config({
        virtual_lines = cfg.virtual_lines,
        virtual_text = not cfg.virtual_lines,
        severity_sort = true,
      }, vim.lsp.diagnostic.get_namespace(client.id))
      if cfg.completion == "auto" then
        complete_with(client.id, bufnr)
      elseif cfg.completion then
        vim.lsp.completion.enable(true, client.id, bufnr, { autotrigger = true })
      end
    end,
  }, { bufnr = buf })
end

local function client(buf)
  return vim.lsp.get_clients({ bufnr = buf, name = "litgo" })[1]
end

--- Is the server attached to this buffer?
function M.active(buf)
  return client(buf) ~= nil
end

--- Is the server reporting errors in this buffer right now? If it is, a
--- run's compile errors would only repeat them.
function M.reporting(buf)
  local c = client(buf)
  return c ~= nil
    and #vim.diagnostic.get(buf, {
        namespace = vim.lsp.diagnostic.get_namespace(c.id),
        severity = vim.diagnostic.severity.ERROR,
      })
      > 0
end

return M
