-- Code generated by litgo from litgo.lit.md; DO NOT EDIT.

-- In-buffer rendering: LaTeX as Unicode, Mermaid as box drawings, and chunk
-- syntax as ⟨names⟩. Whatever the cursor touches falls back to its source,
-- with block renderings kept underneath as a live preview.
local M = {}

local ns = vim.api.nvim_create_namespace("litgo-render")

local check_ns = vim.api.nvim_create_namespace("litgo-check")

M.check_ns = check_ns

-- bufnr -> { items, chunks, enabled, dirty, timer, cursor_row }
local state = {}

local function litgo()
  return require("litgo")
end

function M.get(buf)
  return state[buf]
end

local function virt_lines(lines, hl, indent)
  local pad = string.rep(" ", indent)
  local out = {}
  for _, l in ipairs(lines) do
    out[#out + 1] = { { pad .. l, hl } }
  end
  return out
end

local function mark(buf, row, col, opts)
  opts.strict = false
  pcall(vim.api.nvim_buf_set_extmark, buf, ns, row, col, opts)
end

local function wanted(item, cfg)
  if item.kind == "math" or item.kind == "math-block" then
    return cfg.math
  elseif item.kind == "mermaid" then
    return cfg.mermaid
  elseif item.kind == "table" then
    return cfg.tables
  elseif item.kind == "vego-math" then
    return cfg.proofs
  end
  return cfg.chunks
end

--- Redraw every extmark. Cheap enough (one pass over the items) to run on
--- each cursor-line change, which keeps the reveal logic trivial.
function M.draw(buf)
  local st = state[buf]
  if not st or not vim.api.nvim_buf_is_valid(buf) then
    return
  end
  vim.api.nvim_buf_clear_namespace(buf, ns, 0, -1)
  if not st.enabled or not st.items then
    return
  end
  local cfg = litgo().config.render
  local cursor = -1
  if vim.api.nvim_get_current_buf() == buf then
    cursor = vim.api.nvim_win_get_cursor(0)[1] - 1
  end
  st.cursor_row = cursor
  local last = vim.api.nvim_buf_line_count(buf) - 1

  for _, it in ipairs(st.items) do
    if it.kind == "vego" then
      -- An annotation keeps its colour under the cursor too: nothing is
      -- hidden, so there is nothing to reveal.
      local key_end = it.col + 3
      if it.name and it.name ~= "" then
        local line = vim.api.nvim_buf_get_lines(buf, it.line, it.line + 1, false)[1] or ""
        local _, e = line:find(it.name, it.col + 4, true)
        key_end = e or key_end
      end
      mark(buf, it.line, it.col, { end_col = key_end, hl_group = "LitgoProofKeyword", priority = 210 })
      mark(buf, it.line, key_end, { end_col = it.end_col, hl_group = "LitgoProof", priority = 210 })
    elseif wanted(it, cfg) then
      local under_cursor = cursor >= it.line and cursor <= it.end_line
      if it.lines then
        local hl = it.kind == "mermaid" and "LitgoDiagram" or "LitgoMath"
        if it.error then
          hl = "LitgoError"
        end
        local vl = virt_lines(it.lines, hl, cfg.indent)
        if under_cursor or not cfg.conceal_source then
          -- Editing: keep the source visible and preview underneath. Anchor to
          -- the line after the block: treesitter conceals fence lines, and
          -- virtual lines hanging off a concealed line disappear with it.
          if it.end_line < last then
            mark(buf, it.end_line + 1, 0, { virt_lines = vl, virt_lines_above = true })
          else
            mark(buf, it.end_line, 0, { virt_lines = vl })
          end
        elseif it.end_line < last then
          mark(buf, it.line, 0, { end_row = it.end_line, conceal_lines = "" })
          mark(buf, it.end_line + 1, 0, { virt_lines = vl, virt_lines_above = true })
        elseif it.line > 0 then
          mark(buf, it.line, 0, { end_row = it.end_line, conceal_lines = "" })
          mark(buf, it.line - 1, 0, { virt_lines = vl })
        else
          mark(buf, it.end_line, 0, { virt_lines = vl })
        end
      elseif it.table then
        local t = it.table
        local function looks(cell)
          return (cell.col - cell.from) + vim.fn.strdisplaywidth(cell.text) + (cell.to - cell.end_col)
        end
        if not it.widths then
          it.widths = {}
          for _, row in ipairs(t.rows) do
            for c, cell in ipairs(row.cells) do
              it.widths[c] = math.max(it.widths[c] or 3, looks(cell))
            end
          end
        end
        local function spaces(row, col, n)
          if n > 0 then
            mark(buf, row, col, { virt_text = { { string.rep(" ", n) } }, virt_text_pos = "inline" })
          end
        end
        for _, row in ipairs(t.rows) do
          if row.line ~= cursor then
            for _, h in ipairs(row.hide or {}) do
              mark(buf, row.line, h[1], { end_col = h[2], conceal = "" })
            end
            for c, cell in ipairs(row.cells) do
              local gap = (it.widths[c] or 0) - looks(cell)
              local before = ({ right = gap, center = math.floor(gap / 2) })[t.align[c]] or 0
              spaces(row.line, cell.from, before)
              spaces(row.line, cell.to, gap - before)
            end
          end
        end
        if it.line + 1 ~= cursor then
          for c, cell in ipairs(t.rule) do
            local w, a = it.widths[c] or 3, t.align[c]
            local dashes = (a == "center" and ":" or "-") .. string.rep("-", w - 2) .. (a == "left" and "-" or ":")
            mark(buf, it.line + 1, cell.from, { end_col = cell.to, conceal = "" })
            mark(buf, it.line + 1, cell.from, { virt_text = { { dashes, "LitgoTableRule" } }, virt_text_pos = "inline" })
          end
        end
      else
        local hl = ({ math = "LitgoMath", file = "LitgoFile", ["vego-math"] = "LitgoProof" })[it.kind] or "LitgoChunk"
        if it.info == "undefined" then
          hl = "LitgoError"
        end
        if not under_cursor and it.text then
          mark(buf, it.line, it.col, { end_col = it.end_col, conceal = "" })
          mark(buf, it.line, it.col, { virt_text = { { it.text, hl } }, virt_text_pos = "inline" })
        end
        if it.info and it.info ~= "" then
          mark(buf, it.line, 0, { virt_text = { { "  " .. it.info, "LitgoInfo" } }, virt_text_pos = "eol" })
        end
      end
    end
  end
end

local function to_diagnostics(list, buf)
  local name = vim.api.nvim_buf_get_name(buf)
  local count = vim.api.nvim_buf_line_count(buf)
  local out = {}
  for _, d in ipairs(list or {}) do
    if not d.file or d.file == "" or d.file == name then
      out[#out + 1] = {
        lnum = math.min(d.line, count - 1),
        col = d.col or 0,
        end_col = (d.end_col and d.end_col > 0) and d.end_col or nil,
        severity = d.severity,
        message = d.message,
        source = d.source,
      }
    end
  end
  return out
end

M.to_diagnostics = to_diagnostics

--- Ask litgo about the buffer and redraw when the answer is still current.
function M.refresh(buf)
  local st = state[buf]
  local bin = litgo().bin()
  if not st or not bin or not vim.api.nvim_buf_is_valid(buf) then
    return
  end
  local tick = vim.api.nvim_buf_get_changedtick(buf)
  local cmd = { bin, "analyze", "--path", vim.api.nvim_buf_get_name(buf) }
  if litgo().config.render.upright then
    cmd[#cmd + 1] = "--upright"
  end
  local text = table.concat(vim.api.nvim_buf_get_lines(buf, 0, -1, false), "\n") .. "\n"
  vim.system(cmd, { stdin = text, text = true }, function(res)
    vim.schedule(function()
      if not vim.api.nvim_buf_is_valid(buf) then
        return
      end
      if vim.api.nvim_buf_get_changedtick(buf) ~= tick then
        -- The buffer moved on. Usually a debounced request is already queued;
        -- if not (the tick also bumps while a file finishes loading), ask again.
        if not st.dirty then
          M.refresh(buf)
        end
        return
      end
      local ok, decoded = pcall(vim.json.decode, res.stdout or "")
      if not ok or type(decoded) ~= "table" then
        return
      end
      st.items, st.chunks, st.dirty = decoded.items, decoded.chunks, false
      M.draw(buf)
      -- Reporting problems is the language server's job. Without it, the
      -- ones this analysis found are better than none; syntax errors while
      -- typing are noise, so they wait until insert mode ends.
      if require("litgo.lsp").active(buf) then
        vim.diagnostic.reset(check_ns, buf)
      elseif vim.api.nvim_get_mode().mode:sub(1, 1) ~= "i" then
        vim.diagnostic.set(check_ns, buf, to_diagnostics(decoded.diagnostics, buf))
      end
    end)
  end)
end

function M.schedule(buf)
  local st = state[buf]
  if not st then
    return
  end
  st.dirty = true
  if st.timer then
    st.timer:stop()
  else
    st.timer = vim.uv.new_timer()
  end
  st.timer:start(litgo().config.render.debounce_ms, 0, function()
    vim.schedule(function()
      M.refresh(buf)
    end)
  end)
end

function M.toggle(buf)
  local st = state[buf]
  if st then
    st.enabled = not st.enabled
    M.draw(buf)
  end
end

local function window_options(buf)
  for _, win in ipairs(vim.fn.win_findbuf(buf)) do
    vim.wo[win][0].conceallevel = 2
    vim.wo[win][0].concealcursor = ""
  end
end

function M.attach(buf)
  state[buf] = { enabled = litgo().config.render.enabled }
  local group = vim.api.nvim_create_augroup("litgo-render-" .. buf, { clear = true })
  vim.api.nvim_create_autocmd({ "TextChanged", "TextChangedI", "TextChangedP" }, {
    group = group,
    buffer = buf,
    callback = function()
      M.schedule(buf)
    end,
  })
  vim.api.nvim_create_autocmd("InsertLeave", {
    group = group,
    buffer = buf,
    callback = function()
      M.refresh(buf)
    end,
  })
  vim.api.nvim_create_autocmd({ "CursorMoved", "CursorMovedI", "BufEnter", "WinEnter" }, {
    group = group,
    buffer = buf,
    callback = function()
      local st = state[buf]
      -- While an analysis is pending the item positions are stale; the
      -- refresh that follows will redraw.
      if st and not st.dirty and st.cursor_row ~= vim.api.nvim_win_get_cursor(0)[1] - 1 then
        M.draw(buf)
      end
    end,
  })
  vim.api.nvim_create_autocmd("BufWinEnter", {
    group = group,
    buffer = buf,
    callback = function()
      window_options(buf)
    end,
  })
  vim.api.nvim_create_autocmd("BufWipeout", {
    group = group,
    buffer = buf,
    callback = function()
      local st = state[buf]
      if st and st.timer then
        st.timer:stop()
        st.timer:close()
      end
      state[buf] = nil
    end,
  })
  vim.diagnostic.config({ virtual_text = true, signs = true, underline = true, [require("litgo.proof").handler] = true }, check_ns)
  window_options(buf)
  M.refresh(buf)
end

return M
