// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/tlehman/litgo/internal/check"
	"github.com/tlehman/litgo/internal/lit"
	"github.com/tlehman/litgo/internal/lsp"
	"github.com/tlehman/litgo/internal/vego"
	"github.com/tlehman/litgo/internal/weave"
)

const usage = `litgo — literate Go

  litgo tangle [--force] [--stdout] FILE.lit.md...   write the Go source
  litgo run    [--vet] [--no-prove] [--timeout 30s] FILE [-- ARGS]
                                                     tangle, prove, compile and run
  litgo weave  [--to pdf|html|typ|md] [-o OUT] FILE  write a PDF through Typst, or a web page
  litgo check  FILE.lit.md...                        chunk, syntax, type and proof errors; writes nothing
  litgo prove  [--json] FILE.lit.md...               check the //@ annotations: contracts, invariants, termination
  litgo cat    FILE.lit.md                           print with math and diagrams rendered
  litgo fmt    [-w] FILE.lit.md                      gofmt the code blocks

Editor protocol (document on stdin, JSON on stdout):
  litgo analyze  [--path P] [--upright]
  litgo untangle --start L --end L [--start-col C --end-col C] [--name N]
  litgo rename   --from NAME --to NAME
  litgo run --json FILE                              one JSON event per line
  litgo lsp [--gopls PATH|off]                       language server on stdin/stdout: errors as you type,
                                                     and gopls for the Go in the code blocks

Positions in the editor protocol are 0-based; columns are bytes.
`

const VERSION = "0.2.3"

func main() {
	if len(os.Args) < 2 {
		fmt.Fprint(os.Stderr, usage)
		os.Exit(2)
	}
	cmd, args := os.Args[1], os.Args[2:]
	switch cmd {
	case "tangle":
		os.Exit(cmdTangle(args))
	case "run":
		os.Exit(cmdRun(args))
	case "weave":
		os.Exit(cmdWeave(args))
	case "check":
		os.Exit(cmdCheck(args))
	case "prove":
		os.Exit(cmdProve(args))
	case "cat":
		os.Exit(cmdCat(args))
	case "fmt":
		os.Exit(cmdFmt(args))
	case "analyze":
		os.Exit(cmdAnalyze(args))
	case "untangle":
		os.Exit(cmdUntangle(args))
  case "version":
    os.Exit(cmdVersion(args))
	case "rename":
		os.Exit(cmdRename(args))
	case "lsp":
		fs := flag.NewFlagSet("lsp", flag.ExitOnError)
		gopls := fs.String("gopls", "", "the gopls to put behind the server; found when empty, none when \"off\"")
		fs.Parse(args)
		if err := lsp.Serve(os.Stdin, os.Stdout, *gopls); err != nil {
			fmt.Fprintln(os.Stderr, "litgo lsp:", err)
			os.Exit(1)
		}
	case "help", "-h", "--help":
		fmt.Print(usage)
	default:
		fmt.Fprintf(os.Stderr, "litgo: unknown command %q\n\n%s", cmd, usage)
		os.Exit(2)
	}
}

func load(path string) (*lit.Doc, error) {
	abs, err := filepath.Abs(path)
	if err != nil {
		return nil, err
	}
	src, err := os.ReadFile(abs)
	if err != nil {
		return nil, err
	}
	return lit.Parse(abs, src), nil
}

func stdinDoc(path string) *lit.Doc {
	src, _ := io.ReadAll(os.Stdin)
	if path == "" {
		path = "stdin.lit.md"
	}
	return lit.Parse(path, src)
}

func printJSON(v any) int {
	enc := json.NewEncoder(os.Stdout)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(v); err != nil {
		fmt.Fprintln(os.Stderr, "litgo:", err)
		return 1
	}
	return 0
}

func jsonError(err error) int {
	printJSON(map[string]string{"error": err.Error()})
	return 1
}

func report(diags []lit.Diag) (errors int) {
	r := &reporter{seen: map[string]bool{}}
	for _, d := range diags {
		r.diag(d)
		if d.Severity == lit.SevError {
			errors++
		}
	}
	return errors
}

func cmdTangle(args []string) int {
	fs := flag.NewFlagSet("tangle", flag.ExitOnError)
	force := fs.Bool("force", false, "overwrite files litgo did not generate")
	stdout := fs.Bool("stdout", false, "print instead of writing")
	fs.Parse(args)
	if fs.NArg() == 0 {
		fmt.Fprintln(os.Stderr, "litgo tangle: no input files")
		return 2
	}
	status := 0
	for _, path := range fs.Args() {
		doc, err := load(path)
		if err != nil {
			fmt.Fprintln(os.Stderr, "litgo:", err)
			status = 1
			continue
		}
		res := doc.Tangle()
		if report(res.Diags) > 0 {
			status = 1
			continue
		}
		for _, o := range res.Files {
			if *stdout {
				if len(res.Files) > 1 {
					fmt.Printf("==> %s <==\n", relPath(o.Path))
				}
				os.Stdout.Write(o.Bytes())
				continue
			}
			if err := writeTangled(o, *force); err != nil {
				fmt.Fprintln(os.Stderr, "litgo:", err)
				status = 1
				continue
			}
			fmt.Fprintf(os.Stderr, "litgo: %s → %s (%d lines)\n", relPath(doc.Path), relPath(o.Path), len(o.Lines))
		}
	}
	return status
}

func cmdRun(args []string) int {
	fs := flag.NewFlagSet("run", flag.ExitOnError)
	o := runOptions{}
	fs.BoolVar(&o.json, "json", false, "emit one JSON event per line")
	fs.BoolVar(&o.force, "force", false, "overwrite files litgo did not generate")
	fs.BoolVar(&o.vet, "vet", false, "also run go vet")
	fs.BoolVar(&o.noProve, "no-prove", false, "run even if the //@ annotations are not proved")
	fs.DurationVar(&o.timeout, "timeout", 0, "kill the program after this long")
	fs.Parse(args)
	if fs.NArg() == 0 {
		fmt.Fprintln(os.Stderr, "litgo run: no input file")
		return 2
	}
	o.args = fs.Args()[1:]
	if len(o.args) > 0 && o.args[0] == "--" {
		o.args = o.args[1:]
	}
	return runFile(fs.Arg(0), o)
}

func cmdWeave(args []string) int {
	fs := flag.NewFlagSet("weave", flag.ExitOnError)
	to := fs.String("to", "", "pdf, html, typ (Typst source) or md (woven Markdown); default pdf, or what -o ends in")
	out := fs.String("o", "", "output file")
	fs.Parse(args)
	if fs.NArg() != 1 {
		fmt.Fprintln(os.Stderr, "litgo weave: expected one input file")
		return 2
	}
	doc, err := load(fs.Arg(0))
	if err != nil {
		fmt.Fprintln(os.Stderr, "litgo:", err)
		return 1
	}
	format := *to
	if format == "" {
		format = strings.TrimPrefix(filepath.Ext(*out), ".")
	}
	if format == "" {
		format = "pdf"
	}
	if *out == "" {
		ext := map[string]string{"md": "woven.md"}[format]
		if ext == "" {
			ext = format
		}
		*out = strings.TrimSuffix(strings.TrimSuffix(doc.Path, ".md"), ".lit") + "." + ext
	}
	switch format {
	case "pdf":
		err = weave.PDF(doc, *out)
	case "html":
		err = weave.HTML(doc, *out)
	case "typ":
		var src string
		if src, err = weave.Typst(doc); err == nil {
			err = os.WriteFile(*out, []byte(src), 0o644)
		}
	case "md":
		err = os.WriteFile(*out, []byte(weave.Markdown(doc)), 0o644)
	default:
		err = fmt.Errorf("cannot weave to %q: pdf, html, typ and md are what there is", format)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "litgo:", err)
		return 1
	}
	abs, _ := filepath.Abs(*out)
	fmt.Println(abs)
	return 0
}

func cmdCheck(args []string) int {
	status, cache := 0, &check.Cache{}
	for _, path := range args {
		doc, err := load(path)
		if err != nil {
			fmt.Fprintln(os.Stderr, "litgo:", err)
			status = 1
			continue
		}
		res := doc.Tangle()
		diags := append(res.Diags, res.SyntaxCheck()...)
		if len(diags) == len(res.Diags) {
			diags = append(diags, check.Types(res, cache)...)
		}
		if len(diags) == len(res.Diags) {
			proofs, _ := vego.Prove(res)
			diags = append(diags, proofs...)
		}
		if report(diags) > 0 {
			status = 1
		}
	}
	return status
}

func cmdProve(args []string) int {
	fs := flag.NewFlagSet("prove", flag.ExitOnError)
	asJSON := fs.Bool("json", false, "print the findings and the count as JSON")
	fs.Parse(args)
	if fs.NArg() == 0 {
		fmt.Fprintln(os.Stderr, "litgo prove: no input files")
		return 2
	}
	status := 0
	for _, path := range fs.Args() {
		doc, err := load(path)
		if err != nil {
			fmt.Fprintln(os.Stderr, "litgo:", err)
			status = 1
			continue
		}
		res := doc.Tangle()
		diags := append(res.Diags, res.SyntaxCheck()...)
		var sum vego.Summary
		if len(diags) == len(res.Diags) && !res.HasErrors() {
			var proofs []lit.Diag
			proofs, sum = vego.Prove(res)
			diags = append(diags, proofs...)
		}
		failed := false
		for _, d := range diags {
			failed = failed || d.Severity == lit.SevError
		}
		if failed {
			status = 1
		}
		if *asJSON {
			if diags == nil {
				diags = []lit.Diag{}
			}
			printJSON(map[string]any{"file": doc.Path, "diagnostics": diags, "functions": sum.Functions,
				"proved": sum.Proved, "obligations": sum.Obligations, "names": sum.Names})
			continue
		}
		report(diags)
		switch {
		case failed && sum.Functions == 0:
		case sum.Functions == 0:
			fmt.Fprintf(os.Stderr, "litgo: %s has no //@ annotations, so there is nothing to prove\n", relPath(doc.Path))
		default:
			fmt.Fprintf(os.Stderr, "litgo: %s: proved %d of %d annotated functions (%d obligations)\n",
				relPath(doc.Path), sum.Proved, sum.Functions, sum.Obligations)
			for _, name := range sum.Names {
				fmt.Fprintf(os.Stderr, "  ✓ %s\n", name)
			}
		}
	}
	return status
}

// cmdCat prints the document the way the editor shows it: math as Unicode,
// diagrams drawn, chunk syntax prettified.
func cmdCat(args []string) int {
	if len(args) != 1 {
		fmt.Fprintln(os.Stderr, "litgo cat: expected one input file")
		return 2
	}
	doc, err := load(args[0])
	if err != nil {
		fmt.Fprintln(os.Stderr, "litgo:", err)
		return 1
	}
	a := doc.Analyze(lit.AnalyzeOptions{})
	blocks := map[int]lit.Item{}
	inline := map[int][]lit.Item{}
	for _, it := range a.Items {
		if it.Kind == "table" || it.Kind == "vego" {
			continue // lining up a table and colouring an annotation are the editor's business
		} else if len(it.Lines) > 0 {
			blocks[it.Line] = it
		} else {
			inline[it.Line] = append(inline[it.Line], it)
		}
	}
	for i := 0; i < len(doc.Lines); i++ {
		if it, ok := blocks[i]; ok {
			for _, l := range it.Lines {
				fmt.Println("    " + l)
			}
			i = it.EndLine
			continue
		}
		line := doc.Lines[i]
		items := inline[i]
		sort.Slice(items, func(a, b int) bool { return items[a].Col < items[b].Col })
		for k := len(items) - 1; k >= 0; k-- { // right to left keeps columns valid
			it := items[k]
			line = line[:it.Col] + it.Text + line[min(it.EndCol, len(line)):]
		}
		fmt.Println(line)
	}
	return 0
}

func cmdFmt(args []string) int {
	fs := flag.NewFlagSet("fmt", flag.ExitOnError)
	write := fs.Bool("w", false, "write the result back instead of printing it")
	fs.Parse(args)
	if fs.NArg() != 1 {
		fmt.Fprintln(os.Stderr, "litgo fmt: expected one input file")
		return 2
	}
	doc, err := load(fs.Arg(0))
	if err != nil {
		fmt.Fprintln(os.Stderr, "litgo:", err)
		return 1
	}
	lines := append([]string{}, doc.Lines...)
	for i := len(doc.Blocks) - 1; i >= 0; i-- {
		b := doc.Blocks[i]
		if !b.Tangled() || b.Lang != "go" || b.Last() < b.First() || b.Strip > 0 {
			continue
		}
		// format.Source accepts fragments; blocks that only make sense once
		// their chunks are spliced in fail to parse and are left alone. So are
		// blocks with inline references: gofmt would tidy away the comma that
		// precedes a reference standing for the rest of an argument list.
		if !b.Verbatim && inlineRefs(doc.Lines[b.First():b.Last()+1]) {
			continue
		}
		src := strings.Join(doc.Lines[b.First():b.Last()+1], "\n") + "\n"
		out, err := format.Source([]byte(src))
		if err != nil {
			continue
		}
		formatted := strings.Split(strings.TrimRight(string(out), "\n"), "\n")
		lines = append(append(append([]string{}, lines[:b.First()]...), formatted...), lines[b.Last()+1:]...)
	}
	text := strings.Join(lines, "\n") + "\n"
	if *write {
		if err := os.WriteFile(doc.Path, []byte(text), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "litgo:", err)
			return 1
		}
		return 0
	}
	fmt.Print(text)
	return 0
}

func inlineRefs(lines []string) bool {
	for i, l := range lines {
		for _, r := range lit.RefsIn(l, i) {
			if r.Inline {
				return true
			}
		}
	}
	return false
}

func cmdAnalyze(args []string) int {
	fs := flag.NewFlagSet("analyze", flag.ExitOnError)
	path := fs.String("path", "", "the document's file name")
	upright := fs.Bool("upright", false, "do not italicise math letters")
	fs.Parse(args)
	return printJSON(stdinDoc(*path).Analyze(lit.AnalyzeOptions{Upright: *upright}))
}

func cmdUntangle(args []string) int {
	fs := flag.NewFlagSet("untangle", flag.ExitOnError)
	path := fs.String("path", "", "the document's file name")
	start := fs.Int("start", -1, "first selected line")
	end := fs.Int("end", -1, "last selected line")
	startCol := fs.Int("start-col", 0, "first selected byte (charwise)")
	endCol := fs.Int("end-col", -1, "byte after the selection (charwise)")
	name := fs.String("name", "", "chunk name; suggested when empty")
	fs.Parse(args)
	res, err := stdinDoc(*path).Untangle(lit.Selection{StartLine: *start, EndLine: *end, StartCol: *startCol, EndCol: *endCol}, *name)
	if err != nil {
		return jsonError(err)
	}
	return printJSON(res)
}

func cmdVersion(args []string) int {
  fmt.Printf("%s\n", VERSION)
  return 0
}

func cmdRename(args []string) int {
	fs := flag.NewFlagSet("rename", flag.ExitOnError)
	path := fs.String("path", "", "the document's file name")
	from := fs.String("from", "", "current chunk name")
	to := fs.String("to", "", "new chunk name")
	fs.Parse(args)
	edits, err := stdinDoc(*path).Rename(*from, *to)
	if err != nil {
		return jsonError(err)
	}
	return printJSON(map[string]any{"edits": edits, "name": lit.NormName(*to)})
}
