// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

//go:build !unix

package main

import "os/exec"

func ownGroup(cmd *exec.Cmd) {}

func killGroup(cmd *exec.Cmd) {
	if cmd.Process != nil {
		cmd.Process.Kill()
	}
}

func killOnSignal(cmd *exec.Cmd) func() { return func() {} }
