// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package lsp

import (
	"bufio"
	"encoding/json"
	"fmt"
	"go/parser"
	"go/token"
	"io"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/tlehman/litgo/internal/lit"
)

// findGopls locates the gopls to run: the one named, or the one that can be
// found. "off" means none.
func findGopls(named string) string {
	if named == "off" {
		return ""
	}
	if named != "" {
		p, _ := exec.LookPath(named)
		return p
	}
	if p, err := exec.LookPath("gopls"); err == nil {
		return p
	}
	gopath := os.Getenv("GOPATH")
	if home, err := os.UserHomeDir(); gopath == "" && err == nil {
		gopath = filepath.Join(home, "go")
	}
	for _, dir := range []string{os.Getenv("GOBIN"), filepath.Join(gopath, "bin")} {
		if p, err := exec.LookPath(filepath.Join(dir, "gopls")); dir != "" && err == nil {
			return p
		}
	}
	return ""
}

// gopls is the Go language server, run as a child process. Like the rest of
// the server's state, it belongs to the loop in Serve.
type gopls struct {
	cmd     *exec.Cmd
	in      io.WriteCloser
	out     chan []byte   // to the goroutine that writes to gopls
	msgs    chan *message // from the goroutine that reads from it
	next    int
	pending map[int]call
	ids     map[string]int // the editor's id for a request in flight → ours
	dead    bool
	caps    map[string]any // what gopls said it can do
}

// call is a request in flight. done gets the answer, or nil if gopls died.
type call struct {
	done   func(*message)
	editor string
}

func (g *gopls) write(m *message) { g.out <- frame(m) }

func (g *gopls) notify(method string, params any) {
	raw, _ := json.Marshal(params)
	g.write(&message{Method: method, Params: raw})
}

// request asks gopls something on behalf of the editor's request id (nil if
// the question is litgo's own).
func (g *gopls) request(id *json.RawMessage, method string, params any, done func(*message)) {
	if g.dead {
		done(nil)
		return
	}
	raw, _ := json.Marshal(params)
	c := call{done: done}
	g.next++
	if id != nil {
		c.editor = string(*id)
		g.ids[c.editor] = g.next
	}
	g.pending[g.next] = c
	ours := json.RawMessage(strconv.Itoa(g.next))
	g.write(&message{ID: &ours, Method: method, Params: raw})
}

// cancel passes on the editor's loss of interest in one of its requests.
func (g *gopls) cancel(params json.RawMessage) {
	var p struct {
		ID json.RawMessage `json:"id"`
	}
	json.Unmarshal(params, &p)
	if n, ok := g.ids[string(p.ID)]; ok {
		g.notify("$/cancelRequest", map[string]any{"id": n})
	}
}

// listen reads what gopls sends until it hangs up or the server stops.
func (g *gopls) listen(out io.Reader, quit <-chan struct{}) {
	defer close(g.msgs)
	defer g.cmd.Wait()
	r := bufio.NewReader(out)
	for {
		m, err := read(r)
		if err != nil {
			return
		}
		if m.ID == nil && m.Method != "window/showMessage" {
			continue
		}
		select {
		case g.msgs <- m:
		case <-quit:
			return
		}
	}
}

// heard is where messages from gopls arrive. Without a gopls it is nil, and
// a nil channel never delivers anything.
func (s *server) heard() <-chan *message {
	if s.gopls == nil || s.gopls.dead {
		return nil
	}
	return s.gopls.msgs
}

// hear handles one message from gopls.
func (g *gopls) hear(m *message, s *server) {
	switch {
	case m.Method == "" && m.ID != nil:
		n, _ := strconv.Atoi(string(*m.ID))
		c, ok := g.pending[n]
		delete(g.pending, n)
		delete(g.ids, c.editor)
		if ok {
			c.done(m)
		}
	case m.ID != nil:
		g.write(&message{ID: m.ID, Result: json.RawMessage("null")})
	case m.Method == "window/showMessage":
		var p struct {
			Type int `json:"type"`
		}
		if json.Unmarshal(m.Params, &p); p.Type == 1 {
			s.write(&message{Method: m.Method, Params: m.Params})
		}
	}
}

// hangUp is what happens when gopls is gone: nobody gets an answer any more.
func (g *gopls) hangUp() {
	g.dead = true
	orphans := g.pending
	g.pending = map[int]call{}
	for _, c := range orphans {
		c.done(nil)
	}
}

// start runs gopls and introduces litgo to it the way the editor introduced
// itself to litgo. On any failure s.gopls stays nil.
func (s *server) start(initialize json.RawMessage) {
	bin := findGopls(s.goplsBin)
	if bin == "" {
		return
	}
	cmd := exec.Command(bin)
	in, _ := cmd.StdinPipe()
	out, _ := cmd.StdoutPipe()
	if cmd.Start() != nil {
		return
	}
	g := &gopls{cmd: cmd, in: in, msgs: make(chan *message), pending: map[int]call{}, ids: map[string]int{}}
	g.out, _ = writer(in)
	go g.listen(out, s.quit)

	var p map[string]any
	if json.Unmarshal(initialize, &p); p == nil {
		p = map[string]any{}
	}
	theirs, _ := p["capabilities"].(map[string]any)
	p["capabilities"] = map[string]any{"textDocument": theirs["textDocument"]}
	var reply *message
	answered := false
	g.request(nil, "initialize", p, func(m *message) { reply, answered = m, true })
	timeout := time.After(30 * time.Second)
	for !answered {
		select {
		case m, ok := <-g.msgs:
			if ok {
				g.hear(m, s)
			} else {
				g.hangUp() // which answers the request, with nil
			}
		case <-timeout:
			answered = true
		}
	}
	if result, _ := reply.result().(map[string]any); result != nil {
		g.caps, _ = result["capabilities"].(map[string]any)
		g.notify("initialized", map[string]any{})
		s.gopls = g
		return
	}
	g.kill()
}

// kill stops gopls, and the goroutine that writes to it.
func (g *gopls) kill() {
	close(g.out)
	g.in.Close()
	g.cmd.Process.Kill()
}

// result is the result of a successful answer, and nil otherwise.
func (m *message) result() any {
	if m == nil || m.Error != nil {
		return nil
	}
	return m.Result
}

func (s *server) stop() {
	if g := s.gopls; g != nil {
		g.kill()
	}
}

// overlay is a tangled file as gopls was last shown it.
type overlay struct {
	owner   string // URI of the document it is tangled from
	version int
	text    string
}

// sync tangles a document, unless that has been done for this version of
// its text, and shows gopls the result. It returns a nil result for a
// document that is not open.
func (s *server) sync(uri string) (*lit.Result, int) {
	d := s.docs[uri]
	if d == nil {
		return nil, -1
	}
	if d.res == nil || d.tangled != d.version {
		d.res, d.tangled = lit.Parse(path(uri), []byte(d.text)).Tangle(), d.version
		s.overlay(uri, d.res)
	}
	return d.res, d.version
}

// forget closes what a closed document tangled to.
func (s *server) forget(uri string) {
	s.overlay(uri, nil)
}

// overlay brings gopls up to date with what a document tangles to: new
// files are opened, changed ones changed, and ones no longer written closed.
func (s *server) overlay(uri string, res *lit.Result) {
	g := s.gopls
	if g == nil {
		return
	}
	live := map[string]bool{}
	for _, o := range outputs(res) {
		live[o.Path] = true
		text := string(o.Bytes())
		ov := s.overlays[o.Path]
		switch {
		case ov == nil:
			s.overlays[o.Path] = &overlay{owner: uri, version: 1, text: text}
			g.notify("textDocument/didOpen", map[string]any{
				"textDocument": map[string]any{"uri": fileURI(o.Path), "languageId": "go", "version": 1, "text": text}})
		case ov.text != text:
			ov.owner, ov.text, ov.version = uri, text, ov.version+1
			g.notify("textDocument/didChange", map[string]any{
				"textDocument":   map[string]any{"uri": fileURI(o.Path), "version": ov.version},
				"contentChanges": []any{map[string]any{"text": text}}})
		}
	}
	for p, ov := range s.overlays {
		if ov.owner == uri && !live[p] {
			delete(s.overlays, p)
			g.notify("textDocument/didClose", map[string]any{
				"textDocument": map[string]any{"uri": fileURI(p)}})
		}
	}
}

// outputs lists the Go files of a result, which may be nil.
func outputs(res *lit.Result) []*lit.Output {
	var out []*lit.Output
	if res != nil {
		for _, o := range res.Files {
			if o.File.Lang == "go" {
				out = append(out, o)
			}
		}
	}
	return out
}

func fileURI(path string) string {
	return (&url.URL{Scheme: "file", Path: filepath.ToSlash(path)}).String()
}

func (s *server) output(uri string, asked *lit.Result) (o *lit.Output, doc *lit.Doc, owner string) {
	p := filepath.Clean(path(uri))
	res := asked
	if ov := s.overlays[p]; ov != nil {
		owner = ov.owner
		if d := s.docs[owner]; d != nil && (asked == nil || asked.Doc.Path != path(owner)) {
			res = d.res
		}
	}
	if owner != "" {
		for _, o := range outputs(res) {
			if filepath.Clean(o.Path) == p {
				return o, res.Doc, owner
			}
		}
	}
	return nil, nil, ""
}

var positional = map[string]string{
	"textDocument/hover":             "hoverProvider",
	"textDocument/definition":        "definitionProvider",
	"textDocument/typeDefinition":    "typeDefinitionProvider",
	"textDocument/implementation":    "implementationProvider",
	"textDocument/references":        "referencesProvider",
	"textDocument/documentHighlight": "documentHighlightProvider",
	"textDocument/completion":        "completionProvider",
	"textDocument/signatureHelp":     "signatureHelpProvider",
	"textDocument/prepareRename":     "renameProvider",
	"textDocument/rename":            "renameProvider",
}

func (s *server) capabilities() map[string]any {
	c := map[string]any{}
	if s.gopls != nil {
		for _, name := range positional {
			if v, ok := s.gopls.caps[name]; ok {
				c[name] = v
			}
		}
		c["workspaceSymbolProvider"] = s.gopls.caps["workspaceSymbolProvider"]
	}
	c["hoverProvider"], c["definitionProvider"], c["referencesProvider"] = true, true, true
	c["renameProvider"] = map[string]any{"prepareProvider": true}
	return c
}

// proxy handles the requests that gopls has a say in, and reports whether
// the message was one.
func (s *server) proxy(m *message) bool {
	switch {
	case positional[m.Method] != "" && m.ID != nil:
		s.ask(m)
	case m.Method == "$/cancelRequest":
		if s.gopls != nil {
			s.gopls.cancel(m.Params)
		}
	case m.Method == "workspace/symbol" && m.ID != nil && s.gopls != nil:
		// No position to translate on the way in, but the symbols found
		// may well be in tangled files.
		var params any
		json.Unmarshal(m.Params, &params)
		s.gopls.request(m.ID, m.Method, params, func(reply *message) {
			s.relay(m, reply, &translation{s: s})
		})
	default:
		return false
	}
	return true
}

// position is the protocol's: a line, and a column in the agreed units.
type position struct {
	Line      int `json:"line"`
	Character int `json:"character"`
}

func (s *server) ask(m *message) {
	var p struct {
		TextDocument struct {
			URI string `json:"uri"`
		} `json:"textDocument"`
		Position position `json:"position"`
		NewName  string   `json:"newName"`
	}
	json.Unmarshal(m.Params, &p)
	uri := p.TextDocument.URI
	res, _ := s.sync(uri)
	if res == nil || p.Position.Line < 0 || p.Position.Line >= len(res.Doc.Lines) {
		s.respond(m, nil)
		return
	}
	line := p.Position.Line
	col := offset(s.utf8, res.Doc.Lines[line], p.Position.Character)
	if mention := res.Doc.MentionAt(line, col); mention != nil {
		result, err := s.mention(m.Method, uri, res.Doc, mention, p.NewName)
		if err != nil {
			s.write(&message{ID: m.ID, Error: &rpcError{requestFailed, err.Error()}})
		} else {
			s.respond(m, result)
		}
		return
	}
	o, outLine, outCol, ok := res.Locate(line, col)
	if !ok || o.File.Lang != "go" || s.gopls == nil {
		s.respond(m, nil)
		return
	}
	var params map[string]any
	json.Unmarshal(m.Params, &params)
	params["textDocument"] = map[string]any{"uri": fileURI(o.Path)}
	params["position"] = position{outLine, units(false, o.Lines[outLine].Text, outCol)}
	s.gopls.request(m.ID, m.Method, params, func(reply *message) {
		s.relay(m, reply, &translation{s: s, res: res, out: o, uri: uri})
	})
}

// respond answers a request; a nil result is the protocol's null.
func (s *server) respond(to *message, result any) {
	if result == nil {
		result = json.RawMessage("null")
	}
	s.write(&message{ID: to.ID, Result: result})
}

// offset converts a column in UTF-16 code units (or in bytes) to a byte
// offset in the line: the inverse of units.
func offset(utf8 bool, line string, n int) int {
	if utf8 {
		return min(max(n, 0), len(line))
	}
	for i, r := range line {
		if n <= 0 {
			return i
		}
		n--
		if r >= 0x10000 {
			n--
		}
	}
	return len(line)
}

const requestFailed = -32803

func (s *server) mention(method, uri string, doc *lit.Doc, m *lit.Mention, newName string) (any, error) {
	span := func(line, col, end int) map[string]any {
		line = min(line, len(doc.Lines)-1)
		text := doc.Lines[line]
		return map[string]any{"start": position{line, s.column(text, col)}, "end": position{line, s.column(text, end)}}
	}
	c := m.Chunk
	var uses, blocks []any
	for _, r := range c.Refs {
		uses = append(uses, map[string]any{"uri": uri, "range": span(r.Line, r.Col, r.EndCol)})
	}
	for _, b := range c.Blocks {
		blocks = append(blocks, map[string]any{"uri": uri, "range": span(b.First(), 0, 0)})
	}
	switch method {
	case "textDocument/definition":
		if m.Ref {
			return blocks, nil
		}
		return uses, nil
	case "textDocument/references":
		return uses, nil
	case "textDocument/hover":
		if !m.Ref || len(c.Blocks) == 0 {
			return nil, nil
		}
		text := "⟨" + c.Name + "⟩ ≡\n"
		for _, b := range c.Blocks {
			text += "```" + b.Lang + "\n" + strings.Join(doc.Lines[b.First():b.Last()+1], "\n") + "\n```\n"
		}
		return map[string]any{"contents": map[string]any{"kind": "markdown", "value": text}, "range": span(m.Line, m.Col, m.EndCol)}, nil
	case "textDocument/prepareRename":
		return map[string]any{"range": span(m.Line, m.Col, m.EndCol), "placeholder": c.Name}, nil
	case "textDocument/rename":
		edits, err := doc.Rename(c.Name, newName)
		if err != nil {
			return nil, err
		}
		var changes []any
		for _, e := range edits { // Rename replaces lines one for one
			changes = append(changes, map[string]any{"range": span(e.Start, 0, len(doc.Lines[e.Start])), "newText": e.Lines[0]})
		}
		return map[string]any{"changes": map[string]any{uri: changes}}, nil
	}
	return nil, nil
}

// translation brings the answer to one question back to the document.
type translation struct {
	s   *server
	res *lit.Result // the tangling gopls was asked about,
	out *lit.Output // the file in it that the question was about,
	uri string      // and the document
}

func (t *translation) value(v any) any {
	switch v := v.(type) {
	case []any:
		if len(v) > 0 && t.out != nil && isEdit(asMap(v[0])) {
			return t.edits(t.out, t.res.Doc, v)
		}
		out, seen := []any{}, map[string]bool{}
		for _, e := range v {
			if e = t.value(e); e == nil {
				continue
			}
			if key := positioned(e); key == "" || !seen[key] {
				out = append(out, e)
				seen[key] = true
			}
		}
		return out
	case map[string]any:
		return t.object(v)
	}
	return v
}

func (t *translation) object(v map[string]any) any {
	if uri, ok := v["uri"].(string); ok && v["range"] != nil {
		if o, doc, owner := t.s.output(uri, t.res); o != nil {
			if v["range"], ok = t.span(o, doc, v["range"], false); !ok {
				return nil
			}
			v["uri"] = owner
		}
		return v
	}
	if uri, ok := v["targetUri"].(string); ok {
		if t.out != nil && v["originSelectionRange"] != nil {
			v["originSelectionRange"], _ = t.span(t.out, t.res.Doc, v["originSelectionRange"], false)
		}
		if o, doc, owner := t.s.output(uri, t.res); o != nil {
			for _, k := range []string{"targetRange", "targetSelectionRange"} {
				if v[k], ok = t.span(o, doc, v[k], false); !ok {
					return nil
				}
			}
			v["targetUri"] = owner
		}
		return v
	}
	if t.out != nil && isEdit(v) { // on its own, as the textEdit of a completion
		if t.edit(t.out, t.res.Doc, v) {
			return v
		}
		return nil
	}
	if t.out != nil && isRange(v) {
		r, _ := t.span(t.out, t.res.Doc, v, false)
		return r
	}
	for k, e := range v {
		if e = t.value(e); e == nil {
			delete(v, k) // in the protocol, null and absent are the same
		} else {
			v[k] = e
		}
	}
	return v
}

func isRange(v map[string]any) bool {
	_, start := v["start"].(map[string]any)
	_, end := v["end"].(map[string]any)
	return start && end
}

func isEdit(v map[string]any) bool {
	_, ok := v["newText"].(string)
	return ok
}

func asMap(v any) map[string]any {
	m, _ := v.(map[string]any)
	return m
}

func asList(v any) []any {
	l, _ := v.([]any)
	return l
}

// positioned gives a location, a highlight or an edit a key to be compared
// by, and anything else none.
func positioned(v any) string {
	if m, ok := v.(map[string]any); ok && (m["range"] != nil || m["targetUri"] != nil) {
		b, _ := json.Marshal(m)
		return string(b)
	}
	return ""
}

// span translates a range in a tangled file to the document it came from.
func (t *translation) span(o *lit.Output, doc *lit.Doc, v any, edit bool) (any, bool) {
	r, _ := v.(map[string]any)
	l1, c1, ok1 := outPosition(o, r["start"])
	l2, c2, ok2 := outPosition(o, r["end"])
	if !ok1 || !ok2 && edit {
		return v, false
	}
	if !ok2 {
		l2, c2 = l1, c1
	}
	sl, sc, ok1 := o.Exact(l1, c1, false)
	el, ec, ok2 := o.Exact(l2, c2, l1 != l2 || c1 != c2)
	if edit && !(ok1 && ok2 && el-sl == l2-l1 && (l1 != l2 || ec-sc == c2-c1)) {
		return v, false
	}
	if !ok1 {
		if sl, sc, _, ok1 = o.Map(l1, c1); !ok1 {
			return v, false
		}
	}
	if !ok2 {
		el, ec, _, ok2 = o.Map(l2, c2)
	}
	if !ok2 || el < sl || el == sl && ec < sc {
		el, ec = sl, sc
	}
	return map[string]any{
		"start": position{sl, units(t.s.utf8, doc.Lines[sl], sc)},
		"end":   position{el, units(t.s.utf8, doc.Lines[el], ec)},
	}, true
}

// outPosition decodes a position in a tangled file, in bytes.
func outPosition(o *lit.Output, v any) (line, col int, ok bool) {
	p, _ := v.(map[string]any)
	l, ok1 := p["line"].(float64)
	c, ok2 := p["character"].(float64)
	if !ok1 || !ok2 || l < 0 || int(l) >= len(o.Lines) {
		return 0, 0, false
	}
	return int(l), offset(false, o.Lines[int(l)].Text, int(c)), true
}

// edit translates a text edit in place, if it has a place in the document.
func (t *translation) edit(o *lit.Output, doc *lit.Doc, v map[string]any) bool {
	ok := true
	for _, k := range []string{"range", "insert", "replace"} { // a completion may offer both an insertion and a replacement
		if r, has := v[k]; has && ok {
			if l, _, _ := outPosition(o, asMap(r)["start"]); l < o.Header {
				return false
			}
			v[k], ok = t.span(o, doc, r, true)
		}
	}
	return ok
}

// edits translates a list of text edits. Those to the generated header
// become edits to the imports directive.
func (t *translation) edits(o *lit.Output, doc *lit.Doc, list []any) []any {
	out, header := []any{}, []map[string]any{}
	for _, e := range list {
		m := asMap(e)
		if l, _, ok := outPosition(o, asMap(m["range"])["start"]); ok && l < o.Header {
			header = append(header, m)
		} else if t.edit(o, doc, m) {
			out = append(out, m)
		}
	}
	if len(header) == 0 {
		return out
	}
	text := string(o.Bytes())
	starts := []int{0}
	for _, l := range o.Lines {
		starts = append(starts, starts[len(starts)-1]+len(l.Text)+1)
	}
	at := func(v any) int {
		l, c, ok := outPosition(o, v)
		if !ok {
			return -1
		}
		return starts[l] + c
	}
	sort.SliceStable(header, func(i, j int) bool {
		return at(asMap(header[i]["range"])["start"]) > at(asMap(header[j]["range"])["start"])
	})
	for _, m := range header {
		r := asMap(m["range"])
		if from, to := at(r["start"]), at(r["end"]); from >= 0 && to >= from {
			text = text[:from] + m["newText"].(string) + text[to:]
		}
	}
	file, _ := parser.ParseFile(token.NewFileSet(), "", text, parser.ImportsOnly)
	if file == nil {
		return out
	}
	for _, spec := range file.Imports {
		alias, path := "", strings.Trim(spec.Path.Value, "\"`")
		if spec.Name != nil {
			alias = spec.Name.Name
		}
		known := false
		for _, imp := range o.File.Imports {
			known = known || imp.Path == path
		}
		if line, col, entry, ok := doc.AddImport(o.File, alias, path); ok && !known {
			at := position{line, units(t.s.utf8, doc.Lines[min(line, len(doc.Lines)-1)], col)}
			out = append(out, map[string]any{"range": map[string]any{"start": at, "end": at}, "newText": entry})
		}
	}
	return out
}

// workspaceEdit translates the answer to a rename.
func (t *translation) workspaceEdit(v any) (any, error) {
	w, _ := v.(map[string]any)
	if w == nil {
		return nil, nil
	}
	changes := map[string][]any{}
	seen := map[string]bool{}
	add := func(uri string, edits []any) error {
		o, doc, owner := t.s.output(uri, t.res)
		if o == nil {
			if b, err := os.ReadFile(path(uri)); err == nil && lit.Generated(b) {
				return fmt.Errorf("%s is tangled from a document that is not open: open it, and rename there", filepath.Base(path(uri)))
			}
			changes[uri] = append(changes[uri], edits...)
			return nil
		}
		for _, e := range edits {
			m := asMap(e)
			at, _ := json.Marshal(m["range"])
			if !t.edit(o, doc, m) {
				return fmt.Errorf("this would change text that litgo generates, in %s at %s", filepath.Base(o.Path), at)
			}
			if key := positioned(m); !seen[owner+key] {
				seen[owner+key] = true
				changes[owner] = append(changes[owner], m)
			}
		}
		return nil
	}
	for uri, edits := range asMap(w["changes"]) {
		if err := add(uri, asList(edits)); err != nil {
			return nil, err
		}
	}
	for _, c := range asList(w["documentChanges"]) {
		change := asMap(c)
		if change["kind"] != nil {
			return nil, fmt.Errorf("this would %s a file, which a document's file directives decide", change["kind"])
		}
		uri, _ := asMap(change["textDocument"])["uri"].(string)
		if err := add(uri, asList(change["edits"])); err != nil {
			return nil, err
		}
	}
	return map[string]any{"changes": changes}, nil
}

// relay passes gopls's answer to a request on to the editor.
func (s *server) relay(to *message, reply *message, t *translation) {
	switch {
	case reply != nil && reply.Error != nil:
		s.write(&message{ID: to.ID, Error: reply.Error})
	case to.Method == "textDocument/rename":
		edit, err := t.workspaceEdit(reply.result())
		if err != nil {
			s.write(&message{ID: to.ID, Error: &rpcError{requestFailed, err.Error()}})
			return
		}
		s.respond(to, edit)
	default:
		s.respond(to, t.value(reply.result()))
	}
}
