// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package lsp

import (
	"encoding/json"
	"fmt"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"
)

const greeter = "<!-- package: main -->\n<!-- imports: fmt -->\n\n```go\nfunc greet(whom string) string {\n\treturn \"hello, \" + whom\n}\n\nfunc main() {\n\t// <<say it>>\n}\n```\n\n<!-- chunk: say it -->\n```go\nfmt.Println(\"𝄞\", greet(\"world\"))\n```\n"

// ask sends a request about a position and returns the result as JSON.
func (c *client) ask(id int, method, uri string, line, character int, more map[string]any) string {
	params := map[string]any{"textDocument": map[string]any{"uri": uri}, "position": map[string]any{"line": line, "character": character}}
	for k, v := range more {
		params[k] = v
	}
	c.send("textDocument/"+method, id, params)
	return c.result(id)
}

// result waits for the answer to a request.
func (c *client) result(id int) string {
	for {
		if m := c.next(); m.ID != nil && string(*m.ID) == strconv.Itoa(id) {
			if m.Error != nil {
				return "error: " + m.Error.Message
			}
			var sb strings.Builder
			enc := json.NewEncoder(&sb)
			enc.SetEscapeHTML(false)
			enc.Encode(m.Result)
			return strings.TrimSpace(sb.String())
		}
	}
}

// start spells the start of a range the way encoding/json does: keys sorted.
func start(line, character int) string {
	return fmt.Sprintf(`"start":{"character":%d,"line":%d}`, character, line)
}

func TestGoplsThroughTheDocument(t *testing.T) {
	if findGopls("") == "" {
		t.Skip("no gopls")
	}
	dir := t.TempDir()
	os.WriteFile(dir+"/go.mod", []byte("module example.com/greeter\n\ngo 1.22\n"), 0o644)
	uri := "file://" + dir + "/greeter.lit.md"
	c := connect(t, "")
	c.send("initialize", 1, map[string]any{"rootUri": "file://" + dir, "capabilities": map[string]any{
		"general": map[string]any{"positionEncodings": []string{"utf-8", "utf-16"}}}})
	if got := c.result(1); !strings.Contains(got, "completionProvider") || !strings.Contains(got, `"utf-16"`) {
		t.Fatalf("with gopls behind it the server completes, and counts as gopls does: %s", got)
	}
	c.send("initialized", 0, `{}`)
	c.send("textDocument/didOpen", 0, map[string]any{"textDocument": map[string]any{"uri": uri, "version": 1, "text": greeter}})

	// Println, in the chunk. gopls may still be loading the first time.
	hover := ""
	for i := 0; i < 50 && !strings.Contains(hover, "func fmt.Println"); i++ {
		if hover = c.ask(10+i, "hover", uri, 15, 5, nil); hover == "null" {
			time.Sleep(200 * time.Millisecond)
		}
	}
	if !strings.Contains(hover, "func fmt.Println") || !strings.Contains(hover, start(15, 4)) {
		t.Errorf("hover in a chunk: %s", hover)
	}
	// greet, after the clef: from the chunk to the block that defines it.
	if got := c.ask(2, "definition", uri, 15, 19, nil); !strings.Contains(got, uri) || !strings.Contains(got, start(4, 5)) {
		t.Errorf("definition across blocks: %s", got)
	}
	if got := c.ask(3, "references", uri, 4, 6, map[string]any{"context": map[string]any{"includeDeclaration": true}}); strings.Count(got, uri) != 2 || !strings.Contains(got, start(15, 18)) {
		t.Errorf("references, in UTF-16 units: %s", got)
	}
	if got := c.ask(4, "rename", uri, 4, 6, map[string]any{"newName": "hail"}); strings.Count(got, `"newText":"hail"`) != 2 ||
		!strings.Contains(got, start(15, 18)) || strings.Contains(got, "greeter.go") {
		t.Errorf("rename edits the document, not the tangled file: %s", got)
	}
	if got := c.ask(5, "hover", uri, 0, 3, nil); got != "null" {
		t.Errorf("prose is not Go: %s", got)
	}

	// The chunk reference is litgo's own business.
	if got := c.ask(6, "definition", uri, 9, 6, nil); !strings.Contains(got, start(15, 0)) {
		t.Errorf("a reference is defined by its chunk: %s", got)
	}
	if got := c.ask(7, "hover", uri, 9, 6, nil); !strings.Contains(got, "⟨say it⟩") || !strings.Contains(got, "greet(") {
		t.Errorf("hovering over a reference shows the chunk: %s", got)
	}
	if got := c.ask(8, "rename", uri, 13, 14, map[string]any{"newName": "speak"}); !strings.Contains(got, "<!-- chunk: speak -->") || !strings.Contains(got, "// <<speak>>") {
		t.Errorf("renaming a chunk: %s", got)
	}

	// Completing from a package that is not imported adds it to the directive.
	c.send("textDocument/didChange", 0, map[string]any{
		"textDocument":   map[string]any{"uri": uri, "version": 2},
		"contentChanges": []any{map[string]any{"text": strings.Replace(greeter, `greet("world")`, "strings.", 1)}},
	})
	got := c.ask(9, "completion", uri, 15, 26, nil)
	if !strings.Contains(got, `"label":"ToUpper"`) {
		t.Fatalf("completion: %.300s", got)
	}
	if !strings.Contains(got, `"newText":", strings"`) || !strings.Contains(got, start(1, 17)) {
		i := strings.Index(got, `"label":"ToUpper"`)
		t.Errorf("the import belongs in the imports directive: %.600s", got[max(i-300, 0):])
	}
}
