// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package lsp

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"net/url"
	"strconv"
	"strings"
	"time"

	"github.com/tlehman/litgo/internal/check"
	"github.com/tlehman/litgo/internal/lit"
)

type message struct {
	JSONRPC string           `json:"jsonrpc"`
	ID      *json.RawMessage `json:"id,omitempty"`
	Method  string           `json:"method,omitempty"`
	Params  json.RawMessage  `json:"params,omitempty"`
	Result  any              `json:"result,omitempty"`
	Error   *rpcError        `json:"error,omitempty"`
}

type rpcError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

func read(r *bufio.Reader) (*message, error) {
	length := 0
	for {
		line, err := r.ReadString('\n')
		if err != nil {
			return nil, err
		}
		line = strings.TrimSpace(line)
		if line == "" {
			break
		}
		if name, value, ok := strings.Cut(line, ":"); ok && strings.EqualFold(name, "Content-Length") {
			length, _ = strconv.Atoi(strings.TrimSpace(value))
		}
	}
	body := make([]byte, length)
	if _, err := io.ReadFull(r, body); err != nil {
		return nil, err
	}
	m := &message{}
	return m, json.Unmarshal(body, m)
}

// frame spells a message the way it goes over the wire.
func frame(m *message) []byte {
	m.JSONRPC = "2.0"
	body, _ := json.Marshal(m)
	return []byte(fmt.Sprintf("Content-Length: %d\r\n\r\n%s", len(body), body))
}

// writer starts the goroutine that writes to a pipe.
func writer(w io.Writer) (messages chan []byte, done chan struct{}) {
	messages, done = make(chan []byte, 64), make(chan struct{})
	go func() {
		defer close(done)
		for b := range messages {
			w.Write(b)
		}
	}()
	return messages, done
}

func (s *server) write(m *message) { s.out <- frame(m) }

type document struct {
	text    string
	version int
	timer   *time.Timer
	res     *lit.Result // what the text tangles to,
	tangled int         // and the version of the text that was tangled
}

// server is the state of the loop in Serve. Only that goroutine touches it.
type server struct {
	out   chan<- []byte // to the goroutine that writes to the editor
	docs  map[string]*document
	utf8  bool // the client counts columns in bytes, as litgo does
	delay time.Duration

	due      chan due      // a document's timer went off
	checked  chan *job     // the type checker is done with a job
	quit     chan struct{} // closed when the server stops
	waiting  map[string]*job
	checking bool // the type checker is busy, and has the cache
	cache    check.Cache

	// The rest is for the chapter after this one.
	goplsBin string
	gopls    *gopls
	overlays map[string]*overlay // by path of the tangled file
}

// due says that a document has not changed for a while since this version.
type due struct {
	uri     string
	version int
}

// Serve speaks the protocol until the client says exit or hangs up. It puts
// the gopls named (or found, if none is named; "off" means none) behind it.
func Serve(in io.Reader, out io.Writer, gopls string) error {
	toEditor, written := writer(out)
	s := &server{out: toEditor, docs: map[string]*document{}, delay: 120 * time.Millisecond,
		due: make(chan due), checked: make(chan *job), quit: make(chan struct{}), waiting: map[string]*job{},
		goplsBin: gopls, overlays: map[string]*overlay{}}
	defer func() {
		close(s.quit)
		s.stop()
		close(toEditor)
		<-written
	}()
	editor, failed := make(chan *message), make(chan error, 1)
	go func() {
		r := bufio.NewReader(in)
		for {
			m, err := read(r)
			if err != nil {
				failed <- err
				return
			}
			select {
			case editor <- m:
			case <-s.quit:
				return
			}
		}
	}()
	for {
		select {
		case m := <-editor:
			if m.Method == "exit" {
				return nil
			}
			s.handle(m)
		case err := <-failed:
			if err == io.EOF {
				return nil
			}
			return err
		case d := <-s.due:
			if _, now := s.current(d.uri); now == d.version {
				s.analyze(d.uri)
			}
		case j := <-s.checked:
			s.finish(j)
		case m, ok := <-s.heard():
			if ok {
				s.gopls.hear(m, s)
			} else {
				s.gopls.hangUp()
			}
		}
	}
}

func (s *server) handle(m *message) {
	switch m.Method {
	case "initialize":
		var p struct {
			Capabilities struct {
				General struct {
					PositionEncodings []string `json:"positionEncodings"`
				} `json:"general"`
			} `json:"capabilities"`
		}
		json.Unmarshal(m.Params, &p)
		s.start(m.Params)
		encoding := "utf-16"
		for _, e := range p.Capabilities.General.PositionEncodings {
			if e == "utf-8" && s.gopls == nil { // gopls counts in UTF-16, and that settles it
				encoding, s.utf8 = e, true
			}
		}
		capabilities := s.capabilities()
		capabilities["positionEncoding"] = encoding
		capabilities["textDocumentSync"] = map[string]any{"openClose": true, "change": 1}
		s.write(&message{ID: m.ID, Result: map[string]any{
			"serverInfo":   map[string]any{"name": "litgo"},
			"capabilities": capabilities,
		}})
	case "shutdown":
		s.write(&message{ID: m.ID, Result: json.RawMessage("null")})
	case "textDocument/didOpen":
		var p struct {
			TextDocument struct {
				URI     string `json:"uri"`
				Text    string `json:"text"`
				Version int    `json:"version"`
			} `json:"textDocument"`
		}
		json.Unmarshal(m.Params, &p)
		s.change(p.TextDocument.URI, p.TextDocument.Text, p.TextDocument.Version)
	case "textDocument/didChange":
		var p struct {
			TextDocument struct {
				URI     string `json:"uri"`
				Version int    `json:"version"`
			} `json:"textDocument"`
			ContentChanges []struct {
				Text string `json:"text"`
			} `json:"contentChanges"`
		}
		json.Unmarshal(m.Params, &p)
		if n := len(p.ContentChanges); n > 0 {
			s.change(p.TextDocument.URI, p.ContentChanges[n-1].Text, p.TextDocument.Version)
		}
	case "textDocument/didClose":
		var p struct {
			TextDocument struct {
				URI string `json:"uri"`
			} `json:"textDocument"`
		}
		json.Unmarshal(m.Params, &p)
		if d := s.docs[p.TextDocument.URI]; d != nil && d.timer != nil {
			d.timer.Stop()
		}
		delete(s.docs, p.TextDocument.URI)
		delete(s.waiting, p.TextDocument.URI)
		s.forget(p.TextDocument.URI)
	default:
		if !s.proxy(m) && m.ID != nil { // a request for something this server does not do
			s.write(&message{ID: m.ID, Error: &rpcError{-32601, "litgo lsp does not implement " + m.Method}})
		}
	}
}

func (s *server) change(uri, text string, version int) {
	if !strings.HasSuffix(uri, ".lit.md") {
		return
	}
	d := s.docs[uri]
	if d == nil {
		d = &document{}
		s.docs[uri] = d
	}
	if d.timer != nil {
		d.timer.Stop()
	}
	d.text, d.version = text, version
	d.timer = time.AfterFunc(s.delay, func() {
		select {
		case s.due <- due{uri, version}:
		case <-s.quit:
		}
	})
}

// current returns the text and version of a document, or version -1.
func (s *server) current(uri string) (string, int) {
	if d := s.docs[uri]; d != nil {
		return d.text, d.version
	}
	return "", -1
}

// job is a type check: what to check, and then what the check found. The
// loop and the checker pass it back and forth and never hold it together.
type job struct {
	uri     string
	version int
	res     *lit.Result
	diags   []lit.Diag // published already
	typed   []lit.Diag // what the type checker adds
}

func (s *server) analyze(uri string) {
	res, version := s.sync(uri)
	if res == nil {
		return
	}
	diags := append(append([]lit.Diag{}, res.Diags...), res.SyntaxCheck()...)
	s.publish(uri, version, res.Doc, diags)
	if res.HasErrors() || len(diags) > len(res.Diags) {
		return
	}
	s.waiting[uri] = &job{uri: uri, version: version, res: res, diags: diags}
	s.check()
}

// check gives the type checker its next job, if it is free and there is one
// that is still worth doing. The cache goes to the checker with the job and
// comes back with it.
func (s *server) check() {
	if s.checking {
		return
	}
	for uri, j := range s.waiting {
		delete(s.waiting, uri)
		if _, now := s.current(uri); now != j.version {
			continue
		}
		s.checking = true
		go func() {
			j.typed = check.Types(j.res, &s.cache)
			select {
			case s.checked <- j:
			case <-s.quit:
			}
		}()
		return
	}
}

// finish publishes what a type check found, if it is still true.
func (s *server) finish(j *job) {
	s.checking = false
	if _, now := s.current(j.uri); now == j.version && len(j.typed) > 0 {
		s.publish(j.uri, j.version, j.res.Doc, append(j.diags, j.typed...))
	}
	s.check()
}

func path(uri string) string {
	if u, err := url.Parse(uri); err == nil && u.Scheme == "file" {
		return u.Path
	}
	return uri
}

func (s *server) publish(uri string, version int, doc *lit.Doc, diags []lit.Diag) {
	type position struct {
		Line      int `json:"line"`
		Character int `json:"character"`
	}
	type diagnostic struct {
		Range struct {
			Start position `json:"start"`
			End   position `json:"end"`
		} `json:"range"`
		Severity int    `json:"severity"`
		Source   string `json:"source"`
		Message  string `json:"message"`
	}
	out := []diagnostic{}
	for _, d := range diags {
		line := ""
		if d.Line >= 0 && d.Line < len(doc.Lines) {
			line = doc.Lines[d.Line]
		}
		start := min(max(d.Col, 0), len(line))
		end := d.EndCol
		if end <= start {
			end = start
			for end < len(line) && (line[end] == '_' || line[end] >= '0' && line[end] <= '9' || line[end] >= 'A' && line[end] <= 'Z' || line[end] >= 'a' && line[end] <= 'z' || line[end] >= 0x80) {
				end++
			}
			if end == start {
				end = min(start+1, len(line))
			}
		}
		end = min(end, len(line))
		var ld diagnostic
		ld.Range.Start = position{d.Line, s.column(line, start)}
		ld.Range.End = position{d.Line, s.column(line, end)}
		ld.Severity, ld.Source, ld.Message = d.Severity, "litgo", d.Message
		if d.Source != "" && d.Source != "litgo" {
			ld.Source = "litgo " + d.Source
		}
		out = append(out, ld)
	}
	params, _ := json.Marshal(map[string]any{"uri": uri, "version": version, "diagnostics": out})
	s.write(&message{Method: "textDocument/publishDiagnostics", Params: params})
}

// column converts a byte offset into the client's unit.
func (s *server) column(line string, offset int) int {
	return units(s.utf8, line, offset)
}

// units converts a byte offset in a line to UTF-16 code units, unless bytes
// are what is wanted.
func units(utf8 bool, line string, offset int) int {
	offset = min(max(offset, 0), len(line))
	if utf8 {
		return offset
	}
	n := 0
	for _, r := range line[:offset] {
		n++
		if r >= 0x10000 {
			n++
		}
	}
	return n
}
