// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package lsp

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"strings"
	"testing"
	"time"
)

const program = "<!-- package: main -->\n<!-- imports: fmt -->\n\n```go\nfunc main() {\n\t// <<greet>>\n}\n```\n\n<!-- chunk: greet -->\n```go\nfmt.Println(\"𝄞\", whom)\n```\n"

// client is the editor's end of a conversation with the server.
type client struct {
	t        *testing.T
	to       io.Writer
	incoming chan *message
}

func connect(t *testing.T, gopls string) *client {
	toServer, fromClient := io.Pipe()
	fromServer, toClient := io.Pipe()
	go Serve(toServer, toClient, gopls)
	t.Cleanup(func() { fromClient.Close() })
	c := &client{t: t, to: fromClient, incoming: make(chan *message, 64)}
	go func() {
		r := bufio.NewReader(fromServer)
		for {
			m, err := read(r)
			if err != nil {
				return
			}
			c.incoming <- m
		}
	}()
	return c
}

func (c *client) send(method string, id int, params any) {
	raw, ok := params.(string)
	if !ok {
		b, _ := json.Marshal(params)
		raw = string(b)
	}
	body := fmt.Sprintf(`{"jsonrpc":"2.0","method":%q,"params":%s}`, method, raw)
	if id > 0 {
		body = fmt.Sprintf(`{"jsonrpc":"2.0","id":%d,"method":%q,"params":%s}`, id, method, raw)
	}
	fmt.Fprintf(c.to, "Content-Length: %d\r\n\r\n%s", len(body), body)
}

func (c *client) next() *message {
	select {
	case m := <-c.incoming:
		return m
	case <-time.After(60 * time.Second):
		c.t.Fatal("the server said nothing for a minute")
		return nil
	}
}

// diagnostics waits for a publication for the given version that satisfies ok.
func (c *client) diagnostics(version int, ok func(string) bool) string {
	for {
		m := c.next()
		if m.Method == "textDocument/publishDiagnostics" && strings.Contains(string(m.Params), fmt.Sprintf(`"version":%d`, version)) && ok(string(m.Params)) {
			return string(m.Params)
		}
	}
}

func TestDiagnosticsComeAndGo(t *testing.T) {
	c := connect(t, "off")
	c.send("initialize", 1, `{"capabilities":{}}`)
	if m := c.next(); !strings.Contains(fmt.Sprint(m.Result), "utf-16") {
		t.Fatalf("a client that offers nothing gets UTF-16: %v", m.Result)
	}
	uri := "file://" + t.TempDir() + "/hello.lit.md"
	c.send("textDocument/didOpen", 0, map[string]any{"textDocument": map[string]any{"uri": uri, "version": 1, "text": program}})
	got := c.diagnostics(1, func(p string) bool { return strings.Contains(p, "undefined: whom") })
	// Line 11, after fmt.Println(" (13 bytes), a clef that is 4 bytes but 2 UTF-16 units, and `", `.
	if !strings.Contains(got, `"start":{"line":11,"character":18}`) || !strings.Contains(got, `"end":{"line":11,"character":22}`) {
		t.Errorf("the error should underline whom, in UTF-16 units: %s", got)
	}

	c.send("textDocument/didChange", 0, map[string]any{
		"textDocument":   map[string]any{"uri": uri, "version": 2},
		"contentChanges": []any{map[string]any{"text": strings.Replace(program, "whom", `"world"`, 1)}},
	})
	c.diagnostics(2, func(p string) bool { return strings.Contains(p, `"diagnostics":[]`) })

	c.send("textDocument/formatting", 2, `{}`)
	if m := c.next(); m.Error == nil || m.Error.Code != -32601 {
		t.Errorf("an unknown request should be refused politely: %+v", m)
	}
}
