// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package check

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/build"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/tlehman/litgo/internal/lit"
)

// pkg is one package about to be checked.
type pkg struct {
	dir, name, path string
	files           []*ast.File // what an importer of the package sees
	tests           []*ast.File // _test.go files of the same package
	types           *types.Package
	checking        bool
}

type checker struct {
	res       *lit.Result
	fset      *token.FileSet
	outputs   map[string]*lit.Output // by path
	pkgs      []*pkg
	byPath    map[string]*pkg   // packages this document writes, by import path
	exports   map[string]string // import path to export data file, for all others
	gc        types.Importer
	goVersion string
	seen      map[string]bool
	diags     []lit.Diag
}

// Cache carries what is worth keeping between checks: where the compiled
// standard library lives. It has no lock, so whoever owns a Cache runs one
// check at a time with it.
type Cache struct {
	std map[string]string
}

// Types type-checks the Go files a document tangles to, without writing
// them, and reports errors at their positions in the document. It reports
// nothing if the files do not parse (the syntax check covers that) or if
// there is no go command to ask about imports.
func Types(res *lit.Result, cache *Cache) []lit.Diag {
	if res.HasErrors() {
		return nil
	}
	c := &checker{res: res, fset: token.NewFileSet(), outputs: map[string]*lit.Output{},
		byPath: map[string]*pkg{}, exports: map[string]string{}, seen: map[string]bool{}}
	if !c.parse() {
		return nil
	}
	c.locate()
	if !c.resolve(cache) {
		return nil
	}
	c.gc = importer.ForCompiler(c.fset, "gc", c.lookup)
	for _, p := range c.pkgs {
		c.check(p, true)
	}
	return c.diags
}

// parse sorts the files into packages. It fails if an output does not parse.
func (c *checker) parse() bool {
	doc := c.res.Doc
	for _, o := range c.res.Files {
		if o.File.Lang == "go" {
			c.outputs[o.Path] = o
		}
	}
	ctx := build.Default
	ctx.OpenFile = func(path string) (io.ReadCloser, error) {
		if o := c.outputs[path]; o != nil {
			return io.NopCloser(bytes.NewReader(o.Bytes())), nil
		}
		return os.Open(path)
	}
	groups := map[string]*pkg{}
	add := func(path string, src any) error {
		dir, base := filepath.Dir(path), filepath.Base(path)
		if ok, _ := ctx.MatchFile(dir, base); !ok {
			return nil
		}
		f, err := parser.ParseFile(c.fset, path, src, parser.SkipObjectResolution)
		if err != nil {
			return err
		}
		test := strings.HasSuffix(base, "_test.go")
		name := f.Name.Name
		p := groups[dir+"\x00"+name]
		if p == nil {
			p = &pkg{dir: dir, name: name}
			groups[dir+"\x00"+name] = p
			c.pkgs = append(c.pkgs, p)
		}
		if test && !strings.HasSuffix(name, "_test") {
			p.tests = append(p.tests, f)
		} else {
			p.files = append(p.files, f)
		}
		return nil
	}

	dirs := map[string]bool{}
	for path, o := range c.outputs {
		if add(path, o.Bytes()) != nil {
			return false
		}
		dirs[filepath.Dir(path)] = true
	}
	if doc.Run != "" || len(doc.Files) > 1 {
		for dir := range dirs {
			entries, _ := os.ReadDir(dir)
			for _, e := range entries {
				path := filepath.Join(dir, e.Name())
				if e.IsDir() || !strings.HasSuffix(path, ".go") || c.outputs[path] != nil {
					continue
				}
				add(path, nil)
			}
		}
	}
	sort.Slice(c.pkgs, func(i, j int) bool {
		return c.pkgs[i].dir+c.pkgs[i].name < c.pkgs[j].dir+c.pkgs[j].name
	})
	return true
}

// locate works out the import path of every package.
func (c *checker) locate() {
	modDir, mod := "", ""
	for _, o := range c.res.Files {
		if filepath.Base(o.Path) == "go.mod" {
			modDir, mod = filepath.Dir(o.Path), string(o.Bytes())
		}
	}
	for dir := filepath.Dir(c.res.Doc.Path); mod == ""; dir = filepath.Dir(dir) {
		if b, err := os.ReadFile(filepath.Join(dir, "go.mod")); err == nil {
			modDir, mod = dir, string(b)
		}
		if dir == filepath.Dir(dir) {
			break
		}
	}
	module := ""
	for _, line := range strings.Split(mod, "\n") {
		if f := strings.Fields(line); len(f) == 2 && f[0] == "module" {
			module = strings.Trim(f[1], `"`)
		} else if len(f) == 2 && f[0] == "go" {
			c.goVersion = "go" + f[1]
		}
	}
	for _, p := range c.pkgs {
		p.path = p.name
		if rel, err := filepath.Rel(modDir, p.dir); module != "" && err == nil && !strings.HasPrefix(rel, "..") {
			p.path = strings.TrimSuffix(module+"/"+filepath.ToSlash(rel), "/.")
			if strings.HasSuffix(p.name, "_test") {
				p.path += "_test"
			}
		}
		if !strings.HasSuffix(p.name, "_test") && p.name != "main" {
			c.byPath[p.path] = p
		}
	}
}

// resolve finds the export data of every package that is imported but not
// written by this document. It fails if the go command cannot be run.
func (c *checker) resolve(cache *Cache) bool {
	if cache.std == nil {
		cache.std = map[string]string{}
	}
	var missing []string
	for _, p := range c.pkgs {
		for _, f := range append(append([]*ast.File{}, p.files...), p.tests...) {
			for _, imp := range f.Imports {
				path := strings.Trim(imp.Path.Value, "\"`")
				if c.byPath[path] != nil || path == "C" || path == "unsafe" || c.seen[path] {
					continue
				}
				c.seen[path] = true
				if file, ok := cache.std[path]; ok && exists(file) {
					c.exports[path] = file
				} else {
					missing = append(missing, path)
				}
			}
		}
	}
	c.seen = map[string]bool{}
	if len(missing) == 0 {
		return true
	}
	args := append([]string{"list", "-e", "-export", "-deps", "-f", "{{if .Export}}{{.ImportPath}}\t{{.Export}}{{end}}", "--"}, missing...)
	cmd := exec.Command("go", args...)
	cmd.Dir = filepath.Dir(c.res.Doc.Path)
	out, err := cmd.Output()
	if _, broken := err.(*exec.Error); broken {
		return false
	}
	for _, line := range strings.Split(string(out), "\n") {
		if path, file, ok := strings.Cut(line, "\t"); ok {
			c.exports[path] = file
			if !strings.Contains(strings.Split(path, "/")[0], ".") {
				cache.std[path] = file
			}
		}
	}
	return true
}

func exists(file string) bool {
	_, err := os.Stat(file)
	return err == nil
}

func (c *checker) lookup(path string) (io.ReadCloser, error) {
	if file := c.exports[path]; file != "" {
		return os.Open(file)
	}
	return nil, os.ErrNotExist
}

// Import implements types.Importer.
func (c *checker) Import(path string) (*types.Package, error) {
	if p := c.byPath[path]; p != nil {
		return c.check(p, false)
	}
	return c.gc.Import(path)
}

// check type-checks a package: as a root, with its tests and with its
// errors reported, or as the import of another package, silently.
func (c *checker) check(p *pkg, root bool) (*types.Package, error) {
	files := p.files
	if root {
		files = append(append([]*ast.File{}, p.files...), p.tests...)
	} else if p.types != nil {
		return p.types, nil
	} else if p.checking {
		return nil, os.ErrInvalid // an import cycle; the root check of it says so
	}
	conf := types.Config{Importer: c, GoVersion: c.goVersion, FakeImportC: true, Error: func(err error) {
		if root {
			c.report(err)
		}
	}}
	p.checking = true
	tp, _ := conf.Check(p.path, c.fset, files, nil)
	p.checking = false
	if !root {
		p.types = tp
	}
	return tp, nil
}

func (c *checker) report(err error) {
	te, ok := err.(types.Error)
	if !ok || len(c.diags) >= 100 {
		return
	}
	pos := c.fset.Position(te.Pos)
	o := c.outputs[pos.Filename]
	if o == nil {
		return
	}
	line, col, _, ok := o.Map(pos.Line-1, pos.Column-1)
	key := fmt.Sprintf("%d:%d:%s", line, col, te.Msg)
	if !ok || c.seen[key] {
		return
	}
	c.seen[key] = true
	c.diags = append(c.diags, lit.Diag{File: c.res.Doc.Path, Line: line, Col: col, Severity: lit.SevError, Message: te.Msg, Source: "types"})
}
