// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package check

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tlehman/litgo/internal/lit"
)

const module = "<!-- file: go.mod -->\n```gomod\nmodule example.com/m\n\ngo 1.22\n```\n\n" +
	"<!-- file: lib/lib.go -->\n<!-- package: lib -->\n<!-- imports: os, strings -->\n" +
	"```go\nfunc Shout(s string) string {\n\t// <<upper>>\n}\n```\n\n" +
	"<!-- chunk: upper -->\n```go\nreturn strings.ToUpper(s) + suffix\n```\n\n" +
	"<!-- file: lib/lib_test.go -->\n<!-- package: lib -->\n<!-- imports: testing -->\n" +
	"```go\nfunc TestShout(t *testing.T) {\n\tif Shout(1) != \"A\" {\n\t\tt.Fail()\n\t}\n}\n```\n\n" +
	"<!-- file: main.go -->\n<!-- package: main -->\n<!-- imports: fmt, example.com/m/lib -->\n" +
	"```go\nfunc main() {\n\tn := 1\n\tfmt.Println(lib.Shout(\"a\"), lib.Whisper)\n}\n```\n"

func TestTypes(t *testing.T) {
	path := filepath.Join(t.TempDir(), "m.lit.md")
	os.WriteFile(path, []byte(module), 0o644)
	doc := lit.Parse(path, []byte(module))
	diags := Types(doc.Tangle(), &Cache{})

	var got []string
	for _, d := range diags {
		got = append(got, strings.TrimSpace(doc.Lines[d.Line][d.Col:])+" ← "+d.Message)
	}
	for _, want := range []string{
		`os, strings --> ← "os" imported and not used`, // on its entry in the directive
		"suffix ← undefined: suffix",                   // inside a chunk
		"1) != \"A\" { ← cannot use 1",                 // in a test file of the package
		"n := 1 ← declared and not used: n",
		"Whisper) ← undefined: lib.Whisper", // through an import of a package that is not on disk
	} {
		text, msg, _ := strings.Cut(want, " ← ")
		found := false
		for _, g := range got {
			found = found || strings.HasPrefix(g, text) && strings.Contains(g, msg)
		}
		if !found {
			t.Errorf("missing %q in:\n%s", want, strings.Join(got, "\n"))
		}
	}
	if len(diags) != 5 {
		t.Errorf("%d diagnostics, want 5:\n%s", len(diags), strings.Join(got, "\n"))
	}
}

func TestSingleProgramStandsAlone(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "other.go"), []byte("package main\n\nfunc main() {}\n"), 0o644)
	src := "<!-- package: main -->\n```go\nfunc main() {}\n```\n"
	doc := lit.Parse(filepath.Join(dir, "one.lit.md"), []byte(src))
	if diags := Types(doc.Tangle(), &Cache{}); len(diags) != 0 {
		t.Errorf("a second main in the directory is not this program's business: %+v", diags)
	}
}
