-- Code generated by litgo from litgo.lit.md; DO NOT EDIT.

-- Loaded automatically when this directory is on the runtimepath. Calling
-- require("litgo").setup({...}) yourself (before or after) overrides options.
if vim.g.loaded_litgo then
  return
end

vim.g.loaded_litgo = true

if vim.fn.has("nvim-0.11") == 0 then
  vim.notify("litgo needs Neovim 0.11 or newer (inline virtual text, conceal_lines)", vim.log.levels.WARN)
  return
end

require("litgo").setup()
