// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package lit

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/tlehman/litgo/internal/latex"
	"github.com/tlehman/litgo/internal/mermaid"
)

// Item is something an editor can render in place of, or next to, source text.
type Item struct {
	Kind    string   `json:"kind"` // math, math-block, mermaid, table, chunk-def, chunk-ref, file
	Line    int      `json:"line"`
	Col     int      `json:"col"`
	EndLine int      `json:"end_line"`
	EndCol  int      `json:"end_col"`
	Text    string   `json:"text,omitempty"`  // one-line replacement
	Lines   []string `json:"lines,omitempty"` // block rendering
	Info    string   `json:"info,omitempty"`  // end-of-line annotation
	Name    string   `json:"name,omitempty"`
	Error   string   `json:"error,omitempty"`

	Table *Table `json:"table,omitempty"`
}

// ChunkInfo locates a chunk's definitions and uses for navigation.
type ChunkInfo struct {
	Name string     `json:"name"`
	Defs []ChunkDef `json:"defs"`
	Refs []ChunkUse `json:"refs"`
}

type ChunkDef struct {
	Directive int `json:"directive"`
	First     int `json:"first"` // first code line
	Last      int `json:"last"`  // last code line, inclusive
}

type ChunkUse struct {
	Line   int `json:"line"`
	Col    int `json:"col"`
	EndCol int `json:"end_col"`
}

// Analysis is everything the editor needs after a change.
type Analysis struct {
	Items       []Item      `json:"items"`
	Chunks      []ChunkInfo `json:"chunks"`
	Diagnostics []Diag      `json:"diagnostics"`
	Outputs     []string    `json:"outputs"`
}

// AnalyzeOptions tune rendering.
type AnalyzeOptions struct {
	Upright bool
}

// Analyze renders math and diagrams, annotates chunks, and checks the
// document: undefined or unused chunks, cycles, and Go syntax errors.
func (d *Doc) Analyze(o AnalyzeOptions) *Analysis {
	a := &Analysis{Items: []Item{}, Chunks: []ChunkInfo{}, Diagnostics: []Diag{}, Outputs: []string{}}
	res := d.Tangle()
	for _, o := range res.Files {
		a.Outputs = append(a.Outputs, o.Path)
	}
	a.Diagnostics = append(a.Diagnostics, res.Diags...)
	a.Diagnostics = append(a.Diagnostics, res.SyntaxCheck()...)

	inBlock := make([]bool, len(d.Lines))
	for _, b := range d.Blocks {
		for i := b.Open; i <= b.Close && i < len(d.Lines); i++ {
			inBlock[i] = true
		}
		switch b.Lang {
		case "mermaid":
			it := Item{Kind: "mermaid", Line: b.Open, EndLine: min(b.Close, len(d.Lines)-1)}
			lines, err := mermaid.Render(strings.Join(d.Lines[b.First():b.Last()+1], "\n"))
			if err != nil {
				it.Error = err.Error()
				it.Lines = []string{"[mermaid: " + err.Error() + "]"}
			} else {
				it.Lines = lines
			}
			a.Items = append(a.Items, it)
		case "math", "latex", "tex":
			if b.Last() >= b.First() {
				src := strings.Join(d.Lines[b.First():b.Last()+1], "\n")
				a.Items = append(a.Items, Item{Kind: "math-block", Line: b.Open, EndLine: min(b.Close, len(d.Lines)-1),
					Lines: latex.Render(src, latex.Options{Display: true, Upright: o.Upright})})
			}
		}
	}
	a.Items = append(a.Items, d.mathItems(inBlock, o)...)
	a.Items = append(a.Items, d.tableItems(inBlock, o)...)

	for _, f := range d.Files[1:] {
		a.Items = append(a.Items, Item{Kind: "file", Line: f.Line, EndLine: f.Line, EndCol: len(d.Lines[f.Line]), Text: "▸ " + f.Path})
	}

	chunks := d.Chunks()
	for _, c := range chunks {
		info := ChunkInfo{Name: c.Name, Defs: []ChunkDef{}, Refs: []ChunkUse{}}
		for _, b := range c.Blocks {
			info.Defs = append(info.Defs, ChunkDef{Directive: b.ChunkLine, First: b.First(), Last: b.Last()})
		}
		for _, r := range c.Refs {
			info.Refs = append(info.Refs, ChunkUse{Line: r.Line, Col: r.Col, EndCol: r.EndCol})
		}
		a.Chunks = append(a.Chunks, info)
	}
	for _, c := range chunks {
		for i, b := range c.Blocks {
			text := "⟨" + c.Name + "⟩ ≡"
			if i > 0 {
				text = "⟨" + c.Name + "⟩ +≡"
			}
			info := "unused"
			switch n := len(c.Refs); {
			case n == 1:
				info = fmt.Sprintf("← used at line %d", c.Refs[0].Line+1)
			case n > 1:
				var at []string
				for _, r := range c.Refs {
					at = append(at, fmt.Sprint(r.Line+1))
				}
				info = "← used at lines " + strings.Join(at, ", ")
			}
			a.Items = append(a.Items, Item{Kind: "chunk-def", Name: c.Name, Line: b.ChunkLine, EndLine: b.ChunkLine,
				Col: 0, EndCol: len(d.Lines[b.ChunkLine]), Text: text, Info: info})
		}
		for _, r := range c.Refs {
			it := Item{Kind: "chunk-ref", Name: c.Name, Line: r.Line, EndLine: r.Line, Col: r.Col, EndCol: r.EndCol, Text: "⟨" + c.Name + "⟩"}
			if len(c.Blocks) == 0 {
				it.Info = "undefined"
			} else {
				n := 0
				for _, b := range c.Blocks {
					n += b.Last() - b.First() + 1
				}
				it.Info = fmt.Sprintf("→ line %d · %d line%s", c.Blocks[0].First()+1, n, plural(n))
			}
			if r.Inline {
				it.Info = ""
			}
			a.Items = append(a.Items, it)
		}
	}
	return a
}

func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}

var displayOpenRe = regexp.MustCompile(`^\s*(\$\$|\\\[)`)

// mathItems finds LaTeX in prose: $inline$, \(inline\), and display math in
// $$...$$ or \[...\], on one line or spanning several.
func (d *Doc) mathItems(inBlock []bool, o AnalyzeOptions) []Item {
	var items []Item
	for i := 0; i < len(d.Lines); i++ {
		if inBlock[i] || directiveRe.MatchString(d.Lines[i]) {
			continue
		}
		line := d.Lines[i]
		if m := displayOpenRe.FindStringSubmatch(line); m != nil {
			closer := map[string]string{"$$": "$$", `\[`: `\]`}[m[1]]
			body := strings.TrimSpace(line)[len(m[1]):]
			end := -1
			var src []string
			if rest := strings.TrimSpace(body); strings.HasSuffix(rest, closer) && len(rest) >= len(closer) {
				end, src = i, []string{strings.TrimSuffix(rest, closer)}
			} else if !strings.Contains(body, closer) {
				src = []string{body}
				for j := i + 1; j < len(d.Lines) && j < i+200 && !inBlock[j]; j++ {
					t := strings.TrimSpace(d.Lines[j])
					if strings.HasSuffix(t, closer) {
						src = append(src, strings.TrimSuffix(t, closer))
						end = j
						break
					}
					src = append(src, d.Lines[j])
				}
			}
			if end >= 0 {
				if tex := strings.TrimSpace(strings.Join(src, "\n")); tex != "" {
					items = append(items, Item{Kind: "math-block", Line: i, EndLine: end, EndCol: len(d.Lines[end]),
						Lines: latex.Render(tex, latex.Options{Display: true, Upright: o.Upright})})
				}
				i = end
				continue
			}
		}
		items = append(items, inlineMath(line, i, o)...)
	}
	return items
}

func inlineMath(line string, lineNo int, o AnalyzeOptions) []Item {
	var items []Item
	add := func(start, end int, tex string) {
		tex = strings.TrimSpace(tex)
		if tex == "" {
			return
		}
		text := latex.Render(tex, latex.Options{Upright: o.Upright})[0]
		items = append(items, Item{Kind: "math", Line: lineNo, EndLine: lineNo, Col: start, EndCol: end, Text: text})
	}
	for i := 0; i < len(line); i++ {
		switch c := line[i]; {
		case c == '\\' && i+1 < len(line) && line[i+1] == '(':
			if j := strings.Index(line[i+2:], `\)`); j >= 0 {
				add(i, i+2+j+2, line[i+2:i+2+j])
				i += 2 + j + 1
			}
		case c == '\\':
			i++ // escaped character, including \$
		case c == '`':
			// Skip the code span: a run of n backticks closes at the next run of n.
			n := 1
			for i+n < len(line) && line[i+n] == '`' {
				n++
			}
			if j := strings.Index(line[i+n:], strings.Repeat("`", n)); j >= 0 {
				i += n + j + n - 1
			} else {
				i += n - 1
			}
		case c == '$':
			delim := "$"
			if i+1 < len(line) && line[i+1] == '$' {
				delim = "$$"
			}
			start := i + len(delim)
			if start >= len(line) || line[start] == ' ' || line[start] == '\t' {
				i = start - 1
				continue
			}
			// The closer must hug the formula and not be followed by a digit,
			// so prices like $5 and $10 stay prose.
			for j := start; j < len(line); j++ {
				if line[j] == '\\' {
					j++
					continue
				}
				if !strings.HasPrefix(line[j:], delim) {
					continue
				}
				after := j + len(delim)
				if line[j-1] == ' ' && after < len(line) && line[after] != ' ' {
					break // this $ opens something itself, so ours was a literal dollar
				}
				if line[j-1] == ' ' || (delim == "$" && after < len(line) && line[after] >= '0' && line[after] <= '9') {
					continue
				}
				add(i, after, line[start:j])
				i = after - 1
				break
			}
		}
	}
	return items
}

// Table is what an editor needs to line up the columns of a table in place.
type Table struct {
	Align []string   `json:"align"` // left, right or center, for each column
	Rule  []Cell     `json:"rule"`  // the cells of the rule under the header
	Rows  []TableRow `json:"rows"`  // the header, and then the rows under the rule
}

type TableRow struct {
	Line  int      `json:"line"`
	Cells []Cell   `json:"cells"`
	Hide  [][2]int `json:"hide,omitempty"` // columns of the markup that is not shown
}

// Cell is one cell of a row. From and To are the pipes around it (or the
// ends of the row), Col and EndCol are its text without the spaces around it.
type Cell struct {
	From   int    `json:"from"`
	To     int    `json:"to"`
	Col    int    `json:"col"`
	EndCol int    `json:"end_col"`
	Text   string `json:"text"` // what the reader sees
}

var tableRuleRe = regexp.MustCompile(`^\s*\|?\s*:?-+:?\s*(\|\s*:?-+:?\s*)*\|?\s*$`)

// tableItems finds the tables in prose.
func (d *Doc) tableItems(inBlock []bool, o AnalyzeOptions) []Item {
	var items []Item
	row := func(i int) bool {
		return i < len(d.Lines) && !inBlock[i] && strings.Contains(d.Lines[i], "|") && !directiveRe.MatchString(d.Lines[i])
	}
	for i := 0; i < len(d.Lines); i++ {
		if !row(i) || !row(i+1) || !tableRuleRe.MatchString(d.Lines[i+1]) {
			continue
		}
		t := &Table{Rule: cells(d.Lines[i+1])}
		if len(cells(d.Lines[i])) != len(t.Rule) {
			continue
		}
		for _, r := range t.Rule {
			rule := d.Lines[i+1][r.Col:r.EndCol]
			switch left, right := strings.HasPrefix(rule, ":"), strings.HasSuffix(rule, ":"); {
			case left && right:
				t.Align = append(t.Align, "center")
			case right:
				t.Align = append(t.Align, "right")
			default:
				t.Align = append(t.Align, "left")
			}
		}
		end := i + 1
		for j := i; row(j); j++ {
			if j == i+1 {
				continue
			}
			r := TableRow{Line: j, Cells: cells(d.Lines[j])}
			for c := range r.Cells {
				cell := &r.Cells[c]
				var hide [][2]int
				cell.Text, hide = cellText(d.Lines[j], cell.Col, cell.EndCol, o)
				r.Hide = append(r.Hide, hide...)
			}
			t.Rows = append(t.Rows, r)
			end = j
		}
		items = append(items, Item{Kind: "table", Line: i, EndLine: end, EndCol: len(d.Lines[end]), Table: t})
		i = end
	}
	return items
}

// cells splits a row at its pipes. A pipe with a backslash in front of it is
// part of a cell, and the pipes at the ends of the row are not cells.
func cells(line string) []Cell {
	start, end := 0, len(line)
	for start < end && (line[start] == ' ' || line[start] == '\t') {
		start++
	}
	for end > start && (line[end-1] == ' ' || line[end-1] == '\t') {
		end--
	}
	if start < end && line[start] == '|' {
		start++
	}
	if end > start && line[end-1] == '|' && (end-1 == start || line[end-2] != '\\') {
		end--
	}
	var out []Cell
	from := start
	for i := start; i <= end; i++ {
		if i == end || line[i] == '|' && line[i-1] != '\\' {
			c := Cell{From: from, To: i, Col: from, EndCol: i}
			for c.Col < c.EndCol && line[c.Col] == ' ' {
				c.Col++
			}
			for c.EndCol > c.Col && line[c.EndCol-1] == ' ' {
				c.EndCol--
			}
			out = append(out, c)
			from = i + 1
		}
	}
	return out
}

var markupRe = regexp.MustCompile("`+([^`]+)`+" + `|\*\*([^*]+)\*\*|\*([^*]+)\*|\[([^\]]+)\]\([^)]*\)|\\(\|)`)

// cellText is line[col:end] the way a reader sees it, and the columns of
// the markup that the reader does not see.
func cellText(line string, col, end int, o AnalyzeOptions) (string, [][2]int) {
	var sb strings.Builder
	var hide [][2]int
	plain := func(from, to int) {
		at := from
		for _, m := range markupRe.FindAllStringSubmatchIndex(line[from:to], -1) {
			for g := 2; g < len(m); g += 2 {
				if m[g] >= 0 {
					sb.WriteString(line[at:from+m[0]] + line[from+m[g]:from+m[g+1]])
					hide = append(hide, [2]int{from + m[0], from + m[g]})
					if m[g+1] < m[1] {
						hide = append(hide, [2]int{from + m[g+1], from + m[1]})
					}
				}
			}
			at = from + m[1]
		}
		sb.WriteString(line[at:to])
	}
	at := col
	for _, m := range inlineMath(line[col:end], 0, o) {
		plain(at, col+m.Col)
		sb.WriteString(m.Text)
		at = col + m.EndCol
	}
	plain(at, end)
	return sb.String(), hide
}
