// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package lit

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"
)

// Severity of a diagnostic, matching vim.diagnostic.severity.
const (
	SevError   = 1
	SevWarning = 2
	SevInfo    = 3
)

// Diag is a problem located in a .lit.md source file.
type Diag struct {
	File     string `json:"file,omitempty"`
	Line     int    `json:"line"`
	Col      int    `json:"col"`
	EndCol   int    `json:"end_col,omitempty"`
	Severity int    `json:"severity"`
	Message  string `json:"message"`
	Source   string `json:"source"`
}

// Directive is a `<!-- key: value -->` line outside of any code fence.
type Directive struct {
	Key      string
	Value    string
	Line     int
	ValueCol int // byte column where Value starts
}

// Import is one entry of an `imports:` directive.
type Import struct {
	Alias string
	Path  string
	Line  int
	Col   int // column of the entry within the directive line
	Len   int
}

// File is one tangled output. A document always has a default file, named
// after the document; each `file:` directive starts another.
type File struct {
	Path    string // as written; relative paths are relative to the document
	Lang    string
	Line    int // line of the file directive, -1 for the default file
	Package string
	PkgDir  *Directive
	Imports []Import
}

// Block is a fenced code block.
type Block struct {
	Lang      string
	File      *File  // the file being written when the block appears
	Chunk     string // chunk name; "" means a root block
	ChunkLine int    // line of the chunk directive, -1 if none
	NoTangle  bool
	Verbatim  bool // text that looks like a reference is just text
	Open      int  // line of the opening fence
	Close     int  // line of the closing fence (len(Lines) if unterminated)
	Strip     int  // fence indentation, stripped from each content line
}

// First and Last content lines (Last is inclusive; Last < First if empty).
func (b *Block) First() int { return b.Open + 1 }
func (b *Block) Last() int  { return b.Close - 1 }

// Doc is a parsed .lit.md document.
type Doc struct {
	Path       string
	Lines      []string
	Directives []Directive
	Blocks     []*Block
	Files      []*File // Files[0] is the default file

	Run      string
	Excludes []*regexp.Regexp
	Diags    []Diag
}

var (
	directiveRe = regexp.MustCompile(`^\s*<!--\s*([A-Za-z][A-Za-z0-9-]*)\s*(?::\s*(.*?))?\s*-->\s*$`)
	fenceRe     = regexp.MustCompile("^( {0,3}|\t*)(```+|~~~+)\\s*([^\\s`]*)(.*)$")

	// RefLineRe matches a whole-line chunk reference: a line comment holding
	// nothing but <<name>>, in the comment syntax of C-like languages, of Lua
	// and SQL, or of the shell family.
	RefLineRe = regexp.MustCompile(`^(\s*)(//|--|#)\s*<<\s*(.+?)\s*>>\s*$`)
	// RefInlineRe matches an inline chunk reference: a block comment.
	RefInlineRe = regexp.MustCompile(`(/\*|--\[\[)\s*<<\s*(.+?)\s*>>\s*(\*/|\]\])`)
)

var knownDirectives = map[string]bool{
	"tangler": true, "package": true, "imports": true, "tangler-exclude": true,
	"output": true, "file": true, "run": true, "chunk": true, "notangle": true, "verbatim": true,
}

// languages maps a file extension to the fence language of the blocks that
// belong in such a file. Anything else uses the extension itself.
var languages = map[string]string{
	".mod": "gomod", ".md": "markdown", ".py": "python", ".rb": "ruby", ".rs": "rust",
	".js": "javascript", ".ts": "typescript", ".yml": "yaml", ".bash": "sh",
}

func langOf(path string) string {
	ext := strings.ToLower(filepath.Ext(path))
	if l, ok := languages[ext]; ok {
		return l
	}
	if ext == "" {
		return strings.ToLower(filepath.Base(path)) // Makefile → makefile
	}
	return ext[1:]
}

// Comments describes how a language writes the comments that carry chunk
// references and the generated-code marker.
type Comments struct{ Line, Open, Close string }

// CommentsFor returns the comment syntax of a fence language. Languages litgo
// does not know get no marker and no reference syntax of their own.
func CommentsFor(lang string) Comments {
	switch lang {
	case "go", "gomod", "c", "cpp", "java", "javascript", "typescript", "rust", "swift", "kotlin", "zig", "css", "typ", "typst":
		return Comments{"//", "/*", "*/"}
	case "lua":
		return Comments{"--", "--[[", "]]"}
	case "sql", "haskell":
		return Comments{Line: "--"}
	case "sh", "bash", "zsh", "fish", "python", "ruby", "yaml", "toml", "makefile", "make", "dockerfile", "nix", "gitignore":
		return Comments{Line: "#"}
	}
	return Comments{}
}

// NormName canonicalises a chunk name: trimmed, inner whitespace collapsed.
func NormName(s string) string { return strings.Join(strings.Fields(s), " ") }

// Parse reads a .lit.md document. Errors land in Diags.
func Parse(path string, src []byte) *Doc {
	text := strings.ReplaceAll(string(src), "\r\n", "\n")
	text = strings.TrimSuffix(text, "\n")
	d := &Doc{Path: path}
	if text != "" || len(src) > 0 {
		d.Lines = strings.Split(text, "\n")
	}
	cur := &File{Lang: "go", Line: -1}
	d.Files = []*File{cur}

	var pending *Directive // chunk directive awaiting its block
	noTangle, verbatim := false, false
	for i := 0; i < len(d.Lines); i++ {
		line := d.Lines[i]
		if m := fenceRe.FindStringSubmatch(line); m != nil {
			b := &Block{Lang: strings.ToLower(m[3]), File: cur, Open: i, ChunkLine: -1, Strip: len(m[1])}
			b.Lang = strings.Trim(b.Lang, "{}.")
			marker := m[2]
			b.Close = len(d.Lines)
			for j := i + 1; j < len(d.Lines); j++ {
				t := strings.TrimSpace(d.Lines[j])
				if strings.HasPrefix(t, marker) && strings.Trim(t, marker[:1]) == "" {
					b.Close = j
					break
				}
			}
			if b.Close == len(d.Lines) {
				d.diag(i, 0, SevWarning, "code fence is never closed")
			}
			if pending != nil {
				b.Chunk, b.ChunkLine = NormName(pending.Value), pending.Line
			}
			b.NoTangle, b.Verbatim = noTangle, verbatim
			pending, noTangle, verbatim = nil, false, false
			d.Blocks = append(d.Blocks, b)
			i = b.Close
			continue
		}
		if m := directiveRe.FindStringSubmatchIndex(line); m != nil {
			key := strings.ToLower(line[m[2]:m[3]])
			if knownDirectives[key] {
				dir := Directive{Key: key, Line: i, ValueCol: m[3]}
				if m[4] >= 0 {
					dir.Value, dir.ValueCol = line[m[4]:m[5]], m[4]
				}
				d.Directives = append(d.Directives, dir)
				switch key {
				case "chunk":
					if NormName(dir.Value) == "" {
						d.diag(i, 0, SevError, "chunk directive needs a name")
					} else {
						p := dir
						pending = &p
					}
				case "notangle":
					noTangle = true
				case "verbatim":
					verbatim = true
				case "file":
					if p := strings.TrimSpace(dir.Value); p == "" {
						d.diag(i, 0, SevError, "file directive needs a path")
					} else {
						cur = &File{Path: p, Lang: langOf(p), Line: i}
						d.Files = append(d.Files, cur)
					}
				default:
					d.apply(&d.Directives[len(d.Directives)-1], cur)
				}
				continue
			}
		}
		if strings.TrimSpace(line) != "" {
			if pending != nil {
				d.diag(pending.Line, 0, SevWarning, fmt.Sprintf("chunk directive %q is not followed by a code block", NormName(pending.Value)))
			}
			pending, noTangle, verbatim = nil, false, false
		}
	}
	if pending != nil {
		d.diag(pending.Line, 0, SevWarning,
			fmt.Sprintf("chunk directive %q is not followed by a code block", NormName(pending.Value)))
	}
	return d
}

func (d *Doc) diag(line, col, sev int, msg string) {
	d.Diags = append(d.Diags, Diag{Line: line, Col: col, Severity: sev, Message: msg, Source: "litgo"})
}

// apply handles the directives that configure the document or the file
// currently being written.
func (d *Doc) apply(dir *Directive, cur *File) {
	switch dir.Key {
	case "tangler":
		d.Files[0].Lang = strings.ToLower(strings.TrimSpace(dir.Value))
	case "output":
		d.Files[0].Path = strings.TrimSpace(dir.Value)
	case "package":
		cur.Package = strings.TrimSpace(dir.Value)
		cur.PkgDir = dir
	case "run":
		d.Run = strings.TrimSpace(dir.Value)
	case "tangler-exclude":
		re, err := regexp.Compile(dir.Value)
		if err != nil {
			d.diag(dir.Line, dir.ValueCol, SevError, "bad tangler-exclude pattern: "+err.Error())
			return
		}
		d.Excludes = append(d.Excludes, re)
	case "imports":
		// Entries are comma separated; each is `path` or `alias path`.
		off := 0
		for _, part := range strings.Split(dir.Value, ",") {
			entry := strings.TrimSpace(part)
			col := dir.ValueCol + off + strings.Index(part, entry)
			off += len(part) + 1
			if entry == "" {
				continue
			}
			imp := Import{Line: dir.Line, Col: col, Len: len(entry)}
			f := strings.Fields(entry)
			imp.Path = strings.Trim(f[len(f)-1], `"`)
			if len(f) > 1 {
				imp.Alias = f[0]
			}
			cur.Imports = append(cur.Imports, imp)
		}
	}
}

// OutPath is where a file is written. The default file is named after the
// document: name.lit.md tangles to name.go.
func (d *Doc) OutPath(f *File) string {
	dir := filepath.Dir(d.Path)
	if f.Path != "" {
		if filepath.IsAbs(f.Path) {
			return f.Path
		}
		return filepath.Join(dir, f.Path)
	}
	base := filepath.Base(d.Path)
	base = strings.TrimSuffix(base, ".md")
	base = strings.TrimSuffix(base, ".lit")
	ext := f.Lang
	if ext == "" {
		ext = "txt"
	}
	return filepath.Join(dir, base+"."+ext)
}

// IsRoot reports whether the block is written straight into its file: it is
// unnamed and in the file's language.
func (b *Block) IsRoot() bool { return b.Chunk == "" && !b.NoTangle && b.Lang == b.File.Lang }

// Tangled reports whether the block takes part in tangling, as a root block
// or as a chunk.
func (b *Block) Tangled() bool { return !b.NoTangle && (b.Chunk != "" || b.IsRoot()) }

// BlockAt returns the block whose fences or content include the line.
func (d *Doc) BlockAt(line int) *Block {
	for _, b := range d.Blocks {
		if line >= b.Open && line <= b.Close {
			return b
		}
	}
	return nil
}

// Ref is one use of a chunk.
type Ref struct {
	Name   string
	Line   int
	Col    int // start of the reference syntax
	EndCol int
	Inline bool
	Indent string
	Open   string // comment opener as written, reused when the reference is renamed
	Close  string
}

// Text spells a reference to name in the same comment syntax.
func (r Ref) Text(name string) string {
	if r.Inline {
		return r.Open + "<<" + name + ">>" + r.Close
	}
	return r.Open + " <<" + name + ">>"
}

// RefsIn lists the chunk references on one source line.
func RefsIn(line string, lineNo int) []Ref {
	if m := RefLineRe.FindStringSubmatchIndex(line); m != nil {
		return []Ref{{Name: NormName(line[m[6]:m[7]]), Line: lineNo, Col: m[3], EndCol: len(strings.TrimRight(line, " \t")),
			Indent: line[m[2]:m[3]], Open: line[m[4]:m[5]]}}
	}
	var out []Ref
	for _, m := range RefInlineRe.FindAllStringSubmatchIndex(line, -1) {
		out = append(out, Ref{Name: NormName(line[m[4]:m[5]]), Line: lineNo, Col: m[0], EndCol: m[1], Inline: true,
			Open: line[m[2]:m[3]], Close: line[m[6]:m[7]]})
	}
	return out
}

// refs lists the references a block makes; a verbatim block makes none.
func (d *Doc) refs(b *Block, line int) []Ref {
	if b.Verbatim {
		return nil
	}
	return RefsIn(d.Lines[line], line)
}

// Chunk gathers every block sharing a name, plus all references to it.
type Chunk struct {
	Name   string
	Blocks []*Block
	Refs   []Ref
}

// Chunks indexes named chunks in document order. References to undefined
// chunks appear as entries with no Blocks.
func (d *Doc) Chunks() []*Chunk {
	byName := map[string]*Chunk{}
	var order []*Chunk
	get := func(name string) *Chunk {
		c := byName[name]
		if c == nil {
			c = &Chunk{Name: name}
			byName[name] = c
			order = append(order, c)
		}
		return c
	}
	for _, b := range d.Blocks {
		if b.Tangled() && b.Chunk != "" {
			c := get(b.Chunk)
			c.Blocks = append(c.Blocks, b)
		}
	}
	for _, b := range d.Blocks {
		if !b.Tangled() {
			continue
		}
		for i := b.First(); i <= b.Last(); i++ {
			for _, r := range d.refs(b, i) {
				c := get(r.Name)
				c.Refs = append(c.Refs, r)
			}
		}
	}
	return order
}
