// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package lit

import (
	"fmt"
	"strings"
)

// Edit replaces source lines [Start, End) with Lines. A list of edits is
// ordered bottom-up so an editor can apply them one after another.
type Edit struct {
	Start int      `json:"start"`
	End   int      `json:"end"`
	Lines []string `json:"lines"`
}

// Selection is a region of a document. With EndCol < 0 it is linewise;
// otherwise StartCol is the first selected byte and EndCol the byte just past
// the selection.
type Selection struct {
	StartLine, EndLine int // inclusive
	StartCol, EndCol   int
}

// UntangleResult describes the edits that extract a selection into a chunk.
type UntangleResult struct {
	Name    string `json:"name"`
	Inline  bool   `json:"inline"`
	RefLine int    `json:"ref_line"` // where the reference ends up
	DefLine int    `json:"def_line"` // first code line of the new chunk, after edits
	Edits   []Edit `json:"edits"`
}

// Untangle moves the selection into a new named chunk at the bottom of the
// document and leaves a reference in its place. Because chunks are spliced in
// textually, the extracted code keeps the lexical scope it had.
func (d *Doc) Untangle(sel Selection, name string) (*UntangleResult, error) {
	if sel.StartLine < 0 || sel.EndLine >= len(d.Lines) || sel.StartLine > sel.EndLine {
		return nil, fmt.Errorf("selection is outside the document")
	}
	b := d.BlockAt(sel.StartLine)
	if b == nil || !b.Tangled() || sel.StartLine < b.First() || sel.EndLine > b.Last() {
		return nil, fmt.Errorf("select lines inside a single tangled code block")
	}
	comments := CommentsFor(b.Lang)
	if comments.Line == "" {
		return nil, fmt.Errorf("litgo does not know how to write a comment in %q, so it cannot leave a reference", b.Lang)
	}

	first, last := d.Lines[sel.StartLine], d.Lines[sel.EndLine]
	inline := sel.EndCol >= 0
	if inline {
		sel.StartCol = min(max(sel.StartCol, 0), len(first))
		sel.EndCol = min(max(sel.EndCol, 0), len(last))
		// A charwise selection that covers whole lines is really linewise.
		if strings.TrimSpace(first[:sel.StartCol]) == "" && strings.TrimSpace(last[sel.EndCol:]) == "" {
			inline = false
		}
		if inline && comments.Open == "" {
			return nil, fmt.Errorf("%s has no block comments, so only whole lines can be untangled", b.Lang)
		}
	}

	var body []string
	var replacement string
	if inline {
		hostIndent := first[:len(first)-len(strings.TrimLeft(first, " \t"))]
		if sel.StartLine == sel.EndLine {
			if sel.EndCol <= sel.StartCol {
				return nil, fmt.Errorf("selection is empty")
			}
			body = []string{first[sel.StartCol:sel.EndCol]}
		} else {
			body = append(body, first[sel.StartCol:])
			for i := sel.StartLine + 1; i < sel.EndLine; i++ {
				body = append(body, strings.TrimPrefix(d.Lines[i], hostIndent))
			}
			body = append(body, strings.TrimPrefix(last[:sel.EndCol], hostIndent))
		}
		if strings.TrimSpace(strings.Join(body, "")) == "" {
			return nil, fmt.Errorf("selection is empty")
		}
	} else {
		body = append(body, d.Lines[sel.StartLine:sel.EndLine+1]...)
		for len(body) > 0 && strings.TrimSpace(body[0]) == "" {
			body = body[1:]
			sel.StartLine++
		}
		for len(body) > 0 && strings.TrimSpace(body[len(body)-1]) == "" {
			body = body[:len(body)-1]
			sel.EndLine--
		}
		if len(body) == 0 {
			return nil, fmt.Errorf("selection is empty")
		}
	}

	name = NormName(name)
	if name == "" {
		name = SuggestName(body, inline)
	}
	name = d.uniqueName(name)

	if inline {
		ref := Ref{Inline: true, Open: comments.Open, Close: comments.Close}
		replacement = first[:sel.StartCol] + ref.Text(name) + last[sel.EndCol:]
	} else {
		indent := commonIndent(body)
		for i, l := range body {
			body[i] = strings.TrimPrefix(l, indent)
			if strings.TrimSpace(l) == "" {
				body[i] = ""
			}
		}
		replacement = indent + Ref{Open: comments.Line}.Text(name)
	}

	// Append the chunk at the bottom, separated by exactly one blank line.
	end := len(d.Lines)
	for end > 0 && strings.TrimSpace(d.Lines[end-1]) == "" {
		end--
	}
	tail := []string{"", "<!-- chunk: " + name + " -->", "```" + b.Lang}
	tail = append(tail, body...)
	tail = append(tail, "```")

	res := &UntangleResult{Name: name, Inline: inline, RefLine: sel.StartLine}
	res.Edits = []Edit{
		{Start: end, End: len(d.Lines), Lines: tail},
		{Start: sel.StartLine, End: sel.EndLine + 1, Lines: []string{replacement}},
	}
	res.DefLine = end + 3 - (sel.EndLine - sel.StartLine)
	return res, nil
}

func (d *Doc) uniqueName(name string) string {
	taken := map[string]bool{}
	for _, c := range d.Chunks() {
		taken[c.Name] = true
	}
	if !taken[name] {
		return name
	}
	for i := 2; ; i++ {
		if n := fmt.Sprintf("%s %d", name, i); !taken[n] {
			return n
		}
	}
}

func commonIndent(lines []string) string {
	indent, seen := "", false
	for _, l := range lines {
		if strings.TrimSpace(l) == "" {
			continue
		}
		ws := l[:len(l)-len(strings.TrimLeft(l, " \t"))]
		if !seen {
			indent, seen = ws, true
			continue
		}
		n := 0
		for n < len(indent) && n < len(ws) && indent[n] == ws[n] {
			n++
		}
		indent = indent[:n]
	}
	return indent
}

// Apply runs bottom-up edits against the document's lines.
func Apply(lines []string, edits []Edit) []string {
	out := append([]string{}, lines...)
	for _, e := range edits {
		next := append([]string{}, out[:e.Start]...)
		next = append(next, e.Lines...)
		out = append(next, out[e.End:]...)
	}
	return out
}

// ChunkAt names the chunk a line belongs to: a reference on the line, the
// chunk directive, or the chunk block around it. col < 0 means "anywhere".
func (d *Doc) ChunkAt(line, col int) string {
	if line < 0 || line >= len(d.Lines) {
		return ""
	}
	if b := d.BlockAt(line); b != nil && b.Tangled() {
		if line >= b.First() && line <= b.Last() {
			refs := d.refs(b, line)
			for _, r := range refs {
				if col >= r.Col && col < r.EndCol {
					return r.Name
				}
			}
			if len(refs) > 0 {
				return refs[0].Name
			}
		}
		return b.Chunk
	}
	for _, b := range d.Blocks {
		if b.ChunkLine == line {
			return b.Chunk
		}
	}
	return ""
}

// Rename changes a chunk's name at every definition and every reference.
func (d *Doc) Rename(from, to string) ([]Edit, error) {
	from, to = NormName(from), NormName(to)
	if to == "" {
		return nil, fmt.Errorf("new chunk name is empty")
	}
	if strings.Contains(to, ">>") || strings.Contains(to, "-->") {
		return nil, fmt.Errorf("chunk names cannot contain >> or -->")
	}
	var target *Chunk
	for _, c := range d.Chunks() {
		if c.Name == to && from != to {
			return nil, fmt.Errorf("chunk ⟨%s⟩ already exists", to)
		}
		if c.Name == from {
			target = c
		}
	}
	if target == nil {
		return nil, fmt.Errorf("no chunk named ⟨%s⟩", from)
	}
	changed := map[int]string{}
	get := func(i int) string {
		if s, ok := changed[i]; ok {
			return s
		}
		return d.Lines[i]
	}
	for _, b := range target.Blocks {
		for _, dir := range d.Directives {
			if dir.Line == b.ChunkLine {
				l := d.Lines[dir.Line]
				changed[dir.Line] = l[:dir.ValueCol] + to + l[dir.ValueCol+len(dir.Value):]
			}
		}
	}
	// Rewrite references right-to-left so earlier columns stay valid.
	for i := len(target.Refs) - 1; i >= 0; i-- {
		r := target.Refs[i]
		l := get(r.Line)
		changed[r.Line] = l[:r.Col] + r.Text(to) + l[r.EndCol:]
	}
	var edits []Edit
	for i := len(d.Lines) - 1; i >= 0; i-- {
		if s, ok := changed[i]; ok {
			edits = append(edits, Edit{Start: i, End: i + 1, Lines: []string{s}})
		}
	}
	return edits, nil
}

// Mention is a place where a chunk's name is written. Col and EndCol span
// the name itself.
type Mention struct {
	Chunk       *Chunk
	Ref         bool // in a reference, rather than in the chunk directive
	Line        int
	Col, EndCol int
}

// MentionAt finds the reference or the chunk directive at a position. A
// reference alone on its line owns the whole line.
func (d *Doc) MentionAt(line, col int) *Mention {
	if line < 0 || line >= len(d.Lines) {
		return nil
	}
	name, m := "", &Mention{Line: line}
	if b := d.BlockAt(line); b != nil {
		if !b.Tangled() || line < b.First() || line > b.Last() {
			return nil
		}
		for _, r := range d.refs(b, line) {
			if r.Inline && (col < r.Col || col >= r.EndCol) {
				continue
			}
			text := d.Lines[line][r.Col:r.EndCol]
			open, shut := strings.Index(text, "<<")+2, strings.LastIndex(text, ">>")
			inner := text[open:shut]
			m.Col = r.Col + open + len(inner) - len(strings.TrimLeft(inner, " \t"))
			m.EndCol = r.Col + shut - len(inner) + len(strings.TrimRight(inner, " \t"))
			name, m.Ref = r.Name, true
		}
	} else {
		for _, dir := range d.Directives {
			if dir.Line == line && dir.Key == "chunk" {
				name, m.Col, m.EndCol = NormName(dir.Value), dir.ValueCol, dir.ValueCol+len(dir.Value)
			}
		}
	}
	for _, c := range d.Chunks() {
		if c.Name == name {
			m.Chunk = c
			return m
		}
	}
	return nil
}

// AddImport says what to insert, and where, for a file to import one more
// package. It fails for a file without a package directive, which writes
// its own import block.
func (d *Doc) AddImport(f *File, alias, path string) (line, col int, text string, ok bool) {
	entry := strings.TrimSpace(alias + " " + path)
	if n := len(f.Imports); n > 0 {
		last := f.Imports[n-1]
		return last.Line, last.Col + last.Len, ", " + entry, true
	}
	if f.PkgDir == nil {
		return 0, 0, "", false
	}
	return f.PkgDir.Line + 1, 0, "<!-- imports: " + entry + " -->\n", true
}
