// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package lit

import (
	"fmt"
	"os"
	"strings"
	"testing"
)

const sample = "<!-- package: main -->\n<!-- imports: fmt, os -->\n<!-- tangler-exclude: ^//.*$ -->\n<!-- tangler-exclude: ^<!-- .* -->$ -->\n\n# T\n\n```go\n// dropped\nfunc main() {\n\tfor i := 0; i < 3; i++ {\n\t\t// <<body>>\n\t}\n\tfmt.Println(add(/*<<args>>*/))\n}\n```\n\n<!-- chunk: body -->\n```go\n// Print the index.\nif i > 0 {\n\tfmt.Println(i)\n}\n```\n\n<!-- chunk: args -->\n```go\n1,\n2\n```\n\n```text\nnot code\n```\n"

// program is everything a document tangles to.
func program(d *Doc) string {
	var sb strings.Builder
	for _, o := range d.Tangle().Files {
		sb.WriteString("==> " + o.Path + "\n")
		sb.Write(o.Bytes())
	}
	return sb.String()
}

func TestDirectives(t *testing.T) {
	d := Parse("x.lit.md", []byte(sample))
	if f := d.Files[0]; f.Package != "main" || len(f.Imports) != 2 || f.Imports[1].Path != "os" {
		t.Fatalf("directives: %+v", d)
	}
	if len(d.Excludes) != 2 || d.Excludes[1].String() != "^<!-- .* -->$" {
		t.Fatalf("an exclude pattern containing --> must survive: %v", d.Excludes)
	}
	if got := d.OutPath(d.Files[0]); got != "x.go" {
		t.Errorf("OutPath = %q", got)
	}
}

func TestTangleAndMap(t *testing.T) {
	d := Parse("x.lit.md", []byte(sample))
	res := d.Tangle()
	if res.HasErrors() || len(res.Files) != 1 {
		t.Fatalf("diags: %+v", res.Diags)
	}
	r := res.Files[0]
	out := string(r.Bytes())
	for _, want := range []string{"\t\tif i > 0 {\n\t\t\tfmt.Println(i)\n\t\t}\n", "\tfmt.Println(add(1,\n\t2))\n", "import (\n\t\"fmt\"\n\t\"os\"\n)"} {
		if !strings.Contains(out, want) {
			t.Errorf("output lacks %q:\n%s", want, out)
		}
	}
	if strings.Contains(out, "// dropped") {
		t.Error("tangler-exclude did not drop the top-level comment")
	}
	if strings.Contains(out, "// Print the index.") {
		t.Error("excludes apply to source lines, so a chunk's column-0 comment is dropped too")
	}
	// Every mapped position must point at identical text in the source.
	for ln, l := range r.Lines {
		for _, s := range l.Segs {
			if s.OutCol == 0 && strings.HasPrefix(l.Text, "\t\"") || strings.HasPrefix(l.Text, "package ") {
				continue // generated header lines map to directive values
			}
			got := d.Lines[s.SrcLine][s.SrcCol : s.SrcCol+s.Len]
			if want := l.Text[s.OutCol : s.OutCol+s.Len]; got != want {
				t.Errorf("out line %d: segment maps %q to %q", ln, want, got)
			}
		}
	}
	// The `2` of the inline chunk sits on a continuation line.
	for ln, l := range r.Lines {
		if l.Text == "\t2))" {
			sl, sc, via, _ := r.Map(ln, 1)
			if d.Lines[sl] != "2" || sc != 0 || len(via) != 1 {
				t.Errorf("Map = %d:%d via %v", sl, sc, via)
			}
			if sl, _, _, _ := r.Map(ln, 3); !strings.Contains(d.Lines[sl], "add(") {
				t.Errorf("text after an inline chunk belongs to the host line, got %q", d.Lines[sl])
			}
		}
	}
	if diags := res.SyntaxCheck(); len(diags) != 0 {
		t.Errorf("syntax: %+v", diags)
	}
}

func TestLocateAndExact(t *testing.T) {
	d := Parse("x.lit.md", []byte(sample))
	res := d.Tangle()
	src := 0
	for i, l := range d.Lines {
		if l == "\tfmt.Println(i)" {
			src = i
		}
	}
	o, ol, oc, ok := res.Locate(src, 5)
	if !ok || !strings.HasPrefix(o.Lines[ol].Text[oc:], "Println(i)") {
		t.Fatalf("Locate = %d:%d %v", ol, oc, ok)
	}
	if sl, sc, ok := o.Exact(ol, oc, false); !ok || sl != src || sc != 5 {
		t.Errorf("Exact should undo Locate, got %d:%d %v", sl, sc, ok)
	}
	if _, sc, ok := o.Exact(ol, len(o.Lines[ol].Text), true); !ok || sc != len(d.Lines[src]) {
		t.Errorf("the end of a range may touch the end of the line, got %d %v", sc, ok)
	}
	if _, _, ok := o.Exact(ol, 0, false); ok {
		t.Error("indentation that tangling added came from nowhere")
	}
	if _, _, ok := o.Exact(4, 0, false); ok || o.Lines[4].Text != "import (" {
		t.Errorf("neither did %q", o.Lines[4].Text)
	}
	if _, _, _, ok := res.Locate(5, 0); ok {
		t.Error("prose is not written anywhere")
	}
}

const twice = "<!-- package: main -->\n\n```go\nfunc a() {\n\t// <<step>>\n}\n\n" +
	"func b() {\n\tif true {\n\t\t// <<step>>\n\t}\n}\n```\n\n" +
	"<!-- chunk: step -->\n```go\nprintln(1)\n\nprintln(2)\n```\n"

var roundTrips = map[string]string{"sample": sample, "multi": multi, "twice": twice}

// char is one byte that tangling copied: where it was written, and where from.
type char struct {
	out               *Output
	line, col         int
	srcLine, srcCol   int
	first, segmentEnd bool // the first copy of its source; the last byte of its segment
}

// chars lists every written character of a result, in the order Locate
// searches: file by file, line by line.
func chars(res *Result) []char {
	var all []char
	seen := map[[2]int]bool{}
	for _, o := range res.Files {
		for n, l := range o.Lines {
			for _, s := range l.Segs {
				for k := 0; k < s.Len; k++ {
					src := [2]int{s.SrcLine, s.SrcCol + k}
					all = append(all, char{o, n, s.OutCol + k, src[0], src[1], !seen[src], k == s.Len-1})
					seen[src] = true
				}
			}
		}
	}
	return all
}

func TestMapUndoesLocate(t *testing.T) {
	for name, src := range roundTrips {
		res := Parse("x.lit.md", []byte(src)).Tangle()
		all := chars(res)
		if len(all) == 0 {
			t.Fatalf("%s: nothing was tangled", name)
		}
		for _, c := range all {
			o, line, col, ok := res.Locate(c.srcLine, c.srcCol)
			if !ok {
				t.Errorf("%s: Locate(%d:%d) finds nothing, but it was written at %s:%d:%d", name, c.srcLine, c.srcCol, c.out.Path, c.line, c.col)
				continue
			}
			if sl, sc, _, ok := o.Map(line, col); !ok || sl != c.srcLine || sc != c.srcCol {
				t.Errorf("%s: Map(Locate(%d:%d)) = %d:%d %v", name, c.srcLine, c.srcCol, sl, sc, ok)
			}
		}
	}
}

func TestLocateUndoesMap(t *testing.T) {
	for name, src := range roundTrips {
		res := Parse("x.lit.md", []byte(src)).Tangle()
		copies := 0
		for _, c := range chars(res) {
			sl, sc, _, ok := c.out.Map(c.line, c.col)
			if !ok || sl != c.srcLine || sc != c.srcCol {
				t.Errorf("%s: Map(%s:%d:%d) = %d:%d %v, but the segment says %d:%d", name, c.out.Path, c.line, c.col, sl, sc, ok, c.srcLine, c.srcCol)
				continue
			}
			o, line, col, ok := res.Locate(sl, sc)
			same := ok && o == c.out && line == c.line && col == c.col
			switch {
			case !ok:
				t.Errorf("%s: Locate(Map(%s:%d:%d)) finds nothing", name, c.out.Path, c.line, c.col)
			case c.first && !same:
				t.Errorf("%s: Locate(Map(%s:%d:%d)) = %s:%d:%d", name, c.out.Path, c.line, c.col, o.Path, line, col)
			case !c.first:
				copies++
				back, backCol, _, _ := o.Map(line, col)
				earlier := o == c.out && (line < c.line || line == c.line && col < c.col)
				if same || !earlier || back != sl || backCol != sc {
					t.Errorf("%s: from the later copy %d:%d, Locate(Map) = %d:%d, which is not an earlier copy of %d:%d", name, c.line, c.col, line, col, sl, sc)
				}
			}
		}
		if (copies > 0) != (name == "twice") {
			t.Errorf("%s: %d characters are later copies", name, copies)
		}
	}
}

func TestWhereTheInverseStops(t *testing.T) {
	d := Parse("x.lit.md", []byte(sample))
	res := d.Tangle()
	o := res.Files[0]

	// Generated text: Map answers with the nearest thing, so many positions
	// share one answer and Locate can return to at most one of them.
	var body int
	for n, l := range o.Lines {
		if l.Text == "\t\t\tfmt.Println(i)" {
			body = n
		}
	}
	sl, sc, _, _ := o.Map(body, 2) // the first byte of the chunk's own text
	for col := 0; col < 2; col++ { // the indentation tangling put before it
		if l, c, _, ok := o.Map(body, col); !ok || l != sl || c != sc {
			t.Errorf("Map(%d:%d) = %d:%d, want the nearest segment's start %d:%d", body, col, l, c, sl, sc)
		}
	}
	if _, line, col, _ := res.Locate(sl, sc); line != body || col != 2 {
		t.Errorf("Locate returns to the text at %d:2, not the indentation, got %d:%d", body, line, col)
	}

	// Text that isn't tangled: Locate has no answer, and Map never gives one.
	// A position has an answer if it is a tangled character or the gap
	// after one, and those are all the answers there are. Even a directive
	// is only tangled in part: its value is, the markup around it isn't.
	written := map[[2]int]bool{}
	for _, c := range chars(res) {
		written[[2]int{c.srcLine, c.srcCol}] = true
	}
	prose := 0
	for n, l := range d.Lines {
		for col := 0; col <= len(l); col++ {
			want := written[[2]int{n, col}] || written[[2]int{n, col - 1}]
			if _, _, _, ok := res.Locate(n, col); ok != want {
				t.Errorf("Locate(%d:%d) = %v in %q", n, col, ok, l)
			}
			if !want {
				prose++
			}
		}
	}
	if prose == 0 {
		t.Error("the sample has no prose to fail on")
	}

	// The end of a segment: Locate takes it, Map steps back or aside, and
	// Exact is the one that returns.
	for _, c := range chars(res) {
		if !c.segmentEnd || !c.first {
			continue
		}
		oo, line, col, ok := res.Locate(c.srcLine, c.srcCol+1)
		if !ok || oo != c.out || line != c.line || col != c.col+1 {
			t.Errorf("Locate(%d:%d), the end of a segment, = %d:%d %v", c.srcLine, c.srcCol+1, line, col, ok)
			continue
		}
		if l, cc, _, _ := oo.Map(line, col); l == c.srcLine && cc == c.srcCol+1 {
			t.Errorf("Map(%d:%d) returned to the end of a segment; the table under \"Two halves of one map\" is out of date", line, col)
		}
		if l, cc, ok := oo.Exact(line, col, true); !ok || l != c.srcLine || cc != c.srcCol+1 {
			t.Errorf("Exact(%d:%d, end) = %d:%d %v, want %d:%d", line, col, l, cc, ok, c.srcLine, c.srcCol+1)
		}
	}
}

func TestMentionsAndImports(t *testing.T) {
	d := Parse("x.lit.md", []byte(sample))
	name := func(m *Mention) string {
		if m == nil {
			return ""
		}
		return d.Lines[m.Line][m.Col:m.EndCol]
	}
	if m := d.MentionAt(11, 0); name(m) != "body" || !m.Ref {
		t.Errorf("a reference owns its line: %+v", m)
	}
	if m := d.MentionAt(13, 20); name(m) != "args" || !m.Ref {
		t.Errorf("an inline reference: %+v", m)
	}
	if m := d.MentionAt(13, 3); m != nil {
		t.Errorf("fmt is Go, not a chunk: %+v", m)
	}
	if m := d.MentionAt(17, 0); name(m) != "body" || m.Ref || len(m.Chunk.Refs) != 1 {
		t.Errorf("a chunk directive: %+v", m)
	}
	if m := d.MentionAt(21, 3); m != nil {
		t.Errorf("the inside of a chunk is Go too: %+v", m)
	}
	line, col, text, ok := d.AddImport(d.Files[0], "", "strings")
	if !ok || d.Lines[line][:col]+text != "<!-- imports: fmt, os, strings" {
		t.Errorf("AddImport = %d:%d %q", line, col, text)
	}
}

func TestProblems(t *testing.T) {
	cases := map[string]string{
		"```go\n// <<nope>>\n```\n":                                       "not defined",
		"```go\n// <<a>>\n```\n<!-- chunk: a -->\n```go\n// <<a>>\n```\n": "includes itself",
		"```go\nx\n```\n<!-- chunk: lonely -->\n```go\ny\n```\n":          "never used",
		"<!-- chunk: dangling -->\n\nprose\n":                             "not followed by a code block",
		"<!-- package: main -->\n```go\nfunc main() {\n\tx := \n}\n```\n": "",
	}
	for src, want := range cases {
		r := Parse("p.lit.md", []byte(src)).Tangle()
		diags := append(r.Diags, r.SyntaxCheck()...)
		found := false
		for _, dg := range diags {
			if want != "" && strings.Contains(dg.Message, want) {
				found = true
			}
			if want == "" && dg.Source == "syntax" && dg.Line == 4 && len(diags) == 1 {
				found = true
			}
		}
		if !found {
			t.Errorf("%q: wanted %q in %+v", src, want, diags)
		}
	}
}

func TestUntangleRoundTrip(t *testing.T) {
	d := Parse("x.lit.md", []byte(sample))
	before := program(d)
	find := func(prefix string) int {
		for i, l := range d.Lines {
			if strings.HasPrefix(strings.TrimSpace(l), prefix) {
				return i
			}
		}
		t.Fatalf("no line %q", prefix)
		return -1
	}

	// Linewise: the whole for loop.
	start := find("for i :=")
	res, err := d.Untangle(Selection{StartLine: start, EndLine: start + 2, EndCol: -1}, "")
	if err != nil {
		t.Fatal(err)
	}
	if res.Name != "loop i to 3" {
		t.Errorf("name = %q", res.Name)
	}
	lines := Apply(d.Lines, res.Edits)
	d2 := Parse("x.lit.md", []byte(strings.Join(lines, "\n")))
	if after := program(d2); after != before {
		t.Errorf("linewise untangle changed the program:\n%s\n---\n%s", before, after)
	}
	if lines[res.RefLine] != "\t// <<loop i to 3>>" || !strings.HasPrefix(lines[res.DefLine], "for i :=") {
		t.Errorf("ref %q def %q", lines[res.RefLine], lines[res.DefLine])
	}

	// Charwise: the call inside Println.
	ln := find("fmt.Println(add(")
	col := strings.Index(d.Lines[ln], "add(")
	res, err = d.Untangle(Selection{StartLine: ln, EndLine: ln, StartCol: col, EndCol: len(d.Lines[ln]) - 1}, "")
	if err != nil {
		t.Fatal(err)
	}
	if !res.Inline || res.Name != "add call" {
		t.Errorf("inline=%v name=%q", res.Inline, res.Name)
	}
	d3 := Parse("x.lit.md", []byte(strings.Join(Apply(d.Lines, res.Edits), "\n")))
	if after := program(d3); after != before {
		t.Errorf("charwise untangle changed the program:\n%s", after)
	}

	if _, err := d.Untangle(Selection{StartLine: 5, EndLine: 5, EndCol: -1}, ""); err == nil {
		t.Error("untangling prose must fail")
	}
}

func TestRename(t *testing.T) {
	d := Parse("x.lit.md", []byte(sample))
	before := program(d)
	edits, err := d.Rename("args", "the two operands")
	if err != nil {
		t.Fatal(err)
	}
	text := strings.Join(Apply(d.Lines, edits), "\n")
	if !strings.Contains(text, "add(/*<<the two operands>>*/)") || !strings.Contains(text, "<!-- chunk: the two operands -->") {
		t.Errorf("rename missed something:\n%s", text)
	}
	if after := program(Parse("x.lit.md", []byte(text))); after != before {
		t.Error("rename changed the program")
	}
	if _, err := d.Rename("args", "body"); err == nil {
		t.Error("renaming onto an existing chunk must fail")
	}
	if _, err := d.Rename("ghost", "x"); err == nil {
		t.Error("renaming a missing chunk must fail")
	}
}

func TestSuggestName(t *testing.T) {
	cases := []struct {
		code   string
		inline bool
		want   string
	}{
		{"// Feed jobs into the channel.\nfor i := 0; i < m; i++ {", false, "feed jobs into the channel"},
		{"for job := range jobs {", false, "for each job in jobs"},
		{"for _, v := range xs {", false, "for each v in xs"},
		{"for {", false, "loop forever"},
		{"if err != nil {\n\treturn err\n}", false, "handle err"},
		{"if x, ok := m[k]; ok && x > 3 {", false, "if ok && x > 3"},
		{"select {\ncase <-ctx.Done():\n\treturn\ncase job := <-jobs:", false, "select on ctx.Done(), jobs"},
		{"switch v := x.(type) {", false, "type switch on x"},
		{"defer wg.Done()", false, "defer wg.Done"},
		{"go func() {", false, "spawn goroutine"},
		{"go worker(ctx, i)", false, "spawn worker"},
		{"jobs := make(chan int, m)", false, "make jobs"},
		{"ctx, cancel := context.WithCancel(parent)", false, "ctx, cancel from context.WithCancel"},
		{"data, err := os.ReadFile(p)", false, "data from os.ReadFile"},
		{"_, err = w.Write(b)", false, "call w.Write"},
		{"wg.Wait()", false, "call wg.Wait"},
		{"results <- job * 2", false, "send to results"},
		{"func (s *Server) Serve(l net.Listener) error {", false, "func Serve"},
		{"type Job struct {", false, "type Job"},
		{"return nil, fmt.Errorf(\"x\")", false, "return nil, fmt.Errorf(\"x\")"},
		{"context.WithTimeout(ctx, time.Second)", true, "context.WithTimeout call"},
		{"&http.Server{Addr: addr}", true, "http.Server literal"},
		{"func(a, b int) bool { return a < b }", true, "func literal"},
		{"a + b*c", true, "a b c expression"},
	}
	for _, c := range cases {
		if got := SuggestName(strings.Split(c.code, "\n"), c.inline); got != c.want {
			t.Errorf("SuggestName(%q) = %q, want %q", c.code, got, c.want)
		}
	}
}

func TestAnalyzeExample(t *testing.T) {
	src, err := os.ReadFile("../../examples/worker_pool.lit.md")
	if err != nil {
		t.Skip(err)
	}
	a := Parse("worker_pool.lit.md", src).Analyze(AnalyzeOptions{})
	kinds := map[string]int{}
	for _, it := range a.Items {
		kinds[it.Kind]++
	}
	if kinds["mermaid"] != 2 || kinds["math-block"] != 1 || kinds["math"] < 6 || kinds["chunk-def"] != 7 || kinds["chunk-ref"] != 7 {
		t.Errorf("items: %v", kinds)
	}
	if len(a.Diagnostics) != 0 {
		t.Errorf("diagnostics: %+v", a.Diagnostics)
	}
}

func TestTables(t *testing.T) {
	src := "| Key | Does | Cost |\n|---|:-:|--:|\n| `\\r` | **run** it, see [docs](x) | $x^2$ |\n| a \\| b | short |\n\nnot | a table\n\n```go\n// | a | b |\n// |---|---|\n```\n"
	d := Parse("t.lit.md", []byte(src))
	var tables []Item
	for _, it := range d.Analyze(AnalyzeOptions{}).Items {
		if it.Kind == "table" {
			tables = append(tables, it)
		}
	}
	if len(tables) != 1 || tables[0].Line != 0 || tables[0].EndLine != 3 {
		t.Fatalf("tables = %+v", tables)
	}
	table := tables[0].Table
	var got []string
	for _, r := range table.Rows {
		for _, c := range r.Cells {
			got = append(got, c.Text)
		}
		got = append(got, fmt.Sprint(len(r.Hide)))
	}
	if want := `Key|Does|Cost|0|\r|run it, see docs|𝑥²|6|a | b|short|1`; strings.Join(got, "|") != want {
		t.Errorf("cells = %s, want %s", strings.Join(got, "|"), want)
	}
	if fmt.Sprint(table.Align) != "[left center right]" || len(table.Rule) != 3 {
		t.Errorf("rule = %v %v", table.Align, table.Rule)
	}
	// "| `\r` | **run** it..." : the first cell is between the pipes at 0 and 7.
	if c := table.Rows[1].Cells[0]; c != (Cell{From: 1, To: 7, Col: 2, EndCol: 6, Text: `\r`}) {
		t.Errorf("cell = %+v", c)
	}
	if h := table.Rows[1].Hide; h[0] != [2]int{2, 3} || h[1] != [2]int{5, 6} {
		t.Errorf("the backticks are hidden: %v", h)
	}
}

func TestInlineMathRules(t *testing.T) {
	d := Parse("m.lit.md", []byte("costs $5 and $10, but $x^2$ and `$y$` and \\$z\\$ and \\(a\\)\n"))
	a := d.Analyze(AnalyzeOptions{})
	var got []string
	for _, it := range a.Items {
		got = append(got, it.Text)
	}
	if strings.Join(got, "|") != "𝑥²|𝑎" {
		t.Errorf("math items = %q", got)
	}
}

const multi = "<!-- file: go.mod -->\n```gomod\nmodule example\n```\n\n" +
	"<!-- file: a/a.go -->\n<!-- package: a -->\n<!-- imports: strings, example.com/z, fmt -->\n```go\nfunc A() { fmt.Println(\"a\") }\n```\n\n" +
	"```lua\n-- ignored: not the language of a.go\n```\n\n" +
	"<!-- file: p/init.lua -->\n```lua\nlocal M = {}\n-- <<body>>\nreturn M\n```\n\n" +
	"<!-- chunk: body -->\n```lua\nM.x = f(--[[<<arg>>]])\n```\n\n<!-- chunk: arg -->\n```lua\n42\n```\n\n" +
	"<!-- file: a/a_test.go -->\n<!-- package: a -->\n<!-- verbatim -->\n```go\nconst s = \"f(/*<<not a ref>>*/)\"\n// <<nor this>>\n```\n"

func TestFilesLanguagesVerbatim(t *testing.T) {
	d := Parse("/m/doc.lit.md", []byte(multi))
	res := d.Tangle()
	if len(res.Diags) != 0 {
		t.Fatalf("diags: %+v", res.Diags)
	}
	got := map[string]string{}
	for _, o := range res.Files {
		got[o.Path] = string(o.Bytes())
	}
	want := map[string]string{
		"/m/go.mod":      "// Code generated by litgo from doc.lit.md; DO NOT EDIT.\n\nmodule example\n",
		"/m/a/a.go":      "// Code generated by litgo from doc.lit.md; DO NOT EDIT.\n\npackage a\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n\n\t\"example.com/z\"\n)\n\nfunc A() { fmt.Println(\"a\") }\n",
		"/m/p/init.lua":  "-- Code generated by litgo from doc.lit.md; DO NOT EDIT.\n\nlocal M = {}\nM.x = f(42)\nreturn M\n",
		"/m/a/a_test.go": "// Code generated by litgo from doc.lit.md; DO NOT EDIT.\n\npackage a\n\nconst s = \"f(/*<<not a ref>>*/)\"\n// <<nor this>>\n",
	}
	if len(got) != len(want) {
		t.Errorf("files: %v", got)
	}
	for p, w := range want {
		if got[p] != w {
			t.Errorf("%s:\n%q\nwant\n%q", p, got[p], w)
		}
	}
	for _, o := range res.Files {
		if !Generated(o.Bytes()) {
			t.Errorf("%s lacks the generated marker", o.Path)
		}
	}

	// Untangling Lua leaves a Lua comment and a lua chunk.
	ln := 0
	for i, l := range d.Lines {
		if l == "local M = {}" {
			ln = i
		}
	}
	u, err := d.Untangle(Selection{StartLine: ln, EndLine: ln, EndCol: -1}, "")
	if err != nil {
		t.Fatal(err)
	}
	lines := Apply(d.Lines, u.Edits)
	if lines[ln] != "-- <<define M>>" || lines[len(lines)-3] != "```lua" {
		t.Errorf("ref %q, fence %q", lines[ln], lines[len(lines)-3])
	}
	edits, err := d.Rename("arg", "the answer")
	if err != nil {
		t.Fatal(err)
	}
	if text := strings.Join(Apply(d.Lines, edits), "\n"); !strings.Contains(text, "f(--[[<<the answer>>]])") {
		t.Errorf("rename lost the Lua comment syntax:\n%s", text)
	}
}
