// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package lit

import (
	"regexp"
	"strings"
	"unicode"
)

// SuggestName proposes a chunk name for extracted code. A leading comment is
// the author's own summary, so it wins; otherwise the first statement's shape
// decides. Names read as short phrases: they label intent in the host block.
func SuggestName(code []string, inline bool) string {
	var lines []string
	for _, l := range code {
		if t := strings.TrimSpace(l); t != "" {
			lines = append(lines, t)
		}
	}
	if len(lines) == 0 {
		return "chunk"
	}
	if !inline {
		if n := fromComment(lines); n != "" {
			return clip(n)
		}
	}
	for _, l := range lines {
		if _, ok := commentText(l); ok {
			continue
		}
		var n string
		if inline {
			n = fromExpr(l)
		} else {
			n = fromStmt(l, lines)
		}
		if n != "" {
			return clip(n)
		}
		break
	}
	if inline {
		return "expression"
	}
	return "chunk"
}

// commentText returns the words of a line comment in any of the comment
// syntaxes litgo knows.
func commentText(l string) (string, bool) {
	for _, leader := range []string{"//", "--", "#"} {
		if strings.HasPrefix(l, leader) && !strings.HasPrefix(l, "--[[") && !strings.HasPrefix(l, "#!") {
			return strings.TrimSpace(strings.TrimLeft(l, leader)), true
		}
	}
	return "", false
}

func fromComment(lines []string) string {
	text, ok := commentText(lines[0])
	if !ok || RefLineRe.MatchString(lines[0]) {
		return ""
	}
	if i := strings.IndexAny(text, ".;:!?"); i > 0 {
		text = text[:i]
	}
	words := strings.Fields(text)
	if len(words) == 0 || len(text) < 3 {
		return ""
	}
	if len(words) > 7 {
		words = words[:7]
	}
	// Lower-case a sentence-style first word, but leave identifiers
	// (HTTPServer, wg) alone.
	if w := []rune(words[0]); len(w) > 1 && unicode.IsUpper(w[0]) && unicode.IsLower(w[1]) && strings.ToLower(words[0][1:]) == words[0][1:] {
		w[0] = unicode.ToLower(w[0])
		words[0] = string(w)
	}
	return strings.Trim(strings.Join(words, " "), " ,-")
}

var (
	forRangeRe = regexp.MustCompile(`^for\s+(?:(.+?)\s*:?=\s*)?range\s+(.+?)\s*\{?$`)
	forCountRe = regexp.MustCompile(`^for\s+(\w+)\s*:=[^;]*;\s*\w+\s*[<>!]=?\s*([^;]+?)\s*;`)
	forCondRe  = regexp.MustCompile(`^for\s+(.+?)\s*\{?$`)
	ifRe       = regexp.MustCompile(`^if\s+(?:.*;\s*)?(.+?)\s*\{?$`)
	switchRe   = regexp.MustCompile(`^switch\s+(?:.*;\s*)?(.*?)\s*\{?$`)
	caseRecvRe = regexp.MustCompile(`^case\s+.*<-\s*([\w.]+(?:\(\))?)`)
	caseSendRe = regexp.MustCompile(`^case\s+([\w.]+)\s*<-`)
	funcRe     = regexp.MustCompile(`^func\s+(?:\([^)]*\)\s*)?(\w+)`)
	luaFuncRe  = regexp.MustCompile(`^(?:local\s+)?function\s+([\w.:]+)`)
	luaLocalRe = regexp.MustCompile(`^local\s+([\w, ]+?)\s*=`)
	declRe     = regexp.MustCompile(`^(type|var|const)\s+(\w+)`)
	assignRe   = regexp.MustCompile(`^([\w.\[\]*, ]+?)\s*(:=|=|\+=|-=)\s*(.+)$`)
	calleeRe   = regexp.MustCompile(`^&?\*?((?:[A-Za-z_][\w]*\.)*[A-Za-z_]\w*)\s*[({\[]`)
	sendRe     = regexp.MustCompile(`^([\w.]+)\s*<-\s*\S`)
	recvRe     = regexp.MustCompile(`^<-\s*([\w.]+)`)
)

func fromStmt(l string, all []string) string {
	switch {
	case strings.HasPrefix(l, "for"):
		if l == "for {" || l == "for" {
			return "loop forever"
		}
		if m := forRangeRe.FindStringSubmatch(l); m != nil {
			vars := strings.Split(m[1], ",")
			v := strings.TrimSpace(vars[len(vars)-1])
			if v == "" || v == "_" {
				return "loop over " + m[2]
			}
			return "for each " + v + " in " + m[2]
		}
		if m := forCountRe.FindStringSubmatch(l); m != nil {
			return "loop " + m[1] + " to " + m[2]
		}
		if m := forCondRe.FindStringSubmatch(l); m != nil {
			return "loop while " + m[1]
		}
	case strings.HasPrefix(l, "if "):
		if m := ifRe.FindStringSubmatch(l); m != nil {
			cond := m[1]
			if em := regexp.MustCompile(`^(\w*[eE]rr\w*)\s*!=\s*nil$`).FindStringSubmatch(cond); em != nil {
				return "handle " + em[1]
			}
			return "if " + cond
		}
	case strings.HasPrefix(l, "select"):
		var chans []string
		for _, c := range all {
			if m := caseRecvRe.FindStringSubmatch(c); m != nil {
				chans = append(chans, m[1])
			} else if m := caseSendRe.FindStringSubmatch(c); m != nil {
				chans = append(chans, m[1])
			}
		}
		if len(chans) > 3 {
			chans = chans[:3]
		}
		if len(chans) > 0 {
			return "select on " + strings.Join(chans, ", ")
		}
		return "select"
	case strings.HasPrefix(l, "switch"):
		if m := switchRe.FindStringSubmatch(l); m != nil && m[1] != "" {
			if subject, ok := strings.CutSuffix(m[1], ".(type)"); ok {
				if _, after, found := strings.Cut(subject, ":="); found {
					subject = after
				}
				return "type switch on " + strings.TrimSpace(subject)
			}
			return "switch on " + m[1]
		}
		return "switch"
	case strings.HasPrefix(l, "defer "):
		rest := strings.TrimPrefix(l, "defer ")
		if strings.HasPrefix(rest, "func") {
			return "deferred cleanup"
		}
		if m := calleeRe.FindStringSubmatch(rest); m != nil {
			return "defer " + m[1]
		}
	case strings.HasPrefix(l, "go "):
		rest := strings.TrimPrefix(l, "go ")
		if strings.HasPrefix(rest, "func") {
			return "spawn goroutine"
		}
		if m := calleeRe.FindStringSubmatch(rest); m != nil {
			return "spawn " + m[1]
		}
	case strings.HasPrefix(l, "return"):
		rest := strings.TrimSpace(strings.TrimPrefix(l, "return"))
		if rest == "" {
			return "return"
		}
		return "return " + rest
	case strings.HasPrefix(l, "func"):
		if m := funcRe.FindStringSubmatch(l); m != nil {
			return "func " + m[1]
		}
	}
	if m := declRe.FindStringSubmatch(l); m != nil {
		return m[1] + " " + m[2]
	}
	if m := luaFuncRe.FindStringSubmatch(l); m != nil {
		return "function " + m[1]
	}
	if m := luaLocalRe.FindStringSubmatch(l); m != nil {
		return "define " + m[1]
	}
	if m := sendRe.FindStringSubmatch(l); m != nil {
		return "send to " + m[1]
	}
	if m := recvRe.FindStringSubmatch(l); m != nil {
		return "receive from " + m[1]
	}
	if m := assignRe.FindStringSubmatch(l); m != nil {
		var names []string
		for _, n := range strings.Split(m[1], ",") {
			n = strings.TrimSpace(n)
			if n != "_" && n != "err" && n != "ok" && n != "" {
				names = append(names, n)
			}
		}
		rhs := strings.TrimSpace(m[3])
		callee := ""
		if cm := calleeRe.FindStringSubmatch(rhs); cm != nil {
			callee = cm[1]
		}
		switch {
		case len(names) == 0 && callee != "":
			return "call " + callee
		case len(names) == 0:
			return "assign " + strings.TrimSpace(m[1])
		case callee == "make" || callee == "new":
			return callee + " " + strings.Join(names, ", ")
		case strings.HasPrefix(rhs, "func"):
			return "define " + strings.Join(names, ", ")
		case callee != "":
			return strings.Join(names, ", ") + " from " + callee
		case m[2] == ":=":
			return "define " + strings.Join(names, ", ")
		default:
			return "set " + strings.Join(names, ", ")
		}
	}
	if m := calleeRe.FindStringSubmatch(l); m != nil {
		return "call " + m[1]
	}
	return ""
}

func fromExpr(l string) string {
	switch {
	case strings.HasPrefix(l, "func"):
		return "func literal"
	case strings.HasPrefix(l, `"`) || strings.HasPrefix(l, "`"):
		return "string literal"
	}
	if m := calleeRe.FindStringSubmatch(l); m != nil {
		open := l[len(m[0])-1]
		switch {
		case open == '{':
			return m[1] + " literal"
		case open == '[':
			return m[1] + " element"
		case strings.HasSuffix(l, ")") && strings.Count(l, "(") == strings.Count(l, ")"):
			return m[1] + " call"
		}
		return m[1] + " expression"
	}
	if words := regexp.MustCompile(`[A-Za-z_][\w.]*`).FindAllString(l, 3); len(words) > 0 {
		return strings.Join(words, " ") + " expression"
	}
	return ""
}

// clip keeps names short and free of characters that would break the
// reference syntax or the HTML comment that carries the definition.
func clip(s string) string {
	s = strings.NewReplacer(">>", "> >", "<<", "< <", "-->", "->", "*/", "* /").Replace(s)
	s = strings.TrimRight(NormName(s), " {(")
	const limit = 48
	if r := []rune(s); len(r) > limit {
		s = string(r[:limit])
		if cut := strings.LastIndex(s, " "); cut > len(s)/2 {
			s = s[:cut]
		}
		s = strings.TrimRight(s, " ,.(&|") + "…"
	}
	return s
}
