// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package lit

import (
	"fmt"
	"go/parser"
	"go/scanner"
	"go/token"
	"path/filepath"
	"sort"
	"strings"
)

// Seg says that Len bytes of an output line starting at OutCol came from
// (SrcLine, SrcCol) of the literate source. Via lists the reference lines the
// text was interpolated through, outermost first.
type Seg struct {
	OutCol, Len     int
	SrcLine, SrcCol int
	Via             []int
}

// OutLine is one line of tangled output.
type OutLine struct {
	Text string
	Segs []Seg
}

// Output is one tangled file. Its first Header lines are the ones litgo
// generates: the marker, the package clause, the imports.
type Output struct {
	File   *File
	Path   string
	Lines  []OutLine
	Header int
}

// Result of tangling one document.
type Result struct {
	Doc   *Doc
	Files []*Output
	Diags []Diag
}

// generatedMarker is the text of the first line of every file litgo writes,
// after the comment leader; tangle refuses to overwrite files that lack it.
const generatedMarker = " Code generated by litgo from "

// Generated reports whether file content starts with litgo's marker.
func Generated(content []byte) bool {
	first, _, _ := strings.Cut(string(content), "\n")
	for _, leader := range []string{"//", "--", "#"} {
		if strings.HasPrefix(first, leader+generatedMarker) {
			return true
		}
	}
	return false
}

// Tangle expands the document into its output files.
func (d *Doc) Tangle() *Result {
	r := &Result{Doc: d}
	r.Diags = append(r.Diags, d.Diags...)
	t := &tangler{d: d, r: r, chunks: map[string]*Chunk{}, reported: map[string]bool{}}
	for _, c := range d.Chunks() {
		t.chunks[c.Name] = c
	}

	for _, f := range d.Files {
		var body []OutLine
		roots := 0
		for _, b := range d.Blocks {
			if b.File != f || !b.IsRoot() {
				continue
			}
			roots++
			lines := t.block(b, nil, nil)
			if len(lines) == 0 {
				continue
			}
			if len(body) > 0 {
				body = append(body, OutLine{})
			}
			body = append(body, lines...)
		}
		if roots == 0 {
			if f.Line >= 0 {
				r.Diags = append(r.Diags, Diag{Line: f.Line, Severity: SevWarning, Source: "litgo",
					Message: fmt.Sprintf("no unnamed ```%s blocks follow: %s would be empty", f.Lang, f.Path)})
			}
			continue
		}
		out := &Output{File: f, Path: d.OutPath(f), Lines: d.header(f)}
		out.Header = len(out.Lines)
		if len(out.Lines) > 0 && len(body) > 0 {
			out.Lines = append(out.Lines, OutLine{})
		}
		out.Lines = append(out.Lines, body...)
		r.Files = append(r.Files, out)
	}
	if len(r.Files) == 0 {
		r.Diags = append(r.Diags, Diag{Line: 0, Severity: SevWarning, Source: "litgo",
			Message: fmt.Sprintf("no unnamed ```%s blocks: nothing to tangle (chunks are only emitted where referenced)", d.Files[0].Lang)})
	}
	for _, c := range d.Chunks() {
		if len(c.Blocks) > 0 && len(c.Refs) == 0 {
			r.Diags = append(r.Diags, Diag{Line: c.Blocks[0].ChunkLine, Severity: SevWarning, Source: "litgo",
				Message: fmt.Sprintf("chunk ⟨%s⟩ is never used", c.Name)})
		}
	}
	for i := range r.Diags {
		if r.Diags[i].File == "" {
			r.Diags[i].File = d.Path
		}
	}
	return r
}

// header is what litgo writes before the blocks: the generated-code marker
// and, for a file with a package directive, the package clause and imports.
// Header lines map to the directives they came from, so an unused import is
// reported on its entry in the imports directive.
func (d *Doc) header(f *File) []OutLine {
	var h []OutLine
	if leader := CommentsFor(f.Lang).Line; leader != "" {
		h = append(h, OutLine{Text: leader + generatedMarker + filepath.Base(d.Path) + "; DO NOT EDIT."})
	}
	if f.Package == "" {
		return h
	}
	h = append(h, OutLine{}, OutLine{Text: "package " + f.Package,
		Segs: []Seg{{OutCol: 8, Len: len(f.Package), SrcLine: f.PkgDir.Line, SrcCol: f.PkgDir.ValueCol}}})
	if len(f.Imports) > 0 {
		h = append(h, OutLine{}, OutLine{Text: "import ("})
		external := func(imp Import) bool { return strings.Contains(strings.Split(imp.Path, "/")[0], ".") }
		imports := append([]Import{}, f.Imports...)
		sort.SliceStable(imports, func(i, j int) bool {
			if a, b := external(imports[i]), external(imports[j]); a != b {
				return b
			}
			return imports[i].Path < imports[j].Path
		})
		for i, imp := range imports {
			if i > 0 && external(imp) && !external(imports[i-1]) {
				h = append(h, OutLine{})
			}
			text := "\t"
			if imp.Alias != "" {
				text += imp.Alias + " "
			}
			text += `"` + imp.Path + `"`
			// The path between the quotes is the path in the directive.
			h = append(h, OutLine{Text: text, Segs: []Seg{{OutCol: len(text) - 1 - len(imp.Path), Len: len(imp.Path),
				SrcLine: imp.Line, SrcCol: imp.Col + strings.LastIndex(d.Lines[imp.Line][imp.Col:imp.Col+imp.Len], imp.Path)}}})
		}
		h = append(h, OutLine{Text: ")"})
	}
	return h
}

type tangler struct {
	d        *Doc
	r        *Result
	chunks   map[string]*Chunk
	reported map[string]bool
}

func (t *tangler) errorAt(ref Ref, msg string) {
	key := fmt.Sprintf("%d:%d:%s", ref.Line, ref.Col, msg)
	if t.reported[key] {
		return
	}
	t.reported[key] = true
	t.r.Diags = append(t.r.Diags, Diag{Line: ref.Line, Col: ref.Col, EndCol: ref.EndCol, Severity: SevError, Message: msg, Source: "litgo"})
}

func (t *tangler) excluded(line string) bool {
	for _, re := range t.d.Excludes {
		if re.MatchString(line) {
			return true
		}
	}
	return false
}

// expand returns the lines of a named chunk.
func (t *tangler) expand(ref Ref, stack []string, via []int) []OutLine {
	for _, s := range stack {
		if s == ref.Name {
			t.errorAt(ref, fmt.Sprintf("chunk ⟨%s⟩ includes itself: %s → %s", ref.Name, strings.Join(stack, " → "), ref.Name))
			return nil
		}
	}
	c := t.chunks[ref.Name]
	if c == nil || len(c.Blocks) == 0 {
		t.errorAt(ref, fmt.Sprintf("chunk ⟨%s⟩ is not defined", ref.Name))
		return nil
	}
	stack = append(append([]string{}, stack...), ref.Name)
	via = append(append([]int{}, via...), ref.Line)
	var out []OutLine
	for _, b := range c.Blocks {
		out = append(out, t.block(b, stack, via)...)
	}
	return out
}

func (t *tangler) block(b *Block, stack []string, via []int) []OutLine {
	var out []OutLine
	for i := b.First(); i <= b.Last(); i++ {
		raw := t.d.Lines[i]
		strip := 0
		for strip < b.Strip && strip < len(raw) && (raw[strip] == ' ' || raw[strip] == '\t') {
			strip++
		}
		line := raw[strip:]
		refs := t.d.refs(b, i)
		if len(refs) == 1 && !refs[0].Inline {
			indent := refs[0].Indent[min(strip, len(refs[0].Indent)):]
			for _, sub := range t.expand(refs[0], stack, via) {
				out = append(out, indentLine(sub, indent))
			}
			continue
		}
		if t.excluded(line) {
			continue
		}
		if len(refs) == 0 {
			ol := OutLine{Text: line}
			if line != "" {
				ol.Segs = []Seg{{OutCol: 0, Len: len(line), SrcLine: i, SrcCol: strip, Via: via}}
			}
			out = append(out, ol)
			continue
		}
		out = append(out, t.inline(raw, strip, i, refs, stack, via)...)
	}
	return out
}

// inline splices chunks into the middle of a host line. Continuation lines of
// a multi-line chunk inherit the host line's indentation.
func (t *tangler) inline(raw string, strip, lineNo int, refs []Ref, stack []string, via []int) []OutLine {
	hostIndent := raw[strip : len(raw)-len(strings.TrimLeft(raw[strip:], " \t"))]
	cur := OutLine{}
	var out []OutLine
	lit := func(from, to int) {
		if to > from {
			cur.Segs = append(cur.Segs, Seg{OutCol: len(cur.Text), Len: to - from, SrcLine: lineNo, SrcCol: from, Via: via})
			cur.Text += raw[from:to]
		}
	}
	pos := strip
	for _, ref := range refs {
		lit(pos, ref.Col)
		pos = ref.EndCol
		for k, sub := range t.expand(ref, stack, via) {
			if k > 0 {
				out = append(out, cur)
				cur = OutLine{}
				if sub.Text != "" {
					cur.Text = hostIndent
				}
			}
			shift := len(cur.Text)
			for _, s := range sub.Segs {
				s.OutCol += shift
				cur.Segs = append(cur.Segs, s)
			}
			cur.Text += sub.Text
		}
	}
	lit(pos, len(raw))
	return append(out, cur)
}

func indentLine(l OutLine, indent string) OutLine {
	if l.Text == "" || indent == "" {
		return l
	}
	segs := make([]Seg, len(l.Segs))
	for i, s := range l.Segs {
		s.OutCol += len(indent)
		segs[i] = s
	}
	return OutLine{Text: indent + l.Text, Segs: segs}
}

// Bytes renders the tangled file.
func (o *Output) Bytes() []byte {
	var sb strings.Builder
	for _, l := range o.Lines {
		sb.WriteString(l.Text)
		sb.WriteByte('\n')
	}
	return []byte(sb.String())
}

// HasErrors reports whether tangling itself failed.
func (r *Result) HasErrors() bool {
	for _, d := range r.Diags {
		if d.Severity == SevError {
			return true
		}
	}
	return false
}

// Map translates a 0-based output position to the literate source. If the
// exact column is not covered, the nearest segment on the line is used; if
// the line is generated, the nearest mapped line above it.
func (o *Output) Map(line, col int) (srcLine, srcCol int, via []int, ok bool) {
	if line < 0 || line >= len(o.Lines) {
		return 0, 0, nil, false
	}
	for l := line; l >= 0; l-- {
		segs := o.Lines[l].Segs
		if len(segs) == 0 {
			continue
		}
		if l != line {
			s := segs[0]
			return s.SrcLine, s.SrcCol, s.Via, true
		}
		best := segs[0]
		for _, s := range segs {
			if col >= s.OutCol && col < s.OutCol+s.Len {
				return s.SrcLine, s.src(col), s.Via, true
			}
			if s.OutCol <= col {
				best = s
			}
		}
		if col >= best.OutCol+best.Len {
			return best.SrcLine, best.SrcCol + max(best.Len-1, 0), best.Via, true
		}
		return best.SrcLine, best.SrcCol, best.Via, true
	}
	return 0, 0, nil, false
}

// SyntaxCheck parses the tangled Go files and reports syntax errors at their
// literate positions. It is fast enough to run on every edit.
func (r *Result) SyntaxCheck() []Diag {
	if r.HasErrors() {
		return nil
	}
	var out []Diag
	seen := map[int]bool{} // the parser cascades; the first error on a line is the real one
	for _, o := range r.Files {
		if o.File.Lang != "go" {
			continue
		}
		fset := token.NewFileSet()
		_, err := parser.ParseFile(fset, o.Path, o.Bytes(), parser.AllErrors|parser.SkipObjectResolution)
		list, _ := err.(scanner.ErrorList)
		for _, e := range list {
			line, col, _, ok := o.Map(e.Pos.Line-1, e.Pos.Column-1)
			if !ok || seen[line] {
				continue
			}
			seen[line] = true
			out = append(out, Diag{File: r.Doc.Path, Line: line, Col: col, Severity: SevError, Message: e.Msg, Source: "syntax"})
			if len(out) >= 20 {
				return out
			}
		}
	}
	return out
}

// Locate translates a position in the literate source to the first place
// tangling wrote it.
func (r *Result) Locate(line, col int) (o *Output, outLine, outCol int, ok bool) {
	for _, o := range r.Files {
		for n, l := range o.Lines {
			for _, s := range l.Segs {
				if s.SrcLine == line && col >= s.SrcCol && col <= s.SrcCol+s.Len {
					return o, n, s.out(col), true
				}
			}
		}
	}
	return nil, 0, 0, false
}

// Exact is Map for the ends of an edit: it fails rather than approximate.
// The end of a range prefers the segment it closes, the start the one it opens.
func (o *Output) Exact(line, col int, end bool) (srcLine, srcCol int, ok bool) {
	if line < 0 || line >= len(o.Lines) {
		return 0, 0, false
	}
	for _, closing := range []bool{end, !end} {
		for _, s := range o.Lines[line].Segs {
			lo, hi := s.OutCol, s.OutCol+s.Len-1
			if closing {
				lo, hi = lo+1, hi+1
			}
			if col >= lo && col <= hi {
				return s.SrcLine, s.src(col), true
			}
		}
	}
	return 0, 0, false
}

// out is where the byte at column col of the source line went in the output.
//
// @ Requires s.SrcCol <= col ^ col <= s.SrcCol + s.Len
func (s Seg) out(col int) (c int) { return s.OutCol + col - s.SrcCol }

//@ Ensures s.OutCol <= c ^ c <= s.OutCol + s.Len
//@ Ensures s.src(c) = col

// src is where the byte at column col of the output line came from.
//
// @ Requires s.OutCol <= col ^ col <= s.OutCol + s.Len
func (s Seg) src(col int) (c int) { return s.SrcCol + col - s.OutCol }

//@ Ensures s.SrcCol <= c ^ c <= s.SrcCol + s.Len
//@ Ensures s.out(c) = col
