// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package mermaid

import (
	"strings"
)

// Direction bits of the line strokes leaving a cell.
const (
	up = 1 << iota
	down
	left
	right
)

type lineStyle int

const (
	solid lineStyle = iota
	dotted
	thick
	rounded
	double
)

type cell struct {
	bits  int
	style lineStyle
	r     rune // explicit content; wins over strokes
}

// canvas is a growable character grid. Lines are recorded as strokes so
// crossings and junctions resolve to the right box-drawing character.
type canvas struct {
	cells [][]cell
	w, h  int
}

func (c *canvas) grow(x, y int) {
	for y >= len(c.cells) {
		c.cells = append(c.cells, nil)
	}
	for x >= len(c.cells[y]) {
		c.cells[y] = append(c.cells[y], cell{})
	}
	c.w, c.h = max(c.w, x+1), max(c.h, y+1)
}

func (c *canvas) at(x, y int) *cell {
	if x < 0 || y < 0 {
		return &cell{}
	}
	c.grow(x, y)
	return &c.cells[y][x]
}

func (c *canvas) put(x, y int, r rune) { c.at(x, y).r = r }

func (c *canvas) write(x, y int, s string) {
	for _, r := range s {
		c.put(x, y, r)
		x++
	}
}

// stroke draws a straight line between two cells in the same row or column.
func (c *canvas) stroke(x1, y1, x2, y2 int, st lineStyle) {
	dx, dy := sign(x2-x1), sign(y2-y1)
	if dx != 0 && dy != 0 {
		return
	}
	for x, y := x1, y1; x != x2 || y != y2; x, y = x+dx, y+dy {
		// Grow first: at() hands out pointers that a later grow would orphan.
		c.grow(max(x, x+dx, 0), max(y, y+dy, 0))
		a, b := c.at(x, y), c.at(x+dx, y+dy)
		// The first stroke through a cell decides its style; where styles
		// meet, the glyph lookup falls back to plain junctions.
		for _, p := range []*cell{a, b} {
			if p.bits == 0 {
				p.style = st
			}
		}
		switch {
		case dx > 0:
			a.bits |= right
			b.bits |= left
		case dx < 0:
			a.bits |= left
			b.bits |= right
		case dy > 0:
			a.bits |= down
			b.bits |= up
		default:
			a.bits |= up
			b.bits |= down
		}
	}
}

// rect outlines a box.
func (c *canvas) rect(x, y, w, h int, st lineStyle) {
	c.stroke(x, y, x+w-1, y, st)
	c.stroke(x+w-1, y, x+w-1, y+h-1, st)
	c.stroke(x+w-1, y+h-1, x, y+h-1, st)
	c.stroke(x, y+h-1, x, y, st)
}

func sign(n int) int {
	switch {
	case n > 0:
		return 1
	case n < 0:
		return -1
	}
	return 0
}

var glyphs = map[int]rune{
	up: '│', down: '│', up | down: '│', left: '─', right: '─', left | right: '─',
	down | right: '┌', down | left: '┐', up | right: '└', up | left: '┘',
	up | down | right: '├', up | down | left: '┤', left | right | down: '┬', left | right | up: '┴',
	up | down | left | right: '┼',
}

var styled = map[lineStyle]map[int]rune{
	dotted:  {up | down: '┆', up: '┆', down: '┆', left | right: '┄', left: '┄', right: '┄'},
	thick:   {up | down: '┃', up: '┃', down: '┃', left | right: '━', left: '━', right: '━', down | right: '┏', down | left: '┓', up | right: '┗', up | left: '┛'},
	rounded: {down | right: '╭', down | left: '╮', up | right: '╰', up | left: '╯'},
	double:  {up | down: '║', left | right: '═', down | right: '╔', down | left: '╗', up | right: '╚', up | left: '╝'},
}

func (c *canvas) lines() []string {
	out := make([]string, 0, c.h)
	for _, row := range c.cells {
		var sb strings.Builder
		for _, cl := range row {
			switch {
			case cl.r != 0:
				sb.WriteRune(cl.r)
			case cl.bits != 0:
				if g, ok := styled[cl.style][cl.bits]; ok {
					sb.WriteRune(g)
				} else {
					sb.WriteRune(glyphs[cl.bits])
				}
			default:
				sb.WriteByte(' ')
			}
		}
		out = append(out, strings.TrimRight(sb.String(), " "))
	}
	for len(out) > 0 && out[len(out)-1] == "" {
		out = out[:len(out)-1]
	}
	return out
}
