// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package mermaid

import (
	"unicode/utf8"
)

// pt converts layout coordinates (rank axis, order axis) to canvas x, y.
func (l *layout) pt(r, o int) (x, y int) {
	if l.mirror {
		r = l.totalR - 1 - r
	}
	if l.vertical {
		return o, r
	}
	return r, o
}

func (l *layout) stroke(c *canvas, r1, o1, r2, o2 int, st lineStyle) {
	x1, y1 := l.pt(r1, o1)
	x2, y2 := l.pt(r2, o2)
	c.stroke(x1, y1, x2, y2, st)
}

// arrow picks the head glyph for travel from (r1,o1) toward (r2,o2).
func (l *layout) arrow(kind rune, r1, o1, r2, o2 int) rune {
	switch kind {
	case 'x':
		return '×'
	case 'o':
		return '○'
	}
	x1, y1 := l.pt(r1, o1)
	x2, y2 := l.pt(r2, o2)
	switch {
	case x2 > x1:
		return '▶'
	case x2 < x1:
		return '◀'
	case y2 < y1:
		return '▲'
	}
	return '▼'
}

func (l *layout) draw() []string {
	c := &canvas{}
	type labelAt struct {
		x, y int
		s    string
	}
	var labels []labelAt
	var heads []labelAt

	for g, segs := range l.segs {
		for _, s := range segs {
			e := s.edge
			o1, o2 := l.portFrom(s), l.portTo(s)
			start := s.from.posR + s.from.sizeR - 1
			track := l.trackPos(g, s)
			end := s.to.posR // the target's border (or the dummy's first cell)

			// An arrowhead sits just outside the box it points at; the line
			// stops there. Open ends run on into the border.
			headAtEnd := s.last && !e.reversed && e.head != 0 || s.last && e.reversed && e.tailHead
			headAtStart := s.first && e.reversed && e.head != 0 || s.first && !e.reversed && e.tailHead
			if s.to.shape == shapeBare && !s.to.dummy {
				headAtEnd = false
				end--
			}
			stop := end
			if headAtEnd {
				stop = end - 1
			}
			l.stroke(c, start, o1, track, o1, e.style)
			l.stroke(c, track, o1, track, o2, e.style)
			l.stroke(c, track, o2, stop, o2, e.style)

			if headAtEnd {
				kind := e.head
				if e.reversed {
					kind = '>'
				}
				x, y := l.pt(stop, o2)
				heads = append(heads, labelAt{x, y, string(l.arrow(kind, track, o2, end, o2))})
			}
			if headAtStart {
				kind := e.head
				if !e.reversed {
					kind = '>'
				}
				x, y := l.pt(start+1, o1)
				heads = append(heads, labelAt{x, y, string(l.arrow(kind, track, o1, start, o1))})
			}
			if s.last && e.label != "" {
				n := utf8.RuneCountInString(e.label)
				if l.vertical {
					x, y := l.pt(end-2, o2)
					if e.reversed && o2 < s.to.centerO() {
						labels = append(labels, labelAt{x - 1 - n, y, e.label})
					} else if e.reversed {
						labels = append(labels, labelAt{x + 2, y, e.label})
					} else {
						labels = append(labels, labelAt{x - n/2, y, e.label})
					}
				} else {
					zone := l.gapLabel[g]
					r := end - 1 - zone + (zone-n)/2
					if l.mirror {
						r += n - 1
					}
					x, y := l.pt(r, o2)
					labels = append(labels, labelAt{x, y, e.label})
				}
			}
		}
	}

	for _, rank := range l.ranks {
		for _, n := range rank {
			x1, y1 := l.pt(n.posR, n.posO)
			x2, y2 := l.pt(n.posR+n.sizeR-1, n.posO+n.sizeO-1)
			x, y := min(x1, x2), min(y1, y2)
			w, h := abs(x2-x1)+1, abs(y2-y1)+1
			if n.dummy {
				l.stroke(c, n.posR, n.centerO(), n.posR+n.sizeR-1, n.centerO(), solid)
				continue
			}
			if n.shape == shapeBare {
				c.write(x, y, n.label[0])
				continue
			}
			// Blank the interior so nothing shows through the box.
			for yy := y + 1; yy < y+h-1; yy++ {
				for xx := x + 1; xx < x+w-1; xx++ {
					*c.at(xx, yy) = cell{r: ' '}
				}
			}
			st := map[shape]lineStyle{shapeRound: rounded, shapeDouble: double}[n.shape]
			c.rect(x, y, w, h, st)
			if n.shape == shapeDiamond {
				for _, p := range [][2]int{{x, y}, {x + w - 1, y}, {x, y + h - 1}, {x + w - 1, y + h - 1}} {
					c.put(p[0], p[1], '◆')
				}
			}
			for i, s := range n.label {
				c.write(x+(w-utf8.RuneCountInString(s))/2, y+1+i, s)
			}
		}
	}
	for _, h := range heads {
		c.write(h.x, h.y, h.s)
	}
	for _, lb := range labels {
		c.write(lb.x, lb.y, lb.s)
	}
	return c.lines()
}

func abs(n int) int {
	if n < 0 {
		return -n
	}
	return n
}
