// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package mermaid

import (
	"sort"
	"unicode/utf8"
)

// seg is one rank-to-rank hop of an edge; long edges become chains of
// segments through dummy nodes.
type seg struct {
	from, to    *fnode
	edge        *fedge
	first, last bool
	track       int
}

type layout struct {
	g        *graph
	vertical bool // ranks stack top-to-bottom (TD/BT) rather than left-to-right
	mirror   bool // BT and RL: flip the rank axis
	ranks    [][]*fnode
	segs     [][]*seg // by gap: segs[r] joins rank r to rank r+1
	preds    map[*fnode][]*fnode
	succs    map[*fnode][]*fnode

	rankStart, rankSize []int
	gapStub, gapTracks  []int
	gapLabel            []int
	totalR              int
}

func (g *graph) render() []string {
	l := &layout{g: g, vertical: g.dir == "TD" || g.dir == "BT", mirror: g.dir == "BT" || g.dir == "RL",
		preds: map[*fnode][]*fnode{}, succs: map[*fnode][]*fnode{}}
	l.rank()
	l.split()
	l.order()
	l.measure()
	l.placeO()
	l.tracks()
	l.placeR()
	return l.draw()
}

// rank breaks cycles, then assigns each node its longest-path depth.
func (l *layout) rank() {
	g := l.g
	var edges []*fedge
	for _, e := range g.edges {
		if e.from == e.to {
			e.from.loop = true
			continue
		}
		edges = append(edges, e)
	}
	g.edges = edges

	out := map[*fnode][]*fedge{}
	for _, e := range g.edges {
		out[e.from] = append(out[e.from], e)
	}
	state := map[*fnode]int{}
	var visit func(n *fnode)
	visit = func(n *fnode) {
		state[n] = 1
		for _, e := range out[n] {
			switch state[e.to] {
			case 0:
				visit(e.to)
			case 1: // back edge: lay it out reversed, draw the arrow the right way
				e.reversed = true
			}
		}
		state[n] = 2
	}
	for _, n := range g.nodes {
		if state[n] == 0 {
			visit(n)
		}
	}
	for _, e := range g.edges {
		if e.reversed {
			e.from, e.to = e.to, e.from
		}
	}

	indeg := map[*fnode]int{}
	succ := map[*fnode][]*fnode{}
	for _, e := range g.edges {
		indeg[e.to]++
		succ[e.from] = append(succ[e.from], e.to)
	}
	var queue, topo []*fnode
	for _, n := range g.nodes {
		if indeg[n] == 0 {
			queue = append(queue, n)
		}
	}
	for len(queue) > 0 {
		n := queue[0]
		queue = queue[1:]
		topo = append(topo, n)
		for _, m := range succ[n] {
			m.rank = max(m.rank, n.rank+1)
			if indeg[m]--; indeg[m] == 0 {
				queue = append(queue, m)
			}
		}
	}
	// Pull sources down next to what they feed, so they do not float at the top.
	hasPred := map[*fnode]bool{}
	for _, e := range g.edges {
		hasPred[e.to] = true
	}
	for i := len(topo) - 1; i >= 0; i-- {
		n := topo[i]
		if hasPred[n] || len(succ[n]) == 0 {
			continue
		}
		lowest := succ[n][0].rank
		for _, m := range succ[n] {
			lowest = min(lowest, m.rank)
		}
		n.rank = lowest - 1
	}
}

// split inserts dummy nodes so every segment spans exactly one rank.
func (l *layout) split() {
	maxRank := 0
	for _, n := range l.g.nodes {
		maxRank = max(maxRank, n.rank)
	}
	l.ranks = make([][]*fnode, maxRank+1)
	l.segs = make([][]*seg, maxRank)
	for _, n := range l.g.nodes {
		l.ranks[n.rank] = append(l.ranks[n.rank], n)
	}
	for _, e := range l.g.edges {
		prev := e.from
		for r := e.from.rank + 1; r <= e.to.rank; r++ {
			next := e.to
			if r < e.to.rank {
				next = &fnode{dummy: true, rank: r}
				l.ranks[r] = append(l.ranks[r], next)
			}
			l.segs[r-1] = append(l.segs[r-1], &seg{from: prev, to: next, edge: e, first: prev == e.from, last: next == e.to})
			l.preds[next] = append(l.preds[next], prev)
			l.succs[prev] = append(l.succs[prev], next)
			prev = next
		}
	}
}

func (l *layout) crossings() int {
	total := 0
	for _, segs := range l.segs {
		for i, a := range segs {
			for _, b := range segs[i+1:] {
				if (a.from.order-b.from.order)*(a.to.order-b.to.order) < 0 {
					total++
				}
			}
		}
	}
	return total
}

// order reduces crossings with barycenter sweeps, keeping the best result.
func (l *layout) order() {
	index := func() {
		for _, rank := range l.ranks {
			for i, n := range rank {
				n.order = i
			}
		}
	}
	index()
	best, bestCross := l.snapshot(), l.crossings()
	sweep := func(r int, neighbours map[*fnode][]*fnode) {
		rank := l.ranks[r]
		weight := map[*fnode]float64{}
		for _, n := range rank {
			weight[n] = float64(n.order)
			if ns := neighbours[n]; len(ns) > 0 {
				sum := 0
				for _, m := range ns {
					sum += m.order
				}
				weight[n] = float64(sum) / float64(len(ns))
			}
		}
		sort.SliceStable(rank, func(i, j int) bool { return weight[rank[i]] < weight[rank[j]] })
		for i, n := range rank {
			n.order = i
		}
	}
	for iter := 0; iter < 6 && bestCross > 0; iter++ {
		for r := 1; r < len(l.ranks); r++ {
			sweep(r, l.preds)
		}
		for r := len(l.ranks) - 2; r >= 0; r-- {
			sweep(r, l.succs)
		}
		if c := l.crossings(); c < bestCross {
			best, bestCross = l.snapshot(), c
		}
	}
	l.ranks = best
	index()
}

func (l *layout) snapshot() [][]*fnode {
	out := make([][]*fnode, len(l.ranks))
	for i, r := range l.ranks {
		out[i] = append([]*fnode{}, r...)
	}
	return out
}

func (n *fnode) boxSize() (w, h int) {
	if n.dummy {
		return 1, 1
	}
	if n.loop && len(n.label) > 0 {
		n.label[len(n.label)-1] += " ↺"
		n.loop = false
	}
	for _, s := range n.label {
		w = max(w, utf8.RuneCountInString(s))
	}
	if n.shape == shapeBare {
		return max(w, 1), 1
	}
	w += 4
	if w%2 == 0 {
		w++ // odd widths give edges a true centre column
	}
	return w, len(n.label) + 2
}

func (l *layout) measure() {
	for _, rank := range l.ranks {
		for _, n := range rank {
			w, h := n.boxSize()
			if l.vertical {
				n.sizeO, n.sizeR = w, h
			} else {
				n.sizeO, n.sizeR = h, w
			}
		}
	}
}

// placeO positions nodes along the order axis: left to right in rank order,
// then nudged right toward the average of their neighbours so parents sit
// over children and chains run straight.
func (l *layout) placeO() {
	gap := 1
	if l.vertical {
		gap = 3
	}
	sep := func(a, b *fnode) int {
		if a.dummy && b.dummy {
			return max(gap-1, 1)
		}
		return gap
	}
	centre := func(ns []*fnode) int {
		sum := 0
		for _, m := range ns {
			sum += m.centerO()
		}
		return sum / len(ns)
	}
	for _, rank := range l.ranks {
		for i, n := range rank {
			at := 0
			if i > 0 {
				at = rank[i-1].posO + rank[i-1].sizeO + sep(rank[i-1], n)
			}
			if ps := l.preds[n]; len(ps) > 0 {
				want := centre(ps) - n.sizeO/2
				if i == 0 || want > at {
					at = want
				}
			}
			n.posO = at
		}
	}
	nudge := func(rank []*fnode, neighbours map[*fnode][]*fnode) {
		for i := len(rank) - 1; i >= 0; i-- {
			n := rank[i]
			ns := neighbours[n]
			if len(ns) == 0 {
				continue
			}
			want := centre(ns) - n.sizeO/2
			if i+1 < len(rank) {
				want = min(want, rank[i+1].posO-sep(n, rank[i+1])-n.sizeO)
			}
			n.posO = max(n.posO, want)
		}
	}
	for iter := 0; iter < 3; iter++ {
		for r := len(l.ranks) - 2; r >= 0; r-- {
			nudge(l.ranks[r], l.succs)
		}
		for r := 1; r < len(l.ranks); r++ {
			nudge(l.ranks[r], l.preds)
		}
	}

	// Normalise, leaving room on the left for labels centred on an edge.
	lo := 1 << 30
	for _, rank := range l.ranks {
		for _, n := range rank {
			lo = min(lo, n.posO)
		}
	}
	if l.vertical {
		for _, segs := range l.segs {
			for _, s := range segs {
				if !s.last || s.edge.label == "" {
					continue
				}
				n := utf8.RuneCountInString(s.edge.label)
				if port := l.portTo(s); !s.edge.reversed {
					lo = min(lo, port-n/2)
				} else if port < s.to.centerO() {
					lo = min(lo, port-1-n)
				}
			}
		}
	}
	for _, rank := range l.ranks {
		for _, n := range rank {
			n.posO -= lo
		}
	}
}

// Back edges get their own port, off-centre, so they neither share a trunk
// with forward edges nor merge into a forward edge's arrowhead.
func (l *layout) portOffset(n *fnode, toward int) int {
	if !l.vertical || n.dummy || n.shape == shapeBare {
		return 0
	}
	off := min(2, (n.sizeO-3)/2)
	if toward < n.centerO() {
		return -off // leave on the side the edge is heading for
	}
	return off
}

func (l *layout) portFrom(s *seg) int {
	if s.first && s.edge.reversed {
		return s.from.centerO() + l.portOffset(s.from, s.to.centerO())
	}
	return s.from.centerO()
}

func (l *layout) portTo(s *seg) int {
	if s.last && s.edge.reversed {
		return s.to.centerO() + l.portOffset(s.to, s.from.centerO())
	}
	return s.to.centerO()
}

// tracks gives each source in a gap its own lane for the run across the
// order axis, so edges from different sources never merge by accident.
func (l *layout) tracks() {
	n := len(l.segs)
	l.gapStub, l.gapTracks, l.gapLabel = make([]int, n), make([]int, n), make([]int, n)
	for g, segs := range l.segs {
		type group struct {
			lo, hi int
			segs   []*seg
		}
		type key struct {
			n    *fnode
			port int
		}
		bySource := map[key]*group{}
		var groups []*group
		for _, s := range segs {
			k := key{s.from, l.portFrom(s)}
			gr := bySource[k]
			if gr == nil {
				gr = &group{lo: k.port, hi: k.port}
				bySource[k] = gr
				groups = append(groups, gr)
			}
			gr.lo, gr.hi = min(gr.lo, l.portTo(s)), max(gr.hi, l.portTo(s))
			gr.segs = append(gr.segs, s)

			if s.last && s.edge.label != "" {
				if l.vertical {
					l.gapLabel[g] = 1
				} else {
					l.gapLabel[g] = max(l.gapLabel[g], utf8.RuneCountInString(s.edge.label)+2)
				}
			}
			if !l.vertical || (s.first && (s.edge.reversed || s.edge.tailHead)) {
				l.gapStub[g] = 1
			}
		}
		sort.SliceStable(groups, func(i, j int) bool { return groups[i].lo < groups[j].lo })
		var lanes [][]*group
		for _, gr := range groups {
			if gr.lo == gr.hi {
				continue // straight through: needs no lane of its own
			}
			placed := false
			for t := range lanes {
				free := true
				for _, other := range lanes[t] {
					if gr.lo <= other.hi+1 && other.lo <= gr.hi+1 {
						free = false
						break
					}
				}
				if free {
					lanes[t] = append(lanes[t], gr)
					for _, s := range gr.segs {
						s.track = t
					}
					placed = true
					break
				}
			}
			if !placed {
				lanes = append(lanes, []*group{gr})
				for _, s := range gr.segs {
					s.track = len(lanes) - 1
				}
			}
		}
		l.gapTracks[g] = max(len(lanes), 1)
	}
}

func (l *layout) trackStep() int {
	if l.vertical {
		return 1
	}
	return 2
}

func (l *layout) placeR() {
	l.rankStart, l.rankSize = make([]int, len(l.ranks)), make([]int, len(l.ranks))
	at := 0
	for r, rank := range l.ranks {
		for _, n := range rank {
			l.rankSize[r] = max(l.rankSize[r], n.sizeR)
		}
		l.rankStart[r] = at
		for _, n := range rank {
			n.posR = at
			if n.dummy {
				n.sizeR = l.rankSize[r]
			}
		}
		at += l.rankSize[r]
		if r < len(l.segs) {
			at += l.gapStub[r] + l.gapTracks[r]*l.trackStep() + l.gapLabel[r] + 1
		}
	}
	l.totalR = at
}

// trackPos is the rank-axis coordinate of a segment's lane.
func (l *layout) trackPos(gap int, s *seg) int {
	return l.rankStart[gap] + l.rankSize[gap] + l.gapStub[gap] + s.track*l.trackStep()
}
