// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package mermaid

import (
	"strings"
	"testing"
)

var samples = []string{
	`graph TD
    A[Spawn n workers] --> B[Feed m jobs]
    B --> C{ctx cancelled?}
    C -->|yes| D[Return partial]
    C -->|no| E[Collect results]
    D --> F(Done)
    E --> F`,
	`flowchart LR
    jobs[(jobs chan)] --> w1[worker 1] & w2[worker 2] & w3[worker 3]
    w1 & w2 & w3 --> results[(results chan)]
    results -- collect --> main`,
	`graph TD
    A --> B --> C
    C -->|retry| A
    A --> D
    B -.-> D
    D ==> D`,
	`graph BT
    leaf --> root`,
	`stateDiagram-v2
    [*] --> Idle
    Idle --> Running: start
    Running --> Idle: stop
    Running --> [*]`,
	`sequenceDiagram
    participant M as main
    participant W as worker
    M->>W: job
    Note right of W: job * 2
    W-->>M: result
    loop until closed
      M->>M: collect
    end
    M-xW: cancel`,
}

func TestRenderSamples(t *testing.T) {
	for _, src := range samples {
		out, err := Render(src)
		if err != nil {
			t.Fatalf("%v\n%s", err, src)
		}
		t.Logf("\n%s\n\n%s", src, strings.Join(out, "\n"))
	}
}

func TestUnsupportedAndMalformed(t *testing.T) {
	if _, err := Render("gantt\n title x"); err == nil {
		t.Error("expected an error for gantt")
	}
	for _, src := range []string{"", "graph", "graph TD\n-->", "graph TD\nA -->", "sequenceDiagram", "stateDiagram-v2", "graph LR\nA[unclosed --> B"} {
		Render(src) // must not panic
	}
}
