// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package mermaid

import (
	"fmt"
	"regexp"
	"strings"
)

type shape int

const (
	shapeRect shape = iota
	shapeRound
	shapeDiamond
	shapeDouble
	shapeBare // text only, used for state-diagram start and end markers
)

type fnode struct {
	id    string
	label []string
	shape shape
	dummy bool
	loop  bool // has an edge to itself

	rank, order  int
	sizeR, sizeO int // extent along the rank axis and the order axis
	posR, posO   int
}

func (n *fnode) centerO() int { return n.posO + n.sizeO/2 }

type fedge struct {
	from, to *fnode
	label    string
	style    lineStyle
	head     rune // '>' arrow, 'x', 'o', or 0 for an open link
	tailHead bool // <--> also points back at the source
	reversed bool // drawn against the layout direction (a back edge)
}

type graph struct {
	dir   string // TD, BT, LR, RL
	nodes []*fnode
	byID  map[string]*fnode
	edges []*fedge
}

func (g *graph) node(id string) *fnode {
	if n, ok := g.byID[id]; ok {
		return n
	}
	n := &fnode{id: id, label: []string{id}}
	g.byID[id] = n
	g.nodes = append(g.nodes, n)
	return n
}

var (
	headerRe  = regexp.MustCompile(`^(?:graph|flowchart)\s*(TB|TD|BT|LR|RL)?\s*;?\s*$`)
	idRe      = regexp.MustCompile(`^[\p{L}\p{N}_]+`)
	ignoredRe = regexp.MustCompile(`^(style|classDef|class|click|linkStyle|accTitle|accDescr|direction|end\b|subgraph\b)`)
	brRe      = regexp.MustCompile(`(?i)<br\s*/?>|\\n`)
	tagRe     = regexp.MustCompile(`</?[a-zA-Z][^>]*>`)

	linkTextRes = []*regexp.Regexp{
		regexp.MustCompile(`^(<)?--\s*([^\s\->|][^|>]*?)\s*-{2,}([>xo]?)`),
		regexp.MustCompile(`^(<)?-\.\s*([^\s.\-][^|>]*?)\s*\.+-([>xo]?)`),
		regexp.MustCompile(`^(<)?==\s*([^\s=>|][^|>]*?)\s*={2,}([>xo]?)`),
	}
	linkRe     = regexp.MustCompile(`^(<)?(-{2,}|={2,}|-\.+-)([>xo]?)`)
	pipeTextRe = regexp.MustCompile(`^\s*\|([^|]*)\|`)
)

var shapes = []struct {
	open, close string
	shape       shape
}{
	{"(((", ")))", shapeRound}, {"((", "))", shapeRound}, {"([", "])", shapeRound},
	{"[[", "]]", shapeDouble}, {"[(", ")]", shapeRound}, {"[/", "/]", shapeRect},
	{"[/", "\\]", shapeRect}, {"[\\", "\\]", shapeRect}, {"[\\", "/]", shapeRect},
	{"{{", "}}", shapeDiamond}, {"(", ")", shapeRound}, {"[", "]", shapeRect},
	{"{", "}", shapeDiamond}, {">", "]", shapeRect},
}

func cleanLabel(s string) []string {
	s = strings.TrimSpace(s)
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		s = s[1 : len(s)-1]
	}
	s = strings.Trim(s, "`")
	s = brRe.ReplaceAllString(s, "\n")
	s = tagRe.ReplaceAllString(s, "")
	s = strings.NewReplacer("#quot;", `"`, "&quot;", `"`, "&amp;", "&", "&lt;", "<", "&gt;", ">", "**", "").Replace(s)
	var out []string
	for _, l := range strings.Split(s, "\n") {
		out = append(out, strings.TrimSpace(l))
	}
	return out
}

type stmt struct {
	g   *graph
	s   string
	pos int
}

func (p *stmt) rest() string { return p.s[p.pos:] }

func (p *stmt) skip() {
	for p.pos < len(p.s) && (p.s[p.pos] == ' ' || p.s[p.pos] == '\t') {
		p.pos++
	}
}

func (p *stmt) node() *fnode {
	p.skip()
	id := idRe.FindString(p.rest())
	if id == "" {
		return nil
	}
	p.pos += len(id)
	n := p.g.node(id)
	rest := p.rest()
	for _, sh := range shapes {
		if !strings.HasPrefix(rest, sh.open) {
			continue
		}
		// Find the closer, skipping over quoted text.
		inQuote := false
		for i := len(sh.open); i < len(rest); i++ {
			if rest[i] == '"' {
				inQuote = !inQuote
			}
			if !inQuote && strings.HasPrefix(rest[i:], sh.close) {
				n.label = cleanLabel(rest[len(sh.open):i])
				n.shape = sh.shape
				p.pos += i + len(sh.close)
				goto shaped
			}
		}
	}
shaped:
	if strings.HasPrefix(p.rest(), ":::") {
		p.pos += 3
		p.pos += len(idRe.FindString(p.rest()))
	}
	return n
}

func (p *stmt) group() []*fnode {
	var out []*fnode
	for {
		n := p.node()
		if n == nil {
			return out
		}
		out = append(out, n)
		p.skip()
		if !strings.HasPrefix(p.rest(), "&") {
			return out
		}
		p.pos++
	}
}

func (p *stmt) link() *fedge {
	p.skip()
	rest := p.rest()
	styleOf := func(s string) lineStyle {
		switch {
		case strings.HasPrefix(s, "="):
			return thick
		case strings.Contains(s, "."):
			return dotted
		}
		return solid
	}
	head := func(s string) rune {
		if s == "" {
			return 0
		}
		return rune(s[0])
	}
	for i, re := range linkTextRes {
		if m := re.FindStringSubmatch(rest); m != nil {
			p.pos += len(m[0])
			return &fedge{label: strings.Join(cleanLabel(m[2]), " "), style: []lineStyle{solid, dotted, thick}[i], head: head(m[3]), tailHead: m[1] != ""}
		}
	}
	if m := linkRe.FindStringSubmatch(rest); m != nil {
		p.pos += len(m[0])
		e := &fedge{style: styleOf(m[2]), head: head(m[3]), tailHead: m[1] != ""}
		if t := pipeTextRe.FindStringSubmatch(p.rest()); t != nil {
			p.pos += len(t[0])
			e.label = strings.Join(cleanLabel(t[1]), " ")
		}
		return e
	}
	return nil
}

func (g *graph) statement(s string) {
	p := &stmt{g: g, s: s}
	from := p.group()
	for len(from) > 0 {
		e := p.link()
		if e == nil {
			return
		}
		to := p.group()
		for _, a := range from {
			for _, b := range to {
				edge := *e
				edge.from, edge.to = a, b
				g.edges = append(g.edges, &edge)
			}
		}
		from = to
	}
}

func statements(src string) []string {
	var out []string
	for _, line := range strings.Split(src, "\n") {
		if i := strings.Index(line, "%%"); i >= 0 {
			line = line[:i]
		}
		// Semicolons separate statements, except inside quotes or brackets.
		depth, inQuote, start := 0, false, 0
		for i, r := range line {
			switch {
			case r == '"':
				inQuote = !inQuote
			case inQuote:
			case strings.ContainsRune("[({", r):
				depth++
			case strings.ContainsRune("])}", r):
				depth--
			case r == ';' && depth <= 0:
				out = append(out, strings.TrimSpace(line[start:i]))
				start = i + 1
			}
		}
		out = append(out, strings.TrimSpace(line[start:]))
	}
	var kept []string
	for _, s := range out {
		if s != "" {
			kept = append(kept, s)
		}
	}
	return kept
}

func parseFlowchart(lines []string) (*graph, error) {
	g := &graph{dir: "TD", byID: map[string]*fnode{}}
	if m := headerRe.FindStringSubmatch(lines[0]); m != nil && m[1] != "" {
		g.dir = m[1]
	}
	if g.dir == "TB" {
		g.dir = "TD"
	}
	for _, s := range lines[1:] {
		if ignoredRe.MatchString(s) {
			continue
		}
		g.statement(s)
	}
	if len(g.nodes) == 0 {
		return nil, fmt.Errorf("flowchart has no nodes")
	}
	return g, nil
}

var (
	stateEdgeRe  = regexp.MustCompile(`^(\[\*\]|[\p{L}\p{N}_]+)\s*-->\s*(\[\*\]|[\p{L}\p{N}_]+)\s*(?::\s*(.*))?$`)
	stateAliasRe = regexp.MustCompile(`^state\s+"([^"]*)"\s+as\s+([\p{L}\p{N}_]+)`)
	stateDescRe  = regexp.MustCompile(`^([\p{L}\p{N}_]+)\s*:\s*(.+)$`)
	stateDirRe   = regexp.MustCompile(`^direction\s+(TB|TD|BT|LR|RL)`)
)

func parseState(lines []string) (*graph, error) {
	g := &graph{dir: "TD", byID: map[string]*fnode{}}
	inNote := false
	for _, s := range lines[1:] {
		switch {
		case inNote:
			inNote = !strings.HasPrefix(s, "end note")
		case strings.HasPrefix(s, "note "):
			inNote = !strings.Contains(s, ":")
		case stateDirRe.MatchString(s):
			if g.dir = stateDirRe.FindStringSubmatch(s)[1]; g.dir == "TB" {
				g.dir = "TD"
			}
		case stateAliasRe.MatchString(s):
			m := stateAliasRe.FindStringSubmatch(s)
			n := g.node(m[2])
			n.label, n.shape = cleanLabel(m[1]), shapeRound
		case stateEdgeRe.MatchString(s):
			m := stateEdgeRe.FindStringSubmatch(s)
			end := func(id string, start bool) *fnode {
				if id != "[*]" {
					n := g.node(id)
					if n.shape == shapeRect {
						n.shape = shapeRound
					}
					return n
				}
				n := g.node("[*]end")
				n.label = []string{"◉"}
				if start {
					n = g.node("[*]start")
					n.label = []string{"●"}
				}
				n.shape = shapeBare
				return n
			}
			g.edges = append(g.edges, &fedge{from: end(m[1], true), to: end(m[2], false),
				label: strings.Join(cleanLabel(m[3]), " "), head: '>'})
		case stateDescRe.MatchString(s):
			m := stateDescRe.FindStringSubmatch(s)
			n := g.node(m[1])
			n.label, n.shape = cleanLabel(m[2]), shapeRound
		}
	}
	if len(g.nodes) == 0 {
		return nil, fmt.Errorf("state diagram has no states")
	}
	return g, nil
}

// Render draws Mermaid source as text.
func Render(src string) ([]string, error) {
	lines := statements(src)
	if len(lines) == 0 {
		return nil, fmt.Errorf("empty diagram")
	}
	kind := strings.Fields(lines[0])[0]
	switch {
	case kind == "graph" || kind == "flowchart" || strings.HasPrefix(kind, "flowchart"):
		g, err := parseFlowchart(lines)
		if err != nil {
			return nil, err
		}
		return g.render(), nil
	case strings.HasPrefix(kind, "stateDiagram"):
		g, err := parseState(lines)
		if err != nil {
			return nil, err
		}
		return g.render(), nil
	case kind == "sequenceDiagram":
		return renderSequence(lines[1:])
	}
	return nil, fmt.Errorf("%s diagrams are not rendered in the terminal yet (flowchart, stateDiagram and sequenceDiagram are)", kind)
}
