// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package mermaid

import (
	"fmt"
	"regexp"
	"strings"
	"unicode/utf8"
)

type participant struct {
	id, label string
	x         int // lifeline column
	w         int // header box width
}

type seqEvent struct {
	kind     string // message, note, block
	from, to *participant
	text     string
	dotted   bool
	head     string // ">" filled, ")" async, "x" cross, "" open
	side     string // notes: over, left, right
}

var (
	participantRe = regexp.MustCompile(`^(?:participant|actor)\s+(\S+?)(?:\s+as\s+(.+))?$`)
	messageRe     = regexp.MustCompile(`^(.+?)\s*(<<-->>|<<->>|-->>|->>|--x|-x|--\)|-\)|-->|->)\s*([+-]?)\s*([^:]+?)\s*:\s*(.*)$`)
	noteRe        = regexp.MustCompile(`(?i)^note\s+(over|left of|right of)\s+([^:]+?)\s*:\s*(.*)$`)
	blockRe       = regexp.MustCompile(`^(loop|alt|opt|par|critical|break|else|and|option|rect)\b\s*(.*)$`)
)

func rlen(s string) int { return utf8.RuneCountInString(s) }

func renderSequence(lines []string) ([]string, error) {
	var parts []*participant
	byID := map[string]*participant{}
	get := func(id string) *participant {
		id = strings.TrimSpace(id)
		if p, ok := byID[id]; ok {
			return p
		}
		p := &participant{id: id, label: id}
		byID[id] = p
		parts = append(parts, p)
		return p
	}

	var events []seqEvent
	for _, s := range lines {
		switch {
		case participantRe.MatchString(s):
			m := participantRe.FindStringSubmatch(s)
			p := get(m[1])
			if m[2] != "" {
				p.label = strings.Join(cleanLabel(m[2]), " ")
			}
		case noteRe.MatchString(s):
			m := noteRe.FindStringSubmatch(s)
			ids := strings.Split(m[2], ",")
			ev := seqEvent{kind: "note", side: strings.ToLower(strings.Fields(m[1])[0]), from: get(ids[0]), text: strings.Join(cleanLabel(m[3]), " ")}
			ev.to = ev.from
			if len(ids) > 1 {
				ev.to = get(ids[1])
			}
			events = append(events, ev)
		case s == "end":
			events = append(events, seqEvent{kind: "block", text: "end"})
		case blockRe.MatchString(s):
			m := blockRe.FindStringSubmatch(s)
			label := m[1]
			if m[2] != "" && m[1] != "rect" {
				label += ": " + m[2]
			}
			events = append(events, seqEvent{kind: "block", text: label})
		case messageRe.MatchString(s):
			m := messageRe.FindStringSubmatch(s)
			ev := seqEvent{kind: "message", from: get(m[1]), to: get(m[4]), text: strings.Join(cleanLabel(m[5]), " ")}
			arrow := m[2]
			ev.dotted = strings.HasPrefix(arrow, "--") || strings.HasPrefix(arrow, "<<--")
			switch {
			case strings.HasSuffix(arrow, ">>"):
				ev.head = ">"
			case strings.HasSuffix(arrow, "x"):
				ev.head = "x"
			case strings.HasSuffix(arrow, ")"):
				ev.head = ")"
			}
			events = append(events, ev)
		}
	}
	if len(parts) == 0 {
		return nil, fmt.Errorf("sequence diagram has no participants")
	}

	// Column spacing: wide enough for headers and for every label that has to
	// fit between two lifelines.
	index := map[*participant]int{}
	for i, p := range parts {
		index[p] = i
		p.w = rlen(p.label) + 4
		if p.w%2 == 0 {
			p.w++
		}
	}
	gaps := make([]int, len(parts)) // gaps[i]: distance from lifeline i to i+1
	for i := 0; i+1 < len(parts); i++ {
		gaps[i] = parts[i].w/2 + parts[i+1].w/2 + 3
	}
	tail := 0 // room needed right of the last lifeline
	for _, ev := range events {
		if ev.from == nil {
			continue
		}
		a, b := index[ev.from], index[ev.to]
		if a > b {
			a, b = b, a
		}
		need := rlen(ev.text) + 4
		switch {
		case ev.kind == "note" && ev.side == "right", a == b && ev.kind == "message":
			need = rlen(ev.text) + 6
			if a+1 < len(parts) {
				gaps[a] = max(gaps[a], need)
			} else {
				tail = max(tail, need)
			}
		case ev.kind == "note" && ev.side == "left":
			if a > 0 {
				gaps[a-1] = max(gaps[a-1], need+2)
			}
		case a != b:
			have := 0
			for i := a; i < b; i++ {
				have += gaps[i]
			}
			if extra := need - have; extra > 0 {
				per := (extra + (b - a) - 1) / (b - a)
				for i := a; i < b; i++ {
					gaps[i] += per
				}
			}
		}
	}
	x := parts[0].w / 2
	for _, ev := range events {
		if ev.kind == "note" && ev.side == "left" && index[ev.from] == 0 {
			x = max(x, rlen(ev.text)+6)
		}
	}
	for i, p := range parts {
		p.x = x
		x += gaps[i]
	}
	last := parts[len(parts)-1]
	totalW := max(last.x+last.w/2+1, last.x+tail)

	c := &canvas{}
	for _, p := range parts {
		c.rect(p.x-p.w/2, 0, p.w, 3, solid)
		c.write(p.x-rlen(p.label)/2, 1, p.label)
	}
	y := 3
	lifelines := func(rows int) {
		for i := 0; i < rows; i++ {
			for _, p := range parts {
				c.stroke(p.x, y-1, p.x, y, solid)
			}
			y++
		}
	}
	for _, ev := range events {
		switch ev.kind {
		case "block":
			lifelines(1)
			label := "[" + ev.text + "]"
			for xx := 0; xx < totalW; xx++ {
				*c.at(xx, y-1) = cell{r: '┄'}
			}
			c.write(2, y-1, " "+label+" ")
		case "note":
			a, b := ev.from, ev.to
			if index[a] > index[b] {
				a, b = b, a
			}
			w := rlen(ev.text) + 4
			var left int
			switch ev.side {
			case "right":
				left = a.x + 2
			case "left":
				left = a.x - 1 - w
			default:
				span := b.x - a.x
				w = max(w, span+5)
				left = (a.x+b.x)/2 - w/2
			}
			left = max(left, 0)
			lifelines(3)
			for yy := y - 3; yy < y; yy++ {
				for xx := left; xx < left+w; xx++ {
					*c.at(xx, yy) = cell{}
				}
			}
			c.rect(left, y-3, w, 3, rounded)
			c.write(left+(w-rlen(ev.text))/2, y-2, ev.text)
		case "message":
			if ev.from == ev.to {
				lifelines(3)
				px := ev.from.x
				c.write(px+2, y-3, ev.text)
				c.stroke(px, y-2, px+4, y-2, solid)
				c.stroke(px+4, y-2, px+4, y-1, rounded)
				c.stroke(px+4, y-1, px+2, y-1, solid)
				c.at(px+4, y-2).style, c.at(px+4, y-1).style = rounded, rounded
				c.put(px+1, y-1, '◀')
				continue
			}
			lifelines(2)
			ax, bx := ev.from.x, ev.to.x
			dir := sign(bx - ax)
			lo, hi := min(ax, bx), max(ax, bx)
			c.write(lo+1+(hi-lo-1-rlen(ev.text))/2, y-2, ev.text)
			st := solid
			if ev.dotted {
				st = dotted
			}
			c.stroke(ax, y-1, bx-dir, y-1, st)
			head := map[string][2]rune{">": {'▶', '◀'}, ")": {'▷', '◁'}, "x": {'×', '×'}}[ev.head]
			if head[0] != 0 {
				if dir > 0 {
					c.put(bx-1, y-1, head[0])
				} else {
					c.put(bx+1, y-1, head[1])
				}
			}
		}
	}
	lifelines(1)
	return c.lines(), nil
}
