// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package vego

import (
	"fmt"
	"sort"
	"strings"
)

// A poly is a sum of monomials with integer coefficients. A monomial is a
// product of atoms, written as their names joined by sep; the constant's
// monomial is the empty string.
type poly map[string]int64

const sep = "\x1f"

func constant(v int64) poly {
	if v == 0 {
		return poly{}
	}
	return poly{"": v}
}

func (p poly) add(q poly, k int64) poly {
	out := poly{}
	for m, c := range p {
		out[m] = c
	}
	for m, c := range q {
		out[m] += k * c
		if out[m] == 0 {
			delete(out, m)
		}
	}
	return out
}

func (p poly) mul(q poly) poly {
	out := poly{}
	for m1, c1 := range p {
		for m2, c2 := range q {
			var atoms []string
			if m1 != "" {
				atoms = append(atoms, strings.Split(m1, sep)...)
			}
			if m2 != "" {
				atoms = append(atoms, strings.Split(m2, sep)...)
			}
			sort.Strings(atoms)
			m := strings.Join(atoms, sep)
			out[m] += c1 * c2
			if out[m] == 0 {
				delete(out, m)
			}
		}
	}
	return out
}

func (p poly) isConst() (int64, bool) {
	if len(p) == 0 {
		return 0, true
	}
	if c, ok := p[""]; ok && len(p) == 1 {
		return c, true
	}
	return 0, false
}

func (p poly) String() string {
	keys := make([]string, 0, len(p))
	for m := range p {
		keys = append(keys, m)
	}
	sort.Strings(keys)
	var b strings.Builder
	for _, m := range keys {
		fmt.Fprintf(&b, "%+d", p[m])
		if m != "" {
			b.WriteString("*" + strings.ReplaceAll(m, sep, "*"))
		}
	}
	if b.Len() == 0 {
		return "0"
	}
	return b.String()
}

// A node is a formula whose leaves are constraints: p <= 0, p = 0, or a
// boolean atom with a sign.
type node struct {
	kind  byte // 'a' and, 'o' or, 'l' p <= 0, 'e' p = 0, 'b' boolean atom, 't' true, 'f' false
	kids  []*node
	p     poly
	atom  string
	truth bool
}

var (
	nTrue  = &node{kind: 't'}
	nFalse = &node{kind: 'f'}
)

func le0(p poly) *node {
	if c, ok := p.isConst(); ok {
		if c <= 0 {
			return nTrue
		}
		return nFalse
	}
	return &node{kind: 'l', p: p}
}

func eq0(p poly) *node {
	if c, ok := p.isConst(); ok {
		if c == 0 {
			return nTrue
		}
		return nFalse
	}
	return &node{kind: 'e', p: p}
}

// lt0 is p < 0, which over the integers is p + 1 <= 0.
func lt0(p poly) *node { return le0(p.add(constant(1), 1)) }

func ne0(p poly) *node { return nOr(lt0(p), lt0(poly{}.add(p, -1))) }

func nAnd(kids ...*node) *node {
	var out []*node
	for _, k := range kids {
		switch k.kind {
		case 't':
		case 'f':
			return nFalse
		case 'a':
			out = append(out, k.kids...)
		default:
			out = append(out, k)
		}
	}
	if len(out) == 0 {
		return nTrue
	}
	if len(out) == 1 {
		return out[0]
	}
	return &node{kind: 'a', kids: out}
}

func nOr(kids ...*node) *node {
	var out []*node
	for _, k := range kids {
		switch k.kind {
		case 'f':
		case 't':
			return nTrue
		case 'o':
			out = append(out, k.kids...)
		default:
			out = append(out, k)
		}
	}
	if len(out) == 0 {
		return nFalse
	}
	if len(out) == 1 {
		return out[0]
	}
	return &node{kind: 'o', kids: out}
}

// The budgets keep a hopeless proof from holding up the editor. Running out
// of budget means "not proved", never "proved".
const (
	maxSteps       = 2000
	maxConstraints = 1500
	maxInstances   = 4000
	maxTerms       = 14
)

type prover struct {
	fresh     int
	steps     int
	instances int
	gaveUp    bool
	atoms     map[string]bool // atoms whose axioms have been stated
	axioms    []*node
	sels      map[string][]selAtom // by array
}

type selAtom struct {
	name string
	idx  poly
}

// proves reports whether the hypotheses entail the goal. It answers by
// refutation: the hypotheses and the goal's negation must have no model.
func proves(hyps []*expr, goal *expr) bool {
	// Most proofs need every Forall only at the terms that are already there.
	// Some need it again at the terms those instances mention, and that costs
	// much more, so it is the second thing to try and not the first.
	return attempt(hyps, goal, 1) || attempt(hyps, goal, 2)
}

func attempt(hyps []*expr, goal *expr, rounds int) bool {
	pr := &prover{atoms: map[string]bool{}, sels: map[string][]selAtom{}}
	f := nnf(and(conj(hyps), not(goal)), true)
	f = pr.skolem(f)
	for round := 0; round < rounds; round++ {
		f = pr.instantiate(f, pr.terms(f), round < rounds-1)
	}
	f = pr.instantiate(f, nil, false)
	g := pr.ground(f)
	pr.congruence()
	all := nAnd(append([]*node{g}, pr.axioms...)...)
	return pr.refute(nil, map[string]bool{}, []*node{all}) && !pr.gaveUp
}

// nnf pushes negations down to the atoms. pos is false under a negation.
func nnf(e *expr, pos bool) *expr {
	switch e.op {
	case opTrue, opFalse:
		if pos == (e.op == opTrue) {
			return eTrue
		}
		return eFalse
	case opNot:
		return nnf(e.args[0], !pos)
	case opAnd, opOr:
		o := e.op
		if !pos {
			o = opAnd + opOr - o
		}
		return mk(o, nnf(e.args[0], pos), nnf(e.args[1], pos))
	case opImp:
		if pos {
			return mk(opOr, nnf(e.args[0], false), nnf(e.args[1], true))
		}
		return mk(opAnd, nnf(e.args[0], true), nnf(e.args[1], false))
	case opIff:
		a, b := e.args[0], e.args[1]
		if pos {
			return mk(opAnd, mk(opOr, nnf(a, false), nnf(b, true)), mk(opOr, nnf(b, false), nnf(a, true)))
		}
		return mk(opOr, mk(opAnd, nnf(a, true), nnf(b, false)), mk(opAnd, nnf(b, true), nnf(a, false)))
	case opForall, opExists:
		o := e.op
		if !pos {
			o = opForall + opExists - o
		}
		return &expr{op: o, name: e.name, args: []*expr{nnf(e.args[0], pos)}}
	}
	if pos {
		return e
	}
	switch e.op {
	case opLt:
		return mk(opLe, e.args[1], e.args[0])
	case opLe:
		return mk(opLt, e.args[1], e.args[0])
	case opEq:
		return mk(opNe, e.args[0], e.args[1])
	case opNe:
		return mk(opEq, e.args[0], e.args[1])
	}
	return not(e) // a boolean atom
}

// skolem names a witness for every Exists that is not under a Forall. One
// under a Forall waits until the Forall has been instantiated.
func (pr *prover) skolem(e *expr) *expr {
	switch e.op {
	case opAnd, opOr:
		return mk(e.op, pr.skolem(e.args[0]), pr.skolem(e.args[1]))
	case opExists:
		pr.fresh++
		w := sym(fmt.Sprintf("%s?%d", e.name, pr.fresh), sInt)
		return pr.skolem(subst(e.args[0], e.name, w))
	}
	return e
}

// terms collects what a Forall might be worth instantiating with: the ground
// terms that index a slice, and the witnesses.
func (pr *prover) terms(e *expr) []*expr {
	seen := map[string]bool{}
	var out []*expr
	var walk func(e *expr, bound []string)
	walk = func(e *expr, bound []string) {
		if e == nil {
			return
		}
		if e.op == opForall || e.op == opExists {
			bound = append(bound[:len(bound):len(bound)], e.name)
		}
		candidate := e.op == opSel && len(e.args) == 2
		var t *expr
		if candidate {
			t = e.args[1]
		} else if e.op == opVar && strings.Contains(e.name, "?") {
			t, candidate = e, true
		}
		if candidate {
			free := true
			for _, n := range names(t) {
				for _, b := range bound {
					free = free && n != b
				}
			}
			if key := t.String(); free && !seen[key] && len(out) < maxTerms {
				seen[key] = true
				out = append(out, t)
			}
		}
		for _, a := range e.args {
			walk(a, bound)
		}
	}
	walk(e, nil)
	return out
}

// instantiate replaces every outermost Forall by its instances at the terms,
// and keeps the Forall itself for a later round if asked to.
func (pr *prover) instantiate(e *expr, terms []*expr, keep bool) *expr {
	switch e.op {
	case opAnd, opOr:
		return mk(e.op, pr.instantiate(e.args[0], terms, keep), pr.instantiate(e.args[1], terms, keep))
	case opForall:
		out := eTrue
		if keep {
			out = e
		}
		for _, t := range terms {
			if pr.instances++; pr.instances > maxInstances {
				pr.gaveUp = true
				break
			}
			inst := pr.skolem(subst(e.args[0], e.name, t))
			out = and(out, pr.instantiate(inst, terms, keep))
		}
		return out
	}
	return e
}

// ground turns a quantifier-free formula into constraints.
func (pr *prover) ground(e *expr) *node {
	switch e.op {
	case opTrue:
		return nTrue
	case opFalse:
		return nFalse
	case opAnd:
		return nAnd(pr.ground(e.args[0]), pr.ground(e.args[1]))
	case opOr:
		return nOr(pr.ground(e.args[0]), pr.ground(e.args[1]))
	case opForall:
		return nTrue // a fact we could not use
	case opExists:
		pr.gaveUp = true
		return nTrue
	case opNot:
		return &node{kind: 'b', atom: e.args[0].String(), truth: false}
	case opVar, opCall:
		return &node{kind: 'b', atom: e.String(), truth: true}
	}
	if len(e.args) != 2 || isBool(e.args[0]) || isBool(e.args[1]) {
		pr.gaveUp = true // a number where a formula belongs, or the other way round
		return nTrue
	}
	d := pr.poly(e.args[0]).add(pr.poly(e.args[1]), -1)
	switch e.op {
	case opLe:
		return le0(d)
	case opLt:
		return lt0(d)
	case opEq:
		return eq0(d)
	case opNe:
		return ne0(d)
	}
	pr.gaveUp = true
	return nTrue
}

// poly normalises an integer term. Whatever is not arithmetic becomes an
// atom: a variable, an element of a slice, a length, a quotient.
func (pr *prover) poly(e *expr) poly {
	switch e.op {
	case opNum:
		return constant(e.val)
	case opVar:
		return poly{e.name: 1}
	case opAdd:
		return pr.poly(e.args[0]).add(pr.poly(e.args[1]), 1)
	case opSub:
		return pr.poly(e.args[0]).add(pr.poly(e.args[1]), -1)
	case opNeg:
		return poly{}.add(pr.poly(e.args[0]), -1)
	case opMul:
		p := pr.poly(e.args[0]).mul(pr.poly(e.args[1]))
		pr.products(p)
		return p
	case opLen:
		name := "len(" + e.args[0].name + ")"
		if !pr.atoms[name] {
			pr.atoms[name] = true
			pr.axioms = append(pr.axioms, le0(poly{name: -1}))
		}
		return poly{name: 1}
	case opSel:
		idx := pr.poly(e.args[1])
		arr := e.args[0].name
		name := arr + "[" + idx.String() + "]"
		if !pr.atoms[name] {
			pr.atoms[name] = true
			pr.sels[arr] = append(pr.sels[arr], selAtom{name, idx})
		}
		return poly{name: 1}
	case opDiv, opMod:
		return pr.divide(e)
	}
	pr.gaveUp = true
	return poly{e.String(): 1}
}

// divide states what Go's division means. For a = q*b + r with b > 0, the
// remainder has the sign of a and is smaller than b.
func (pr *prover) divide(e *expr) poly {
	a, b := pr.poly(e.args[0]), pr.poly(e.args[1])
	key := "(" + a.String() + ")/(" + b.String() + ")"
	q, r := "quo"+key, "rem"+key
	if !pr.atoms[q] {
		pr.atoms[q] = true
		qb := poly{q: 1}.mul(b)
		pr.products(qb)
		// a = q*b + r
		pr.axioms = append(pr.axioms, eq0(a.add(qb, -1).add(poly{r: 1}, -1)))
		pos := lt0(poly{}.add(b, -1))                    // 0 < b
		nonneg, nonpos := le0(poly{}.add(a, -1)), le0(a) // 0 <= a, a <= 0
		small := lt0(poly{r: 1}.add(b, -1))              // r < b
		smallNeg := lt0(poly{r: -1}.add(b, -1))          // -r < b
		pr.axioms = append(pr.axioms,
			nOr(negate(pos), negate(nonneg), nAnd(le0(poly{r: -1}), small, le0(poly{q: -1}))),
			nOr(negate(pos), negate(nonpos), nAnd(le0(poly{r: 1}), smallNeg, le0(poly{q: 1}))))
	}
	if e.op == opDiv {
		return poly{q: 1}
	}
	return poly{r: 1}
}

// negate works on the constraints divide builds: p <= 0 becomes -p + 1 <= 0.
func negate(n *node) *node {
	switch n.kind {
	case 't':
		return nFalse
	case 'f':
		return nTrue
	case 'l':
		return lt0(poly{}.add(n.p, -1))
	}
	panic("negate: not an inequality")
}

// products says the little that is known about x*y: it is not negative when
// neither factor is, and a square never is.
func (pr *prover) products(p poly) {
	for m := range p {
		atoms := strings.Split(m, sep)
		if len(atoms) != 2 || pr.atoms[m] {
			continue
		}
		pr.atoms[m] = true
		x, y := atoms[0], atoms[1]
		if x == y {
			pr.axioms = append(pr.axioms, le0(poly{m: -1}))
			continue
		}
		pr.axioms = append(pr.axioms, nOr(lt0(poly{x: 1}), lt0(poly{y: 1}), le0(poly{m: -1})),
			nOr(lt0(poly{x: 1}), le0(poly{y: 1}), le0(poly{x: 1, m: -1})), // 0 <= x and 1 <= y: x <= xy
			nOr(lt0(poly{y: 1}), le0(poly{x: 1}), le0(poly{y: 1, m: -1})))
	}
}

// congruence says that equal indices select equal elements.
func (pr *prover) congruence() {
	pairs := 0
	for _, list := range pr.sels {
		for i := range list {
			for j := i + 1; j < len(list); j++ {
				d := list[i].idx.add(list[j].idx, -1)
				if c, ok := d.isConst(); ok && c != 0 {
					continue
				}
				if pairs++; pairs > 80 {
					return
				}
				pr.axioms = append(pr.axioms, nOr(ne0(d), eq0(poly{list[i].name: 1, list[j].name: -1})))
			}
		}
	}
}

// refute reports whether the constraints, the boolean assignment and the
// formulas still to do are unsatisfiable together.
func (pr *prover) refute(cons []poly2, bools map[string]bool, todo []*node) bool {
	if pr.steps++; pr.steps > maxSteps {
		pr.gaveUp = true
		return false
	}
	cons = cons[:len(cons):len(cons)]
	var ors []*node
	copied := false
	for len(todo) > 0 {
		n := todo[len(todo)-1]
		todo = todo[: len(todo)-1 : len(todo)-1]
		switch n.kind {
		case 'f':
			return true
		case 'a':
			todo = append(todo, n.kids...)
		case 'o':
			ors = append(ors, n)
		case 'l', 'e':
			cons = append(cons, poly2{n.p, n.kind == 'e'})
		case 'b':
			if v, ok := bools[n.atom]; ok && v != n.truth {
				return true
			}
			if !copied {
				c := make(map[string]bool, len(bools)+1)
				for k, v := range bools {
					c[k] = v
				}
				bools, copied = c, true
			}
			bools[n.atom] = n.truth
		}
	}
	if pr.unsat(cons) {
		return true
	}
	if len(ors) == 0 {
		return false
	}
	// Drop the disjuncts that are already impossible; a disjunction with one
	// disjunct left is a fact, and one with none closes the branch.
	var rest []*node
	var units []*node
	for _, o := range ors {
		var live []*node
		for _, k := range o.kids {
			if !pr.dead(cons, bools, k) {
				live = append(live, k)
			}
		}
		switch len(live) {
		case 0:
			return true
		case 1:
			units = append(units, live[0])
		default:
			rest = append(rest, &node{kind: 'o', kids: live})
		}
	}
	if len(units) > 0 {
		return pr.refute(cons, bools, append(rest, units...))
	}
	sort.SliceStable(rest, func(i, j int) bool { return len(rest[i].kids) < len(rest[j].kids) })
	for _, k := range rest[0].kids {
		if !pr.refute(cons, bools, append(rest[1:len(rest):len(rest)], k)) {
			return false
		}
	}
	return true
}

// dead reports whether a disjunct is a constraint that contradicts what is
// already known. Anything more complicated is left for the branch to find.
func (pr *prover) dead(cons []poly2, bools map[string]bool, n *node) bool {
	switch n.kind {
	case 'f':
		return true
	case 'b':
		v, ok := bools[n.atom]
		return ok && v != n.truth
	case 'l', 'e':
		return pr.unsat(append(cons[:len(cons):len(cons)], poly2{n.p, n.kind == 'e'}))
	}
	return false
}

// poly2 is one constraint: p <= 0, or p = 0.
type poly2 struct {
	p  poly
	eq bool
}

// unsat decides whether linear constraints have no rational solution, with
// the rounding that makes it sharper over the integers. Every monomial is a
// variable here, so a product is just another unknown.
func (pr *prover) unsat(cons []poly2) bool {
	var eqs, les []poly
	for _, c := range cons {
		if c.eq {
			eqs = append(eqs, c.p)
		} else {
			les = append(les, c.p)
		}
	}
	eqs, les = squeeze(eqs, les)
	eqs, les = unfoldProducts(eqs, les)
	// Equalities first: solve each for one variable and substitute.
	for len(eqs) > 0 {
		e := eqs[0]
		eqs = eqs[1:]
		e, ok := tighten(e, true)
		if !ok {
			return true
		}
		if len(e) == 0 {
			continue
		}
		v := pivot(e)
		for i := range eqs {
			eqs[i] = eliminate(eqs[i], e, v)
		}
		for i := range les {
			les[i] = eliminate(les[i], e, v)
		}
	}
	for {
		// Normalise, drop what is trivially true, and keep the tightest of the
		// constraints that differ only in their constant.
		best := map[string]poly{}
		for _, p := range les {
			p, _ := tighten(p, false)
			if c, ok := p.isConst(); ok {
				if c > 0 {
					return true
				}
				continue
			}
			k := key(p)
			if old, ok := best[k]; !ok || p[""] > old[""] {
				best[k] = p
			}
		}
		if len(best) == 0 {
			return false
		}
		if len(best) > maxConstraints {
			pr.gaveUp = true
			return false
		}
		les = les[:0]
		keys := make([]string, 0, len(best))
		for k := range best {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			les = append(les, best[k])
		}
		// Eliminate the variable that multiplies the fewest pairs.
		up, down := map[string]int{}, map[string]int{}
		for _, p := range les {
			for m, c := range p {
				if m == "" {
					continue
				}
				if c > 0 {
					up[m]++
				} else {
					down[m]++
				}
			}
		}
		v, cost := "", -1
		for _, p := range les {
			for m := range p {
				if m == "" {
					continue
				}
				if c := up[m] * down[m]; cost < 0 || c < cost || c == cost && m < v {
					v, cost = m, c
				}
			}
		}
		var next, pos, neg []poly
		for _, p := range les {
			switch c := p[v]; {
			case c > 0:
				pos = append(pos, p)
			case c < 0:
				neg = append(neg, p)
			default:
				next = append(next, p)
			}
		}
		for _, p := range pos {
			for _, n := range neg {
				a, b := p[v], -n[v]
				if big(a) || big(b) {
					pr.gaveUp = true
					return false
				}
				c := poly{}.add(p, b).add(n, a)
				for _, k := range c {
					if big(k) {
						pr.gaveUp = true
						return false
					}
				}
				next = append(next, c)
			}
		}
		les = next
	}
}

// squeeze finds the equalities hidden in pairs of inequalities: p <= 0 and
// -p <= 0.
func squeeze(eqs, les []poly) ([]poly, []poly) {
	byKey := map[string]bool{}
	for _, p := range les {
		byKey[p.String()] = true
	}
	for _, p := range les {
		if len(p) > 0 && byKey[poly{}.add(p, -1).String()] {
			eqs = append(eqs, p)
		}
	}
	return eqs, les
}

// unfoldProducts uses an equality x = e inside the products x occurs in.
// Elimination cannot do that, because to it x*y is one unknown and x another;
// but i = n + 1 is exactly what turns i*i into something about n.
func unfoldProducts(eqs, les []poly) ([]poly, []poly) {
	for round := 0; round < 8; round++ {
		x, by := "", poly(nil)
		for _, e := range eqs {
			for m, c := range e {
				if m == "" || strings.Contains(m, sep) || c != 1 && c != -1 || !inProduct(m, eqs, les) {
					continue
				}
				rest := poly{}.add(e, -c) // x = rest, once x's own term is taken out
				delete(rest, m)
				if mentions(rest, m) {
					continue
				}
				if x == "" || m < x {
					x, by = m, rest
				}
			}
		}
		if x == "" {
			break
		}
		for i := range eqs {
			eqs[i] = substitute(eqs[i], x, by)
		}
		for i := range les {
			les[i] = substitute(les[i], x, by)
		}
		eqs = append(eqs, poly{x: 1}.add(by, -1)) // what substituting made trivial
	}
	return eqs, les
}

func mentions(p poly, x string) bool {
	for m := range p {
		for _, a := range strings.Split(m, sep) {
			if a == x {
				return true
			}
		}
	}
	return false
}

func inProduct(x string, lists ...[]poly) bool {
	for _, list := range lists {
		for _, p := range list {
			for m := range p {
				if strings.Contains(m, sep) && mentions(poly{m: 1}, x) {
					return true
				}
			}
		}
	}
	return false
}

func substitute(p poly, x string, by poly) poly {
	if !mentions(p, x) {
		return p
	}
	out := poly{}
	for m, c := range p {
		term := poly{"": c}
		for _, a := range strings.Split(m, sep) {
			switch {
			case a == x:
				term = term.mul(by)
			case a != "":
				term = term.mul(poly{a: 1})
			}
		}
		out = out.add(term, 1)
	}
	return out
}

func big(v int64) bool { return v > 1<<30 || v < -(1<<30) }

func key(p poly) string {
	ms := make([]string, 0, len(p))
	for m := range p {
		if m != "" {
			ms = append(ms, m)
		}
	}
	sort.Strings(ms)
	var b strings.Builder
	for _, m := range ms {
		fmt.Fprintf(&b, "%d*%s;", p[m], m)
	}
	return b.String()
}

// tighten divides a constraint by the gcd of its coefficients. Over the
// integers the constant of an inequality rounds up, and an equality whose
// constant does not divide has no solution.
func tighten(p poly, eq bool) (poly, bool) {
	var g int64
	for m, c := range p {
		if m != "" {
			g = gcd(g, c)
		}
	}
	if g == 0 {
		c := p[""]
		return p, !eq || c == 0
	}
	if g == 1 {
		return p, true
	}
	out := poly{}
	for m, c := range p {
		if m != "" {
			out[m] = c / g
		}
	}
	c := p[""]
	if eq {
		if c%g != 0 {
			return p, false
		}
		c /= g
	} else {
		c = ceilDiv(c, g)
	}
	if c != 0 {
		out[""] = c
	}
	return out, true
}

func gcd(a, b int64) int64 {
	if a < 0 {
		a = -a
	}
	if b < 0 {
		b = -b
	}
	for b != 0 {
		a, b = b, a%b
	}
	return a
}

func ceilDiv(a, b int64) int64 {
	q := a / b
	if a%b != 0 && (a < 0) == (b < 0) {
		q++
	}
	return q
}

// pivot picks the variable of an equality to solve for: one with coefficient
// ±1 if there is one, so that substituting it loses nothing over the integers.
func pivot(e poly) string {
	v := ""
	for m, c := range e {
		if m == "" {
			continue
		}
		unit := c == 1 || c == -1
		bestUnit := v != "" && (e[v] == 1 || e[v] == -1)
		if v == "" || unit && !bestUnit || unit == bestUnit && m < v {
			v = m
		}
	}
	return v
}

// eliminate removes v from p using the equality e = 0.
func eliminate(p, e poly, v string) poly {
	c := p[v]
	if c == 0 {
		return p
	}
	a := e[v]
	// |a|*p - sign(a)*c*e has no v, and scaling an inequality by |a| > 0 is fine.
	if a < 0 {
		return poly{}.add(p, -a).add(e, c)
	}
	return poly{}.add(p, a).add(e, -c)
}
