// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package vego

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"path/filepath"
	"sort"
	"strings"

	"github.com/tlehman/litgo/internal/lit"
)

// Marker starts a comment that is a VeGo annotation.
const Marker = "//@"

// Source is a Go file to verify.
type Source struct {
	Path string
	Text []byte
}

// Pos is a 0-based position in a Source.
type Pos struct {
	Path      string
	Line, Col int
}

// Finding is something the verifier has to say. Ref, when it has a Path, is a
// second position; the message mentions it as {ref}.
type Finding struct {
	Pos
	EndCol  int
	Warning bool
	Message string
	Ref     Pos
}

// Summary counts what a verification did.
type Summary struct {
	Functions   int // functions with annotations
	Proved      int // of which every obligation was proved
	Obligations int
	Names       []string // the proved functions
}

// annot is one annotation: a //@ comment, with the lines that continue it.
type annot struct {
	kind    string
	text    string // the formula
	e       *expr
	pos     token.Pos
	where   Pos
	endCol  int
	textCol int // where the formula starts on the line
	first   int // how much of the formula is on that line
	lines   int // how many comment lines it takes
	used    bool
}

// Annotated reports whether a Go file has annotations at all, which is what
// decides whether verifying it is worth the time.
func Annotated(text []byte) bool {
	return strings.Contains(string(text), Marker) || strings.Contains(string(text), "// @ ")
}

// Prove verifies the annotated Go a document tangles to, and reports at the
// document's own lines. Nothing is written, so it works on a buffer.
func Prove(res *lit.Result) ([]lit.Diag, Summary) {
	var total Summary
	if res.HasErrors() {
		return nil, total
	}
	packages := map[string][]*lit.Output{}
	var dirs []string
	for _, o := range res.Files {
		if o.File.Lang != "go" || strings.HasSuffix(o.Path, "_test.go") {
			continue
		}
		dir := filepath.Dir(o.Path)
		if packages[dir] == nil {
			dirs = append(dirs, dir)
		}
		packages[dir] = append(packages[dir], o)
	}
	var diags []lit.Diag
	seen := map[string]bool{}
	for _, dir := range dirs {
		var sources []Source
		outputs := map[string]*lit.Output{}
		annotated := false
		for _, o := range packages[dir] {
			text := o.Bytes()
			annotated = annotated || Annotated(text)
			sources = append(sources, Source{o.Path, text})
			outputs[o.Path] = o
		}
		if !annotated {
			continue
		}
		findings, sum := Verify(sources)
		total.Functions += sum.Functions
		total.Proved += sum.Proved
		total.Obligations += sum.Obligations
		total.Names = append(total.Names, sum.Names...)
		for _, f := range findings {
			o := outputs[f.Path]
			line, col, _, ok := o.Map(f.Line, f.Col)
			if !ok {
				continue
			}
			d := lit.Diag{File: res.Doc.Path, Line: line, Col: col, Severity: lit.SevError, Message: f.Message, Source: "vego"}
			if f.Warning {
				d.Severity = lit.SevWarning
			}
			if f.EndCol > f.Col {
				d.EndCol = col + f.EndCol - f.Col
			}
			if f.Ref.Path != "" {
				if l, _, _, ok := outputs[f.Ref.Path].Map(f.Ref.Line, f.Ref.Col); ok {
					d.Message = strings.ReplaceAll(d.Message, "{ref}", fmt.Sprintf("line %d", l+1))
				}
			}
			// A chunk that is used twice is verified twice, and fails twice.
			key := fmt.Sprintf("%d:%d:%s", d.Line, d.Col, d.Message)
			if !seen[key] {
				seen[key] = true
				diags = append(diags, d)
			}
		}
	}
	return diags, total
}

// Verify checks every annotated function of one package.
func Verify(sources []Source) ([]Finding, Summary) {
	v := &verifier{fset: token.NewFileSet(), funcs: map[string]*fn{}, structs: map[string]map[string]string{},
		consts: map[string]int64{}, preds: map[string]*predicate{}, reported: map[string]bool{}}
	for _, s := range sources {
		f, err := parser.ParseFile(v.fset, s.Path, s.Text, parser.ParseComments|parser.SkipObjectResolution)
		if err != nil {
			continue // the syntax check has more to say about it than we do
		}
		v.files = append(v.files, f)
	}
	for _, f := range v.files {
		v.declarations(f)
	}
	for _, f := range v.files {
		v.functions(f)
	}
	for _, f := range v.files {
		v.annotations(f)
	}
	var sum Summary
	for _, f := range v.ordered {
		if !f.annotated {
			continue
		}
		sum.Functions++
		before := v.errors
		v.verify(f)
		sum.Obligations += f.obligations
		if v.errors == before && !f.broken {
			sum.Proved++
			sum.Names = append(sum.Names, f.key)
		}
	}
	for _, a := range v.all {
		if !a.used && a.e != nil {
			v.report(a.where, a.endCol, false, a.kind+" is not attached to anything: Requires goes above a function, Ensures below it, Invariant and Variant at a loop")
		}
	}
	sort.SliceStable(v.findings, func(i, j int) bool {
		a, b := v.findings[i], v.findings[j]
		if a.Path != b.Path {
			return a.Path < b.Path
		}
		return a.Line < b.Line
	})
	return v.findings, sum
}

type vkind int

const (
	kNone vkind = iota
	kInt
	kBool
	kSlice
	kStruct
)

type param struct {
	name string
	kind vkind
	typ  string // the struct's name, for kStruct
}

// fn is a function of the package, with its contract.
type fn struct {
	key         string // name, or Type.name for a method
	decl        *ast.FuncDecl
	recv        *param
	params      []param
	results     []param
	requires    []*annot
	ensures     []*annot
	exsures     []*annot
	measure     []*annot
	inside      []*annot // the annotations in the body
	annotated   bool
	broken      bool // an annotation of it does not parse
	obligations int
}

type verifier struct {
	fset       *token.FileSet
	files      []*ast.File
	funcs      map[string]*fn
	ordered    []*fn
	structs    map[string]map[string]string
	consts     map[string]int64
	preds      map[string]*predicate
	all        []*annot
	findings   []Finding
	reported   map[string]bool
	errors     int
	fresh      int
	parseFresh int
}

func (v *verifier) position(p token.Pos) Pos {
	pp := v.fset.Position(p)
	return Pos{pp.Filename, pp.Line - 1, pp.Column - 1}
}

func (v *verifier) report(at Pos, endCol int, warning bool, msg string) {
	v.reportRef(at, endCol, warning, msg, Pos{})
}

// reportRef reports once per place and message: a contract that fails on
// three paths is still one problem.
func (v *verifier) reportRef(at Pos, endCol int, warning bool, msg string, ref Pos) {
	key := fmt.Sprintf("%s:%d:%d:%s", at.Path, at.Line, at.Col, msg)
	if v.reported[key] {
		return
	}
	v.reported[key] = true
	if !warning {
		v.errors++
	}
	v.findings = append(v.findings, Finding{Pos: at, EndCol: endCol, Warning: warning, Message: msg, Ref: ref})
}

// kindOf reads a type the way the verifier sees it: integers, booleans,
// slices of integers, and structs declared in the package.
func (v *verifier) kindOf(t ast.Expr) (vkind, string) {
	switch t := t.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64":
			return kInt, ""
		case "bool":
			return kBool, ""
		}
		if _, ok := v.structs[t.Name]; ok {
			return kStruct, t.Name
		}
	case *ast.StarExpr:
		if k, name := v.kindOf(t.X); k == kStruct {
			return k, name
		}
	case *ast.ArrayType:
		if k, _ := v.kindOf(t.Elt); t.Len == nil && k == kInt {
			return kSlice, ""
		}
	case *ast.ParenExpr:
		return v.kindOf(t.X)
	}
	return kNone, ""
}

// declarations notes the structs and the integer constants.
func (v *verifier) declarations(f *ast.File) {
	for _, d := range f.Decls {
		g, ok := d.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range g.Specs {
			switch s := spec.(type) {
			case *ast.TypeSpec:
				if st, ok := s.Type.(*ast.StructType); ok {
					fields := map[string]string{}
					for _, fl := range st.Fields.List {
						for _, n := range fl.Names {
							fields[n.Name] = typeText(fl.Type)
						}
					}
					v.structs[s.Name.Name] = fields
				}
			case *ast.ValueSpec:
				if g.Tok != token.CONST {
					continue
				}
				for i, n := range s.Names {
					if i < len(s.Values) {
						if c, ok := constInt(s.Values[i]); ok {
							v.consts[n.Name] = c
						}
					}
				}
			}
		}
	}
}

// functions notes the functions, once every struct they may mention is known.
func (v *verifier) functions(f *ast.File) {
	for _, d := range f.Decls {
		fd, ok := d.(*ast.FuncDecl)
		if !ok || fd.Body == nil {
			continue
		}
		f := &fn{key: fd.Name.Name, decl: fd}
		if fd.Recv != nil && len(fd.Recv.List) == 1 {
			r := fd.Recv.List[0]
			k, typ := v.kindOf(r.Type)
			name := "_"
			if len(r.Names) == 1 {
				name = r.Names[0].Name
			}
			f.recv = &param{name, k, typ}
			f.key = strings.TrimPrefix(typeText(r.Type), "*") + "." + f.key
		}
		f.params = v.fields(fd.Type.Params, "")
		f.results = v.fields(fd.Type.Results, "ret_")
		v.funcs[f.key] = f
		v.ordered = append(v.ordered, f)
	}
}

func (v *verifier) fields(list *ast.FieldList, unnamed string) []param {
	var out []param
	if list == nil {
		return nil
	}
	for _, fl := range list.List {
		k, typ := v.kindOf(fl.Type)
		if len(fl.Names) == 0 {
			out = append(out, param{fmt.Sprintf("%s%d", unnamed, len(out)), k, typ})
		}
		for _, n := range fl.Names {
			out = append(out, param{n.Name, k, typ})
		}
	}
	return out
}

func typeText(t ast.Expr) string {
	switch t := t.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + typeText(t.X)
	case *ast.ArrayType:
		if t.Len == nil {
			return "[]" + typeText(t.Elt)
		}
	}
	return "?"
}

func constInt(e ast.Expr) (int64, bool) {
	switch e := e.(type) {
	case *ast.BasicLit:
		if e.Kind == token.INT {
			var v int64
			if _, err := fmt.Sscan(e.Value, &v); err == nil {
				return v, true
			}
		}
	case *ast.UnaryExpr:
		if c, ok := constInt(e.X); ok && e.Op == token.SUB {
			return -c, true
		}
	case *ast.ParenExpr:
		return constInt(e.X)
	}
	return 0, false
}

// annotations reads a file's //@ comments, parses them, and hands each to the
// function it belongs to.
func (v *verifier) annotations(f *ast.File) {
	var list []*annot
	for _, group := range f.Comments {
		var open *annot // an annotation whose formula is not finished
		for _, c := range group.List {
			body, ok := lit.ProofComment(c.Text, open != nil)
			if !ok {
				open = nil
				continue
			}
			if open != nil {
				open.text += " " + strings.TrimSpace(body)
				open.lines++
				if !continues(body) {
					open = nil
				}
				continue
			}
			rest := strings.TrimLeft(body, " \t")
			a := &annot{kind: "Assert", pos: c.Pos(), where: v.position(c.Pos()), lines: 1}
			a.endCol = a.where.Col + len(c.Text)
			word, after, _ := strings.Cut(rest, " ")
			if lit.ProofKeywords[word] {
				a.kind = word
				rest = strings.TrimLeft(after, " \t")
			}
			a.text = strings.TrimSpace(rest)
			a.first = len(a.text)
			a.textCol = a.where.Col + len(c.Text) - len(rest)
			list = append(list, a)
			if continues(body) {
				open = a
			}
		}
	}
	for _, a := range list {
		v.parse(a)
	}
	v.all = append(v.all, list...)

	var decls []*fn
	for _, fd := range v.ordered {
		if v.fset.File(fd.decl.Pos()) == v.fset.File(f.Pos()) {
			decls = append(decls, fd)
		}
	}
	for _, a := range list {
		if a.kind == "Predicate" {
			a.used = true
			continue
		}
		if v.inType(f, a) {
			v.report(a.where, a.endCol, true, "litgo prove does not check contracts on interface methods")
			a.used = true
			continue
		}
		var inside, before, after *fn
		for _, fd := range decls {
			switch {
			case a.pos > fd.decl.Body.Lbrace && a.pos < fd.decl.Body.Rbrace:
				inside = fd
			case fd.decl.End() <= a.pos:
				before = fd
			case a.pos < fd.decl.Pos() && after == nil:
				after = fd
			}
		}
		// An Ensures belongs to the function above it, unless it is part of
		// the doc comment of the function below and does not touch the one above.
		if after != nil && after.decl.Doc != nil && a.pos >= after.decl.Doc.Pos() && a.pos < after.decl.Doc.End() &&
			!(before != nil && v.adjacent(before, a, list)) {
			before = nil
		}
		var owner *fn
		switch a.kind {
		case "Requires":
			if owner = after; inside != nil {
				owner = nil
			}
			if owner != nil {
				owner.requires = append(owner.requires, a)
			}
		case "Ensures", "Exsures":
			if inside == nil {
				if owner = before; owner == nil {
					owner = after
				}
			}
			if owner != nil && a.kind == "Ensures" {
				owner.ensures = append(owner.ensures, a)
			} else if owner != nil {
				owner.exsures = append(owner.exsures, a)
			}
		case "Measure":
			if owner = inside; owner == nil {
				owner = after
			}
			if owner != nil {
				owner.measure = append(owner.measure, a)
			}
		case "Property":
			v.report(a.where, a.endCol, true, "litgo prove does not check Property annotations")
			a.used = true
			continue
		default:
			if owner = inside; owner != nil {
				owner.inside = append(owner.inside, a)
			}
		}
		if owner != nil {
			owner.annotated = true
			owner.broken = owner.broken || a.e == nil
			if a.kind != "Requires" && a.kind != "Ensures" && a.kind != "Exsures" && a.kind != "Measure" {
				continue // the body marks its own as used, when it reaches them
			}
			a.used = true
		}
	}
}

// inType reports whether an annotation is written inside a type declaration,
// which is where VeGo puts the contract of an interface method.
func (v *verifier) inType(f *ast.File, a *annot) bool {
	for _, d := range f.Decls {
		if g, ok := d.(*ast.GenDecl); ok && g.Tok == token.TYPE && a.pos > g.Pos() && a.pos < g.End() {
			return true
		}
	}
	return false
}

// adjacent reports whether nothing but annotations lies between the end of a
// function and an annotation below it.
func (v *verifier) adjacent(f *fn, a *annot, list []*annot) bool {
	line := v.position(f.decl.End()).Line
	for _, b := range list {
		if b.where.Line == line+1 && b.pos > f.decl.End() {
			line += b.lines
			if b == a {
				return true
			}
		}
	}
	return false
}

func (v *verifier) parse(a *annot) {
	var err error
	switch a.kind {
	case "Predicate":
		var p *predicate
		if p, err = parsePredicate(a.text, &v.parseFresh); err == nil {
			v.preds[p.name] = p
			a.e = p.body
		}
	case "Immutable":
		a.e = eTrue
	default:
		a.e, err = parseFormula(a.text, &v.parseFresh)
		number := a.kind == "Variant" || a.kind == "Measure"
		if err == nil && a.e.op != opCall && isBool(a.e) == number {
			a.e = nil
			err = &syntaxError{0, "this has to be a formula, something that is true or false"}
			if number {
				err = &syntaxError{0, "this has to be an integer expression, something that can get smaller"}
			}
		}
	}
	if se, ok := err.(*syntaxError); ok {
		at := a.where
		at.Col = a.textCol + min(se.pos, a.first)
		v.report(at, a.endCol, false, "in this "+a.kind+": "+se.msg)
	}
}
