// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package vego

import (
	"go/format"
	"os"
	"strings"
	"testing"

	"github.com/tlehman/litgo/internal/lit"
)

func verifySrc(t *testing.T, src string) ([]Finding, Summary) {
	t.Helper()
	return Verify([]Source{{"t.go", []byte("package p\n" + src)}})
}

func expectProved(t *testing.T, src string, n int) {
	t.Helper()
	fs, sum := verifySrc(t, src)
	for _, f := range fs {
		if !f.Warning {
			t.Errorf("unexpected: %d:%d %s", f.Line+1, f.Col+1, f.Message)
		}
	}
	if sum.Proved != n {
		t.Errorf("proved %d of %d, want %d", sum.Proved, sum.Functions, n)
	}
}

func expectFail(t *testing.T, src, want string) {
	t.Helper()
	fs, _ := verifySrc(t, src)
	for _, f := range fs {
		if !f.Warning && strings.Contains(f.Message, want) {
			return
		}
	}
	t.Errorf("no error containing %q in %v", want, fs)
}

const divide = `
//@ Requires n >= 0 ^ d > 0
func Divide(n, d int) (q, r int) {
	r = n
	//@ Invariant n = q*d + r ^ r >= 0
	//@ Variant r
	for r >= d {
		q++
		r -= d
	}
	return q, r
}
//@ Ensures n = q*d + r
//@ Ensures 0 <= r < d
`

func TestDivide(t *testing.T) { expectProved(t, divide, 1) }

// gofmt moves annotations around: //@ becomes // @ in a doc comment, and an
// Ensures gets a blank line above it. The proof has to come out the same, and
// so does the refusal.
func TestSurvivesGofmt(t *testing.T) {
	for _, src := range []string{divide, search} {
		formatted, err := format.Source([]byte("package p\n" + src))
		if err != nil {
			t.Fatal(err)
		}
		text := strings.TrimPrefix(string(formatted), "package p\n")
		if !strings.Contains(text, "// @ Requires") || !strings.Contains(text, "}\n\n//@ Ensures") {
			t.Fatalf("gofmt no longer does what this test is about:\n%s", text)
		}
		expectProved(t, text, 1)
	}
	formatted, _ := format.Source([]byte("package p\n" + strings.Replace(divide, "r -= d", "r -= 1", 1)))
	expectFail(t, strings.TrimPrefix(string(formatted), "package p\n"), "Invariant is not maintained")
}

// A contract may also be written whole above its function.
func TestContractAbove(t *testing.T) {
	const above = `
func First() (x int) { return 1 }

//@ Requires n >= 0
//@ Ensures r = n + 1
func Next(n int) (r int) { return n + 1 }
`
	expectProved(t, above, 1)
	expectFail(t, strings.Replace(above, "return n + 1", "return n", 1), "Ensures is not proved")
}

// What the verifier cannot follow, it refuses.
func TestRefusals(t *testing.T) {
	expectFail(t, `
//@ Requires 0 <= i ^ i < |A|
func Set(A []int, i int) (x int) {
	A[i] = 0
	return A[i]
}
//@ Ensures x = 0
`, "only variables can be assigned to")
	expectFail(t, `
func scramble(A []int) {
	for i := range A {
		A[i] = 0
	}
}

//@ Requires |A| > 0 ^ A[0] = 1
func Keeps(A []int) (x int) {
	scramble(A)
	return A[0]
}
//@ Ensures x = 1
`, "scramble has no annotations")
	expectFail(t, `
//@ Requires n >= 0
func Bad(n int) (x int) {
	//@ Assert n + 1
	return n
}
`, "this has to be a formula")
	expectFail(t, `
//@ Requires n >= 0
func Bad(n int) (x int) {
	//@ Variant n > 0
	for n > 0 {
		n--
	}
	return n
}
`, "this has to be an integer expression")
	fs, sum := verifySrc(t, `
type Counter interface {
	//@ Requires self.Value >= 0
	Increment()
}

//@ Requires n >= 0
func Id(n int) (x int) { return n }
//@ Ensures x = n
`)
	if sum.Proved != 1 || len(fs) != 1 || !fs[0].Warning {
		t.Errorf("findings = %+v, sum = %+v", fs, sum)
	}
}

func TestDivideWrong(t *testing.T) {
	expectFail(t, strings.Replace(divide, "r -= d", "r -= 1", 1), "Invariant is not maintained")
	expectFail(t, strings.Replace(divide, "d > 0", "d >= 0", 1), "Variant is not shown to decrease")
	expectFail(t, strings.Replace(divide, "0 <= r < d", "0 <= r <= d - 2", 1), "Ensures is not proved")
}

func TestGauss(t *testing.T) {
	expectProved(t, `
//@ Requires n >= 0
func Sum(n int) (s int) {
	//@ Invariant 0 <= i <= n + 1 ^ 2*s = i*(i-1)
	//@ Variant n + 1 - i
	for i := 0; i <= n; i++ {
		s += i
	}
	return s
}
//@ Ensures 2*s = n*(n+1)
`, 1)
}

func TestSqrt(t *testing.T) {
	expectProved(t, `
//@ Requires n >= 0
func Isqrt(n int) (r int) {
	//@ Invariant r >= 0 ^ r*r <= n
	//@ Variant n - r*r
	for (r+1)*(r+1) <= n {
		r++
	}
	return r
}
//@ Ensures r*r <= n ^ n < (r+1)*(r+1)
`, 1)
}

const search = `
//@ Predicate Sorted(A) ::= Forall i in [0, |A|) : Forall j in [i, |A|) : A[i] <= A[j]

//@ Requires Sorted(A)
func Search(A []int, x int) (at int, found bool) {
	lo, hi := 0, len(A)
	//@ Invariant 0 <= lo <= hi <= |A|
	//@ Invariant A[0:lo) < x ^ x < A[hi:|A|)
	//@ Variant hi - lo
	for lo < hi {
		mid := lo + (hi-lo)/2
		if A[mid] == x {
			return mid, true
		} else if A[mid] < x {
			lo = mid + 1
		} else {
			hi = mid
		}
	}
	return 0, false
}
//@ Ensures found -> 0 <= at < |A| ^ A[at] = x
//@ Ensures ~found -> x <> A[:]
`

func TestSearch(t *testing.T) { expectProved(t, search, 1) }

func TestSearchWrong(t *testing.T) {
	expectFail(t, strings.Replace(search, "lo = mid + 1", "lo = mid", 1), "Variant is not shown to decrease")
	expectFail(t, strings.Replace(search, "hi = mid\n", "hi = mid - 1\n", 1), "Invariant is not maintained")
	expectFail(t, strings.Replace(search, "//@ Requires Sorted(A)\n", "", 1), "Invariant is not maintained")
}

func TestSafety(t *testing.T) {
	expectFail(t, `
//@ Requires i >= 0
func At(A []int, i int) (x int) { return A[i] }
`, "index may be out of range")
	expectFail(t, `
//@ Requires a >= 0
func Div(a, b int) (x int) { return a / b }
`, "divisor may be zero")
}

func TestCallsAndRecursion(t *testing.T) {
	expectProved(t, `
//@ Requires n >= 0
//@ Measure n
func Fact(n int) (f int) {
	//@ BaseCase n = 0
	if n == 0 {
		return 1
	}
	return n * Fact(n-1)
}
//@ Ensures f >= 1

//@ Requires a >= 0 ^ b >= 0
func Use(a, b int) (x int) {
	return Fact(a) + Fact(b)
}
//@ Ensures x >= 2
`, 2)
	expectFail(t, `
//@ Requires n >= 0
//@ Measure n
func F(n int) (f int) {
	if n == 0 {
		return 1
	}
	return F(n)
}
`, "Measure is not shown to get smaller")
}

func TestPrimesAndPreserves(t *testing.T) {
	expectProved(t, `
//@ Requires a = a
func P(a int) (x int) {
	x = 0
	x = x + 1
	x = x + 2
	//@ Assert x = 0 ^ x' = 1 ^ x'' = 3
	y := a
	//@ Preserves x + y >= a
	x++
	y--
	x++
	return x + y
}
//@ Ensures x >= a
`, 1)
}

// The examples are documentation, and documentation that claims a proof had
// better have one.
func TestExamples(t *testing.T) {
	for name, want := range map[string]int{"isqrt": 1, "vego-tutorial": 15, "heap": 10} {
		src, err := os.ReadFile("../../examples/" + name + ".lit.md")
		if err != nil {
			t.Skip(err)
		}
		diags, sum := Prove(lit.Parse(name+".lit.md", src).Tangle())
		for _, d := range diags {
			if d.Severity == lit.SevError {
				t.Errorf("%s:%d: %s", name, d.Line+1, d.Message)
			}
		}
		if sum.Proved != want || sum.Functions != want {
			t.Errorf("%s: proved %d of %d, want %d", name, sum.Proved, sum.Functions, want)
		}
	}
}

// A failure is reported where the annotation is in the Markdown, and the
// line it mentions is a line of the Markdown too.
// litgo proves the arithmetic of its own source map. The test names the two
// functions, so that deleting their annotations does not pass for a proof.
func TestLitgoProvesItself(t *testing.T) {
	src, err := os.ReadFile("../../litgo.lit.md")
	if err != nil {
		t.Skip(err)
	}
	diags, sum := Prove(lit.Parse("litgo.lit.md", src).Tangle())
	for _, d := range diags {
		if d.Severity == lit.SevError {
			t.Errorf("litgo.lit.md:%d: %s", d.Line+1, d.Message)
		}
	}
	proved := strings.Join(sum.Names, " ")
	if !strings.Contains(proved, "Seg.out") || !strings.Contains(proved, "Seg.src") || sum.Proved != sum.Functions {
		t.Errorf("proved %d of %d: %s", sum.Proved, sum.Functions, proved)
	}
}

func TestProveMapsToTheDocument(t *testing.T) {
	doc := "<!-- package: halve -->\n# Halving\n\n```go\nfunc Halve(n int) (h int) {\n\t// <<halve>>\n}\n//@ Ensures 2*h = n\n```\n\n" +
		"<!-- chunk: halve -->\n```go\nreturn n / 2\n```\n"
	diags, sum := Prove(lit.Parse("halve.lit.md", []byte(doc)).Tangle())
	if sum.Proved != 0 || len(diags) != 1 {
		t.Fatalf("diags = %+v, sum = %+v", diags, sum)
	}
	d := diags[0]
	if d.Line != 7 || d.Source != "vego" || !strings.Contains(d.Message, "the return at line 13") {
		t.Errorf("diag = %+v", d)
	}
}

func TestOneLine(t *testing.T) {
	expectProved(t, `
type Seg struct{ OutCol, Len, SrcLine, SrcCol int }

//@ Requires s.SrcCol <= col ^ col <= s.SrcCol + s.Len
func (s Seg) out(col int) (c int) { return s.OutCol + col - s.SrcCol }
//@ Ensures s.OutCol <= c ^ c <= s.OutCol + s.Len
//@ Ensures s.src(c) = col

//@ Requires s.OutCol <= col ^ col <= s.OutCol + s.Len
func (s Seg) src(col int) (c int) { return s.SrcCol + col - s.OutCol }
//@ Ensures s.SrcCol <= c ^ c <= s.SrcCol + s.Len
//@ Ensures s.out(c) = col
`, 2)
}
