// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package vego

import (
	"fmt"
	"go/ast"
	"go/token"
	"sort"
	"strings"
)

// binding is a program variable on one path: its kind, and every value it
// has had since it was declared or since the loop around it was cut. The
// last one is its value now; the ones before are what primes reach for.
type binding struct {
	kind vkind
	typ  string
	hist []*expr
}

// state is one path through a function: what the variables hold, and what is
// known to be true.
type state struct {
	vars      map[string]*binding
	scopes    []map[string]*binding // what each open block shadowed
	hyps      []*expr
	preserved []kept
	base      []*expr // the BaseCase conditions passed so far
}

type kept struct {
	a     *annot
	depth int
}

func (s *state) clone() *state {
	c := &state{vars: make(map[string]*binding, len(s.vars)), hyps: s.hyps[:len(s.hyps):len(s.hyps)],
		preserved: s.preserved[:len(s.preserved):len(s.preserved)], base: s.base[:len(s.base):len(s.base)]}
	for n, b := range s.vars {
		c.vars[n] = &binding{b.kind, b.typ, append([]*expr{}, b.hist...)}
	}
	for _, sc := range s.scopes {
		m := make(map[string]*binding, len(sc))
		for n, b := range sc {
			m[n] = b
		}
		c.scopes = append(c.scopes, m)
	}
	return c
}

func (s *state) push() { s.scopes = append(s.scopes, map[string]*binding{}) }

func (s *state) pop() {
	top := s.scopes[len(s.scopes)-1]
	s.scopes = s.scopes[:len(s.scopes)-1]
	for n, old := range top {
		for f := range s.vars {
			if strings.HasPrefix(f, n+".") {
				delete(s.vars, f)
			}
		}
		if old == nil {
			delete(s.vars, n)
		} else {
			s.vars[n] = old
		}
	}
	for len(s.preserved) > 0 && s.preserved[len(s.preserved)-1].depth > len(s.scopes) {
		s.preserved = s.preserved[:len(s.preserved)-1]
	}
}

func (s *state) popTo(depth int) {
	for len(s.scopes) > depth {
		s.pop()
	}
}

func (s *state) declare(name string, b *binding) {
	if name == "_" {
		return
	}
	if top := s.scopes[len(s.scopes)-1]; top != nil {
		if _, ok := top[name]; !ok {
			top[name] = s.vars[name]
		}
	}
	for f := range s.vars {
		if strings.HasPrefix(f, name+".") {
			delete(s.vars, f)
		}
	}
	s.vars[name] = b
}

// outcomes are the states a statement leaves behind, by how it was left.
// A return leaves none: its obligations are settled on the spot.
type outcomes struct {
	normal, brk, cont []*state
}

func (o *outcomes) add(p outcomes) {
	o.normal = append(o.normal, p.normal...)
	o.brk = append(o.brk, p.brk...)
	o.cont = append(o.cont, p.cont...)
}

// run verifies one function.
type run struct {
	v        *verifier
	f        *fn
	entry    map[string]*expr // the parameters' values on entry
	blocks   map[*ast.BlockStmt][]*annot
	measure0 []*expr
	paths    int
	depth    int // of one-line functions being unfolded
}

// unsupported is how the verifier backs out of a function it cannot follow.
type unsupported struct {
	pos token.Pos
	msg string
}

func (r *run) no(n ast.Node, format string, args ...any) {
	panic(unsupported{n.Pos(), fmt.Sprintf(format, args...)})
}

const maxPaths = 400

func (v *verifier) verify(f *fn) {
	r := &run{v: v, f: f, entry: map[string]*expr{}, blocks: map[*ast.BlockStmt][]*annot{}}
	defer func() {
		if p := recover(); p != nil {
			u, ok := p.(unsupported)
			if !ok {
				// A bug in the verifier. The editor is on the other end of this,
				// so say so at the function instead of taking the server down.
				u = unsupported{f.decl.Name.Pos(), fmt.Sprintf("the verifier failed (%v); please report this", p)}
			}
			at := v.position(u.pos)
			v.report(at, 0, false, fmt.Sprintf("%s is not verified: %s", f.key, u.msg))
		}
	}()
	r.place()
	st := &state{vars: map[string]*binding{}}
	st.push()
	all := append([]param{}, f.params...)
	if f.recv != nil {
		all = append(all, *f.recv)
	}
	for _, p := range all {
		if p.kind == kNone && p.name != "_" {
			// Whatever it is, the proof cannot mention it.
			continue
		}
		b := &binding{kind: p.kind, typ: p.typ}
		if p.kind != kStruct {
			b.hist = []*expr{r.fresh(p.name, p.kind)}
			r.entry[p.name] = b.hist[0]
		}
		st.declare(p.name, b)
	}
	for _, p := range f.results {
		if p.kind != kInt && p.kind != kBool {
			r.no(f.decl, "its result %s is neither an integer nor a boolean", p.name)
		}
		zero := num(0)
		if p.kind == kBool {
			zero = eFalse
		}
		st.declare(p.name, &binding{kind: p.kind, hist: []*expr{zero}})
	}
	for _, a := range f.requires {
		if a.e != nil {
			st.hyps = append(st.hyps, r.formula(st, a, false))
		}
	}
	for _, a := range f.measure {
		if a.e != nil {
			r.measure0 = append(r.measure0, r.formula(st, a, false))
		}
	}
	r.lint()
	if r.recursive() && len(f.measure) == 0 {
		v.report(v.position(f.decl.Name.Pos()), 0, true, f.key+" calls itself and has no Measure, so nothing shows that it terminates")
	}
	out := r.block(st, f.decl.Body)
	for _, s := range out.normal {
		r.leave(s, f.decl.Body.Rbrace)
	}
}

// place sorts the annotations of the body into the blocks they are written in.
func (r *run) place() {
	for _, a := range r.f.inside {
		var inner *ast.BlockStmt
		ast.Inspect(r.f.decl.Body, func(n ast.Node) bool {
			if b, ok := n.(*ast.BlockStmt); ok && a.pos > b.Lbrace && a.pos < b.Rbrace {
				inner = b
			}
			return true
		})
		if inner != nil {
			r.blocks[inner] = append(r.blocks[inner], a)
		}
	}
}

// lint points at contracts that say nothing.
func (r *run) lint() {
	for _, list := range [][]*annot{r.f.requires, r.f.ensures} {
		for _, a := range list {
			if a.e != nil && a.e.op == opTrue {
				r.v.report(a.where, a.endCol, true, a.kind+" true says nothing")
			}
		}
	}
}

func (r *run) recursive() bool {
	found := false
	ast.Inspect(r.f.decl.Body, func(n ast.Node) bool {
		if c, ok := n.(*ast.CallExpr); ok {
			if callee, _ := r.callee(nil, c); callee == r.f {
				found = true
			}
		}
		return true
	})
	return found
}

func (r *run) fresh(name string, k vkind) *expr {
	r.v.fresh++
	s := sInt
	if k == kBool {
		s = sBool
	} else if k == kSlice {
		s = sArr
	}
	return sym(fmt.Sprintf("%s#%d", name, r.v.fresh), s)
}

// check is one proof obligation. It reports at the annotation, or at a
// place in the code, and mentions a second place if there is one.
func (r *run) check(st *state, goal *expr, a *annot, at ast.Node, ref ast.Node, msg string) bool {
	r.f.obligations++
	if proves(st.hyps, goal) {
		return true
	}
	where, end := Pos{}, 0
	if a != nil {
		where, end = a.where, a.endCol
	} else {
		where = r.v.position(at.Pos())
		end = where.Col + int(at.End()-at.Pos())
	}
	var rp Pos
	if ref != nil {
		rp = r.v.position(ref.Pos())
	}
	r.v.reportRef(where, end, false, msg, rp)
	return false
}

func (r *run) assume(st *state, f *expr) { st.hyps = append(st.hyps, f) }

// feasible reports whether a path can be taken at all. Pruning the ones that
// cannot keeps their obligations from being reported as failures of logic.
func (r *run) feasible(st *state) bool { return !proves(st.hyps, eFalse) }

// formula gives an annotation's formula its meaning in a state: predicates
// and one-line functions unfolded, names replaced by values. In a
// postcondition a parameter means its value on entry, and primed, its value
// at the end.
func (r *run) formula(st *state, a *annot, post bool) *expr {
	e := r.unfold(st, a, a.e, 0)
	most := map[string]int{}
	var count func(e *expr)
	count = func(e *expr) {
		if e == nil {
			return
		}
		if e.op == opVar {
			most[e.name] = max(most[e.name], e.primes)
		}
		for _, x := range e.args {
			count(x)
		}
	}
	count(e)
	return rewrite(e, func(v *expr) *expr {
		if strings.ContainsAny(v.name, "#?") {
			return nil
		}
		if old, ok := r.entry[v.name]; ok && post {
			if v.primes == 0 {
				return old
			}
			return r.lookup(st, a, v.name, 0)
		}
		return r.lookup(st, a, v.name, most[v.name]-v.primes)
	})
}

// lookup finds the value a name had `back` assignments ago.
func (r *run) lookup(st *state, a *annot, name string, back int) *expr {
	b := r.binding(st, name)
	if b == nil {
		if c, ok := r.v.consts[name]; ok {
			return num(c)
		}
		r.bad(a, "%s is not a variable here", name)
	}
	if b.kind == kStruct || len(b.hist) == 0 {
		r.bad(a, "%s is not an integer, a boolean or a slice of integers", name)
	}
	if back >= len(b.hist) {
		r.bad(a, "%s has not been assigned often enough on this path for that many primes", name)
	}
	return b.hist[len(b.hist)-1-back]
}

// binding finds a variable, or makes one for the field of a struct the
// first time it is mentioned. Nothing in the fragment assigns to a field, so
// a field holds one value throughout.
func (r *run) binding(st *state, name string) *binding {
	if b := st.vars[name]; b != nil {
		return b
	}
	base, field, ok := strings.Cut(name, ".")
	if !ok {
		return nil
	}
	s := st.vars[base]
	if s == nil || s.kind != kStruct {
		return nil
	}
	var k vkind
	switch r.v.structs[s.typ][field] {
	case "int", "int8", "int16", "int32", "int64":
		k = kInt
	case "bool":
		k = kBool
	case "[]int":
		k = kSlice
	default:
		return nil
	}
	b := &binding{kind: k, hist: []*expr{r.fresh(name, k)}}
	st.vars[name] = b
	return b
}

// bad gives up on an annotation that does not make sense.
func (r *run) bad(a *annot, format string, args ...any) {
	msg := fmt.Sprintf(format, args...)
	if a == nil {
		panic(unsupported{r.f.decl.Pos(), msg})
	}
	r.v.report(a.where, a.endCol, false, "in this "+a.kind+": "+msg)
	panic(unsupported{r.f.decl.Name.Pos(), "one of its annotations does not make sense"})
}

// unfold replaces P(x, y) by what it stands for: the body of a predicate, or
// the expression a one-line Go function returns.
func (r *run) unfold(st *state, a *annot, e *expr, depth int) *expr {
	if e == nil {
		return nil
	}
	if depth > 12 {
		r.bad(a, "%s is defined in terms of itself", e.name)
	}
	c := *e
	c.args = make([]*expr, len(e.args))
	for i, x := range e.args {
		c.args[i] = r.unfold(st, a, x, depth)
	}
	if e.op != opCall {
		return &c
	}
	if p := r.v.preds[e.name]; p != nil {
		if len(p.params) != len(c.args) {
			r.bad(a, "%s takes %d arguments", p.name, len(p.params))
		}
		return r.unfold(st, a, replace(p.body, p.params, c.args, "", ""), depth+1)
	}
	callee, recv := r.named(st, e.name)
	if callee == nil {
		r.bad(a, "%s is neither a predicate nor a function of this package", e.name)
	}
	body := r.oneLine(callee)
	if body == nil {
		r.bad(a, "%s cannot be used in a formula: only a function whose body is one return of one expression can", e.name)
	}
	if len(callee.params) != len(c.args) {
		r.bad(a, "%s takes %d arguments", e.name, len(callee.params))
	}
	var formals []string
	for _, p := range callee.params {
		formals = append(formals, p.name)
	}
	from := ""
	if callee.recv != nil {
		from = callee.recv.name
	}
	return r.unfold(st, a, replace(body, formals, c.args, from, recv), depth+1)
}

// replace substitutes all the parameters at once, and renames the fields of
// the callee's receiver to fields of the caller's.
func replace(body *expr, formals []string, actuals []*expr, from, to string) *expr {
	return rewrite(body, func(v *expr) *expr {
		for i, f := range formals {
			if v.name == f && v.primes == 0 {
				return actuals[i]
			}
		}
		if from != "" && strings.HasPrefix(v.name, from+".") {
			c := *v
			c.name = to + strings.TrimPrefix(v.name, from)
			return &c
		}
		return nil
	})
}

// named finds the function a formula or a call mentions: f, or x.m where x
// is a struct.
func (r *run) named(st *state, name string) (*fn, string) {
	if f := r.v.funcs[name]; f != nil && f.recv == nil {
		return f, ""
	}
	if i := strings.LastIndex(name, "."); i > 0 && st != nil {
		if b := st.vars[name[:i]]; b != nil && b.kind == kStruct {
			return r.v.funcs[b.typ+name[i:]], name[:i]
		}
	}
	return nil, ""
}

// oneLine is the expression a function returns, if that is all it does.
func (r *run) oneLine(f *fn) *expr {
	if len(f.decl.Body.List) != 1 || len(f.results) != 1 || len(f.inside) > 0 {
		return nil
	}
	ret, ok := f.decl.Body.List[0].(*ast.ReturnStmt)
	if !ok || len(ret.Results) != 1 {
		return nil
	}
	kinds := map[string]vkind{}
	for _, p := range f.params {
		kinds[p.name] = p.kind
	}
	var e *expr
	func() {
		defer func() {
			if p := recover(); p != nil {
				if _, ok := p.(unsupported); !ok {
					panic(p)
				}
				e = nil
			}
		}()
		e = r.pure(ret.Results[0], func(name string) vkind {
			if k, ok := kinds[name]; ok {
				return k
			}
			if f.recv != nil && strings.HasPrefix(name, f.recv.name+".") {
				if r.v.structs[f.recv.typ][strings.TrimPrefix(name, f.recv.name+".")] == "bool" {
					return kBool
				}
			}
			return kInt
		})
	}()
	return e
}

// pure reads a Go expression as a term over the names it mentions. It
// checks nothing yet; pos remembers where each part came from.
func (r *run) pure(e ast.Expr, kind func(string) vkind) *expr {
	at := func(x *expr) *expr { x.pos = int(e.Pos()); return x }
	switch e := e.(type) {
	case *ast.ParenExpr:
		return r.pure(e.X, kind)
	case *ast.BasicLit:
		if c, ok := constInt(e); ok {
			return at(num(c))
		}
	case *ast.Ident:
		switch e.Name {
		case "true":
			return eTrue
		case "false":
			return eFalse
		}
		s := sInt
		if kind(e.Name) == kBool {
			s = sBool
		} else if kind(e.Name) == kSlice {
			s = sArr
		}
		return at(sym(e.Name, s))
	case *ast.SelectorExpr:
		if x, ok := e.X.(*ast.Ident); ok {
			name := x.Name + "." + e.Sel.Name
			s := sInt
			if kind(name) == kBool {
				s = sBool
			} else if kind(name) == kSlice {
				s = sArr
			}
			return at(sym(name, s))
		}
	case *ast.UnaryExpr:
		x := r.pure(e.X, kind)
		switch e.Op {
		case token.SUB:
			return at(mk(opNeg, x))
		case token.ADD:
			return x
		case token.NOT:
			return at(mk(opNot, x))
		}
	case *ast.BinaryExpr:
		l, rt := r.pure(e.X, kind), r.pure(e.Y, kind)
		switch e.Op {
		case token.ADD:
			return at(mk(opAdd, l, rt))
		case token.SUB:
			return at(mk(opSub, l, rt))
		case token.MUL:
			return at(mk(opMul, l, rt))
		case token.QUO:
			return at(mk(opDiv, l, rt))
		case token.REM:
			return at(mk(opMod, l, rt))
		case token.LAND:
			return at(mk(opAnd, l, rt))
		case token.LOR:
			return at(mk(opOr, l, rt))
		case token.LSS:
			return at(mk(opLt, l, rt))
		case token.LEQ:
			return at(mk(opLe, l, rt))
		case token.GTR:
			return at(mk(opLt, rt, l))
		case token.GEQ:
			return at(mk(opLe, rt, l))
		case token.EQL, token.NEQ:
			var c *expr
			if isBool(l) || isBool(rt) {
				c = mk(opIff, l, rt)
			} else {
				c = mk(opEq, l, rt)
			}
			if e.Op == token.NEQ {
				c = mk(opNot, c)
			}
			return at(c)
		}
	case *ast.IndexExpr:
		a := r.pure(e.X, kind)
		if a.op == opVar {
			a.sort = sArr
			return at(mk(opSel, a, r.pure(e.Index, kind)))
		}
	case *ast.CallExpr:
		name := ""
		switch f := e.Fun.(type) {
		case *ast.Ident:
			name = f.Name
		case *ast.SelectorExpr:
			if x, ok := f.X.(*ast.Ident); ok {
				name = x.Name + "." + f.Sel.Name
			}
		}
		if name == "" {
			break
		}
		var args []*expr
		for _, x := range e.Args {
			args = append(args, r.pure(x, kind))
		}
		if name == "len" && len(args) == 1 && args[0].op == opVar {
			args[0].sort = sArr
			return at(mk(opLen, args[0]))
		}
		if name == "int" && len(args) == 1 {
			return args[0]
		}
		c := at(&expr{op: opCall, name: name, args: args})
		return c
	}
	r.no(e, "this expression is outside what litgo prove understands (integers, booleans, slices of integers, fields of structs, calls of verified functions)")
	return nil
}

// value evaluates a Go expression in a state, and states what has to be
// true for the evaluation to be safe: indices in range, divisors not zero,
// the preconditions of what is called.
func (r *run) value(st *state, e ast.Expr) *expr {
	p := r.pure(e, func(name string) vkind {
		if b := r.binding(st, name); b != nil {
			return b.kind
		}
		return kNone
	})
	vals := r.eval(st, p, nil, e)
	if len(vals) != 1 {
		r.no(e, "a call with %d results cannot be used as a value", len(vals))
	}
	return vals[0]
}

// eval does the work of value. The guards are what is known at this point
// of the expression and not before: the left side of an && while its right
// side is being evaluated.
func (r *run) eval(st *state, e *expr, guards []*expr, at ast.Node) []*expr {
	one := func(x *expr) *expr {
		vals := r.eval(st, x, guards, at)
		if len(vals) != 1 {
			r.no(at, "a call with %d results cannot be used as a value", len(vals))
		}
		return vals[0]
	}
	guarded := func(goal *expr) *expr {
		if len(guards) == 0 {
			return goal
		}
		return mk(opImp, conj(guards), goal)
	}
	here := ast.Node(at)
	if e.pos != 0 {
		here = point(e.pos)
	}
	switch e.op {
	case opNum, opTrue, opFalse:
		return []*expr{e}
	case opVar:
		if strings.ContainsAny(e.name, "#?") {
			return []*expr{e}
		}
		b := r.binding(st, e.name)
		if b == nil {
			if c, ok := r.v.consts[e.name]; ok {
				return []*expr{num(c)}
			}
			r.no(here, "%s is not a variable the proof can talk about", e.name)
		}
		if len(b.hist) == 0 {
			r.no(here, "%s is a struct, and only its fields have values", e.name)
		}
		return []*expr{b.hist[len(b.hist)-1]}
	case opAnd, opOr:
		l := one(e.args[0])
		g := l
		if e.op == opOr {
			g = not(l)
		}
		rt := r.eval(st, e.args[1], append(guards[:len(guards):len(guards)], g), at)
		return []*expr{mk(e.op, l, rt[0])}
	case opSel:
		arr, idx := one(e.args[0]), one(e.args[1])
		in := mk(opAnd, mk(opLe, num(0), idx), mk(opLt, idx, mk(opLen, arr)))
		r.check(st, guarded(in), nil, here, nil, "the index may be out of range: 0 <= "+e.args[1].String()+" < len("+e.args[0].String()+") is not proved")
		r.assume(st, guarded(in))
		return []*expr{mk(opSel, arr, idx)}
	case opDiv, opMod:
		l, d := one(e.args[0]), one(e.args[1])
		r.check(st, guarded(mk(opNe, d, num(0))), nil, here, nil, "the divisor may be zero: "+e.args[1].String()+" <> 0 is not proved")
		r.assume(st, guarded(mk(opNe, d, num(0))))
		return []*expr{mk(e.op, l, d)}
	case opCall:
		var args []*expr
		for _, x := range e.args {
			args = append(args, one(x))
		}
		return r.call(st, e, args, guards, here)
	}
	c := *e
	c.args = make([]*expr, len(e.args))
	for i, x := range e.args {
		c.args[i] = one(x)
	}
	return []*expr{&c}
}

// point is a position that stands in for a node.
type point token.Pos

func (p point) Pos() token.Pos { return token.Pos(p) }
func (p point) End() token.Pos { return token.Pos(p) + 1 }

// callee finds the declared function a call expression calls.
func (r *run) callee(st *state, c *ast.CallExpr) (*fn, string) {
	switch f := c.Fun.(type) {
	case *ast.Ident:
		if fn := r.v.funcs[f.Name]; fn != nil && fn.recv == nil {
			return fn, ""
		}
	case *ast.SelectorExpr:
		x, ok := f.X.(*ast.Ident)
		if !ok {
			return nil, ""
		}
		if st == nil { // asked only whether the function calls itself
			if r.f.recv != nil && x.Name == r.f.recv.name && r.f.key == r.f.recv.typ+"."+f.Sel.Name {
				return r.f, x.Name
			}
			return nil, ""
		}
		return r.named(st, x.Name+"."+f.Sel.Name)
	}
	return nil, ""
}

// call uses a function by its contract: the precondition is an obligation,
// the postcondition is what is known about the results. A function that is
// one expression is used as that expression, which says more.
func (r *run) call(st *state, e *expr, args []*expr, guards []*expr, at ast.Node) []*expr {
	switch e.name {
	case "min", "max":
		if len(args) != 2 || r.v.funcs[e.name] != nil {
			break
		}
		m := r.fresh(e.name, kInt)
		lo, hi := m, args[0]
		lo2, hi2 := m, args[1]
		if e.name == "max" {
			lo, hi, lo2, hi2 = args[0], m, args[1], m
		}
		r.assume(st, conj([]*expr{mk(opLe, lo, hi), mk(opLe, lo2, hi2), mk(opOr, mk(opEq, m, args[0]), mk(opEq, m, args[1]))}))
		return []*expr{m}
	}
	callee, recv := r.named(st, e.name)
	if callee == nil {
		r.no(at, "%s has no contract the proof could use; only functions of this package can be called", e.name)
	}
	if len(args) != len(callee.params) {
		r.no(at, "%s takes %d arguments", e.name, len(callee.params))
	}
	if !callee.annotated && r.oneLine(callee) == nil {
		// Nobody has checked what it does to the slices and structs it can reach.
		r.no(at, "%s has no annotations, so nothing is known about what it does; give it a contract, even an empty one like Requires true", e.name)
	}
	guarded := func(goal *expr) *expr {
		if len(guards) == 0 {
			return goal
		}
		return mk(opImp, conj(guards), goal)
	}
	// The callee's formulas, in the caller's terms.
	inst := func(a *annot, results []*expr) *expr {
		if a.e == nil {
			return eTrue
		}
		sub := &state{vars: map[string]*binding{}}
		sub.push()
		for i, p := range callee.params {
			if p.kind == kNone {
				continue
			}
			sub.vars[p.name] = &binding{kind: p.kind, typ: p.typ, hist: []*expr{args[i]}}
			if results != nil && p.kind != kSlice {
				// Primed, a parameter is the callee's own copy when it returned,
				// and the caller knows nothing about that.
				sub.vars[p.name].hist = []*expr{r.fresh(p.name, p.kind)}
			}
		}
		if callee.recv != nil && callee.recv.kind == kStruct {
			sub.vars[callee.recv.name] = &binding{kind: kStruct, typ: callee.recv.typ}
			for field := range r.v.structs[callee.recv.typ] {
				if b := r.binding(st, recv+"."+field); b != nil {
					sub.vars[callee.recv.name+"."+field] = b
				}
			}
		}
		for i, p := range callee.results {
			if results != nil {
				sub.vars[p.name] = &binding{kind: p.kind, hist: []*expr{results[i]}}
			}
		}
		inner := &run{v: r.v, f: callee, entry: map[string]*expr{}}
		for i, p := range callee.params {
			if p.kind != kNone && p.kind != kStruct {
				inner.entry[p.name] = args[i]
			}
		}
		defer func() {
			// What goes wrong in the callee's annotation is the callee's problem.
			if p := recover(); p != nil {
				if _, ok := p.(unsupported); !ok {
					panic(p)
				}
				r.no(at, "the contract of %s cannot be used here", e.name)
			}
		}()
		return inner.formula(sub, a, results != nil)
	}
	for _, a := range callee.requires {
		r.check(st, guarded(inst(a, nil)), nil, at, nil, fmt.Sprintf("this call does not establish what %s requires: %s", callee.key, a.text))
	}
	if callee == r.f {
		r.descends(st, e, args, guards, at)
	}
	if body := r.oneLine(callee); body != nil {
		if r.depth++; r.depth > 40 {
			r.no(at, "%s never stops calling itself", callee.key)
		}
		defer func() { r.depth-- }()
		var formals []string
		for _, p := range callee.params {
			formals = append(formals, p.name)
		}
		from := ""
		if callee.recv != nil {
			from = callee.recv.name
		}
		return r.eval(st, replace(body, formals, args, from, recv), guards, at)
	}
	var results []*expr
	for _, p := range callee.results {
		results = append(results, r.fresh(callee.decl.Name.Name+"."+p.name, p.kind))
	}
	for _, a := range callee.ensures {
		r.assume(st, guarded(inst(a, results)))
	}
	for _, a := range callee.exsures {
		r.assume(st, guarded(not(inst(a, results))))
	}
	return results
}

// descends checks a recursive call: the measure is smaller than it was on
// entry and was not negative, and no base case has been passed.
func (r *run) descends(st *state, e *expr, args []*expr, guards []*expr, at ast.Node) {
	guarded := func(goal *expr) *expr {
		if len(guards) == 0 {
			return goal
		}
		return mk(opImp, conj(guards), goal)
	}
	for i, a := range r.f.measure {
		if a.e == nil {
			continue
		}
		sub := &state{vars: map[string]*binding{}}
		for j, p := range r.f.params {
			if p.kind != kNone && p.kind != kStruct {
				sub.vars[p.name] = &binding{kind: p.kind, hist: []*expr{args[j]}}
			}
		}
		m := (&run{v: r.v, f: r.f, entry: map[string]*expr{}}).formula(sub, a, false)
		r.check(st, guarded(mk(opLt, m, r.measure0[i])), a, nil, at, "Measure is not shown to get smaller in the recursive call at {ref}")
		r.check(st, guarded(mk(opLe, num(0), r.measure0[i])), a, nil, at, "Measure can be negative when the recursive call at {ref} is made")
	}
	for _, b := range st.base {
		r.check(st, guarded(not(b)), nil, at, nil, "this recursive call can be reached in the base case")
	}
}

// block runs the statements of a block, with the annotations between them.
func (r *run) block(st *state, b *ast.BlockStmt) outcomes {
	st.push()
	depth := len(st.scopes)
	var out outcomes
	live := []*state{st}
	notes := r.blocks[b]
	n := 0
	for i := 0; i <= len(b.List); i++ {
		var next ast.Stmt
		limit := b.Rbrace
		if i < len(b.List) {
			next = b.List[i]
			limit = next.Pos()
		}
		var pending []*annot
		for n < len(notes) && notes[n].pos < limit {
			a := notes[n]
			n++
			if a.kind == "Invariant" || a.kind == "Variant" {
				if isLoop(next) {
					pending = append(pending, a)
				}
				continue // at the end of a loop's body it belongs to that loop
			}
			for _, s := range live {
				r.note(s, a)
			}
		}
		if next == nil {
			break
		}
		var after []*state
		for _, s := range live {
			o := r.stmt(s, next, pending)
			after = append(after, o.normal...)
			out.brk = append(out.brk, o.brk...)
			out.cont = append(out.cont, o.cont...)
		}
		live = after
		if r.paths += len(live); r.paths > maxPaths*50 || len(live) > maxPaths {
			r.no(next, "there are too many paths through it")
		}
	}
	for _, s := range live {
		s.popTo(depth - 1)
	}
	out.normal = live
	return out
}

func isLoop(s ast.Stmt) bool {
	switch s.(type) {
	case *ast.ForStmt, *ast.RangeStmt:
		return true
	}
	return false
}

// note handles an annotation that stands where a statement could.
func (r *run) note(st *state, a *annot) {
	a.used = true
	if a.e == nil {
		return
	}
	switch a.kind {
	case "Assert", "InductionHypothesis":
		f := r.formula(st, a, false)
		r.check(st, f, a, nil, nil, a.kind+" is not proved: "+a.text)
		r.assume(st, f)
	case "Axiom":
		r.v.report(a.where, a.endCol, true, "Axiom is taken on trust, not proved: "+a.text)
		r.assume(st, r.formula(st, a, false))
	case "Preserves":
		f := r.formula(st, a, false)
		r.check(st, f, a, nil, nil, "Preserves does not hold to begin with: "+a.text)
		r.assume(st, f)
		st.preserved = append(st.preserved, kept{a, len(st.scopes)})
	case "BaseCase":
		st.base = append(st.base, r.formula(st, a, false))
	case "Immutable":
	default:
		r.v.report(a.where, a.endCol, false, a.kind+" does not belong inside a function body")
	}
}

func (r *run) stmt(st *state, s ast.Stmt, pending []*annot) outcomes {
	switch s := s.(type) {
	case *ast.EmptyStmt:
		return outcomes{normal: []*state{st}}
	case *ast.BlockStmt:
		return r.block(st, s)
	case *ast.DeclStmt:
		g, ok := s.Decl.(*ast.GenDecl)
		if !ok || g.Tok != token.VAR {
			r.no(s, "only variables can be declared inside a verified function")
		}
		for _, spec := range g.Specs {
			vs := spec.(*ast.ValueSpec)
			for i, n := range vs.Names {
				var val *expr
				k := kNone
				if vs.Type != nil {
					k, _ = r.v.kindOf(vs.Type)
				}
				if i < len(vs.Values) {
					val = r.value(st, vs.Values[i])
					if k == kNone {
						k = kInt
						if isBool(val) {
							k = kBool
						}
					}
				} else if k == kInt {
					val = num(0)
				} else if k == kBool {
					val = eFalse
				}
				if val == nil || k != kInt && k != kBool {
					r.no(s, "%s is neither an integer nor a boolean", n.Name)
				}
				st.declare(n.Name, &binding{kind: k, hist: []*expr{val}})
			}
		}
		return outcomes{normal: []*state{st}}
	case *ast.AssignStmt:
		r.assign(st, s)
		return outcomes{normal: []*state{st}}
	case *ast.IncDecStmt:
		one := mk(opAdd, r.value(st, s.X), num(1))
		if s.Tok == token.DEC {
			one.op = opSub
		}
		r.set(st, s.X, one, s)
		return outcomes{normal: []*state{st}}
	case *ast.ExprStmt:
		r.effect(st, s)
		return outcomes{normal: []*state{st}}
	case *ast.ReturnStmt:
		r.ret(st, s)
		return outcomes{}
	case *ast.BranchStmt:
		if s.Label != nil {
			r.no(s, "labels are outside what litgo prove understands")
		}
		switch s.Tok {
		case token.BREAK:
			return outcomes{brk: []*state{st}}
		case token.CONTINUE:
			return outcomes{cont: []*state{st}}
		}
	case *ast.IfStmt:
		return r.branch(st, s)
	case *ast.ForStmt:
		return r.loop(st, &loop{stmt: s, init: s.Init, cond: s.Cond, post: s.Post, body: s.Body}, pending)
	case *ast.RangeStmt:
		return r.loop(st, &loop{stmt: s, over: s, body: s.Body}, pending)
	}
	r.no(s, "this statement is outside what litgo prove understands")
	return outcomes{}
}

// effect is a call made for what it does. A call of a verified function is
// checked like any other. A call of anything else is let through if all it
// is handed are numbers, booleans and literals, because then it cannot
// change anything the proof is about. panic ends the path.
func (r *run) effect(st *state, s *ast.ExprStmt) {
	c, ok := s.X.(*ast.CallExpr)
	if !ok {
		r.no(s, "this statement is outside what litgo prove understands")
	}
	if id, ok := c.Fun.(*ast.Ident); ok && id.Name == "panic" {
		r.assume(st, eFalse)
		return
	}
	if callee, _ := r.callee(st, c); callee != nil {
		r.eval(st, r.pure(c, func(name string) vkind {
			if b := r.binding(st, name); b != nil {
				return b.kind
			}
			return kNone
		}), nil, c)
		return
	}
	if sel, ok := c.Fun.(*ast.SelectorExpr); ok {
		if x, ok := sel.X.(*ast.Ident); ok && st.vars[x.Name] != nil {
			r.no(c, "%s.%s has no contract, and a method may change what it is called on", x.Name, sel.Sel.Name)
		}
	}
	for _, a := range c.Args {
		if lit, ok := a.(*ast.BasicLit); ok && lit.Kind != token.INT {
			continue
		}
		if v := r.value(st, a); v.sort == sArr {
			r.no(a, "a slice handed to a function without a contract may come back changed")
		}
	}
}

func (r *run) assign(st *state, s *ast.AssignStmt) {
	ops := map[token.Token]op{token.ADD_ASSIGN: opAdd, token.SUB_ASSIGN: opSub, token.MUL_ASSIGN: opMul,
		token.QUO_ASSIGN: opDiv, token.REM_ASSIGN: opMod}
	if o, ok := ops[s.Tok]; ok {
		bin := &ast.BinaryExpr{X: s.Lhs[0], OpPos: s.TokPos, Y: s.Rhs[0],
			Op: map[op]token.Token{opAdd: token.ADD, opSub: token.SUB, opMul: token.MUL, opDiv: token.QUO, opMod: token.REM}[o]}
		r.set(st, s.Lhs[0], r.value(st, bin), s)
		return
	}
	if s.Tok != token.ASSIGN && s.Tok != token.DEFINE {
		r.no(s, "this assignment is outside what litgo prove understands")
	}
	var vals []*expr
	if len(s.Rhs) == 1 && len(s.Lhs) > 1 {
		c, ok := s.Rhs[0].(*ast.CallExpr)
		if !ok {
			r.no(s, "only a call can give several values at once")
		}
		vals = r.eval(st, r.pure(c, func(name string) vkind {
			if b := r.binding(st, name); b != nil {
				return b.kind
			}
			return kNone
		}), nil, c)
	} else {
		for _, x := range s.Rhs {
			vals = append(vals, r.value(st, x))
		}
	}
	if len(vals) != len(s.Lhs) {
		r.no(s, "the two sides of this assignment do not match")
	}
	for i, l := range s.Lhs {
		id, ok := l.(*ast.Ident)
		if s.Tok == token.DEFINE && ok && (st.vars[id.Name] == nil || !r.inScope(st, id.Name)) {
			k := kInt
			if isBool(vals[i]) {
				k = kBool
			} else if vals[i].sort == sArr {
				r.no(s, "slices cannot be copied inside a verified function")
			}
			st.declare(id.Name, &binding{kind: k, hist: []*expr{vals[i]}})
			continue
		}
		r.store(st, l, vals[i])
	}
	// A parallel assignment is one step: what is preserved is looked at
	// once all of it has happened.
	r.keep(st, s)
}

// inScope reports whether a name was declared in the innermost block, which
// is what decides whether := declares it again.
func (r *run) inScope(st *state, name string) bool {
	_, ok := st.scopes[len(st.scopes)-1][name]
	return ok
}

// set assigns to a variable, and then looks at what was promised to be
// preserved.
func (r *run) set(st *state, target ast.Expr, val *expr, at ast.Node) {
	r.store(st, target, val)
	r.keep(st, at)
}

func (r *run) store(st *state, target ast.Expr, val *expr) {
	id, ok := target.(*ast.Ident)
	if !ok {
		r.no(target, "only variables can be assigned to: an element of a slice or a field may have other names, and the proof would not see them change")
	}
	if id.Name == "_" {
		return
	}
	b := st.vars[id.Name]
	if b == nil || b.kind != kInt && b.kind != kBool {
		r.no(target, "%s is not an integer or boolean variable", id.Name)
	}
	b.hist = append(b.hist, val)
}

func (r *run) keep(st *state, at ast.Node) {
	for _, k := range st.preserved {
		f := r.formula(st, k.a, false)
		r.check(st, f, k.a, nil, at, "Preserves is broken by the assignment at {ref}: "+k.a.text)
		r.assume(st, f)
	}
}

func (r *run) branch(st *state, s *ast.IfStmt) outcomes {
	st.push()
	depth := len(st.scopes)
	var out outcomes
	starts := []*state{st}
	if s.Init != nil {
		starts = r.stmt(st, s.Init, nil).normal
	}
	for _, st := range starts {
		cond := r.value(st, s.Cond)
		yes, no := st, st.clone()
		r.assume(yes, cond)
		r.assume(no, not(cond))
		if r.feasible(yes) {
			out.add(r.block(yes, s.Body))
		}
		if r.feasible(no) {
			switch e := s.Else.(type) {
			case nil:
				out.normal = append(out.normal, no)
			case *ast.BlockStmt:
				out.add(r.block(no, e))
			case *ast.IfStmt:
				out.add(r.branch(no, e))
			}
		}
	}
	for _, s := range out.normal {
		s.popTo(depth - 1)
	}
	return out
}

// ret settles a return: the results get their values, and every
// postcondition is an obligation.
func (r *run) ret(st *state, s *ast.ReturnStmt) {
	if len(s.Results) > 0 {
		var vals []*expr
		if len(s.Results) == 1 && len(r.f.results) > 1 {
			c, ok := s.Results[0].(*ast.CallExpr)
			if !ok {
				r.no(s, "only a call can give several values at once")
			}
			vals = r.eval(st, r.pure(c, func(name string) vkind {
				if b := r.binding(st, name); b != nil {
					return b.kind
				}
				return kNone
			}), nil, c)
		} else {
			for _, x := range s.Results {
				vals = append(vals, r.value(st, x))
			}
		}
		if len(vals) != len(r.f.results) {
			r.no(s, "this return does not match the results")
		}
		// The results may be shadowed here; a return assigns the real ones.
		for i, p := range r.f.results {
			st.vars[p.name] = &binding{kind: p.kind, hist: []*expr{vals[i]}}
		}
	}
	r.leave(st, s.Pos())
}

func (r *run) leave(st *state, at token.Pos) {
	for _, a := range r.f.ensures {
		if a.e != nil {
			r.check(st, r.formula(st, a, true), a, nil, point(at), "Ensures is not proved for the return at {ref}: "+a.text)
		}
	}
	for _, a := range r.f.exsures {
		if a.e != nil {
			r.check(st, not(r.formula(st, a, true)), a, nil, point(at), "Exsures is not ruled out for the return at {ref}: "+a.text)
		}
	}
}

// loop is a for statement, or a range statement read as one.
type loop struct {
	stmt ast.Stmt
	init ast.Stmt
	cond ast.Expr
	post ast.Stmt
	body *ast.BlockStmt
	over *ast.RangeStmt
}

// loop cuts a loop at its invariant. The invariant is proved on entry;
// then everything the loop assigns is forgotten, the invariant is assumed,
// and one iteration has to give it back, with a smaller variant. What
// follows the loop knows the invariant and that the condition is false.
func (r *run) loop(st *state, l *loop, pending []*annot) outcomes {
	var invs, vars []*annot
	notes := append(append([]*annot{}, pending...), r.trailing(l.body)...)
	for _, a := range notes {
		a.used = true
		if a.e == nil {
			continue
		}
		if a.kind == "Invariant" {
			invs = append(invs, a)
		} else {
			vars = append(vars, a)
		}
	}
	if len(vars) == 0 && l.over == nil {
		r.v.report(r.v.position(l.stmt.Pos()), r.v.position(l.stmt.Pos()).Col+3, true, "this loop has no Variant, so nothing shows that it terminates")
	}
	st.push()
	depth := len(st.scopes)
	var out outcomes
	starts := []*state{st}
	var index string // the counter of a range loop
	var bound *expr
	if l.over != nil {
		index, bound = r.rangeStart(st, l.over)
	} else if l.init != nil {
		starts = r.stmt(st, l.init, nil).normal
	}
	for _, s0 := range starts {
		for _, a := range invs {
			r.check(s0, r.formula(s0, a, false), a, nil, l.stmt, "Invariant does not hold when the loop at {ref} is entered: "+a.text)
		}
		head := s0.clone()
		for _, name := range r.assigned(l) {
			if b := head.vars[name]; b != nil && (b.kind == kInt || b.kind == kBool) {
				b.hist = []*expr{r.fresh(name, b.kind)}
			}
		}
		if index != "" {
			b := head.vars[index]
			b.hist = []*expr{r.fresh(index, kInt)}
			r.assume(head, mk(opAnd, mk(opLe, num(0), b.hist[0]), mk(opLe, b.hist[0], bound)))
		}
		for _, a := range invs {
			r.assume(head, r.formula(head, a, false))
		}
		for _, k := range head.preserved {
			r.assume(head, r.formula(head, k.a, false))
		}
		var cond *expr
		switch {
		case index != "":
			cond = mk(opLt, head.vars[index].hist[0], bound)
		case l.cond != nil:
			cond = r.value(head, l.cond)
		default:
			cond = eTrue
		}
		exit := head.clone()
		r.assume(exit, not(cond))
		if r.feasible(exit) {
			out.normal = append(out.normal, exit)
		}
		body := head
		r.assume(body, cond)
		if !r.feasible(body) {
			continue
		}
		var before []*expr
		for _, a := range vars {
			m := r.formula(body, a, false)
			before = append(before, m)
			r.check(body, mk(opLe, num(0), m), a, nil, nil, "Variant can be negative while the loop still runs: "+a.text)
		}
		if l.over != nil && l.over.Value != nil {
			if id, ok := l.over.Value.(*ast.Ident); ok && id.Name != "_" {
				body.push()
				arr := r.value(body, l.over.X)
				body.declare(id.Name, &binding{kind: kInt, hist: []*expr{mk(opSel, arr, body.vars[index].hist[0])}})
			}
		}
		o := r.block(body, l.body)
		out.normal = append(out.normal, o.brk...)
		for _, s := range append(o.normal, o.cont...) {
			s.popTo(depth)
			ends := []*state{s}
			if index != "" {
				b := s.vars[index]
				b.hist = append(b.hist, mk(opAdd, b.hist[len(b.hist)-1], num(1)))
			} else if l.post != nil {
				ends = r.stmt(s, l.post, nil).normal
			}
			for _, s := range ends {
				for _, a := range invs {
					r.check(s, r.formula(s, a, false), a, nil, l.stmt, "Invariant is not maintained by the body of the loop at {ref}: "+a.text)
				}
				for i, a := range vars {
					r.check(s, mk(opLt, r.formula(s, a, false), before[i]), a, nil, l.stmt, "Variant is not shown to decrease in the loop at {ref}: "+a.text)
				}
			}
		}
	}
	for _, s := range out.normal {
		s.popTo(depth - 1)
	}
	return out
}

// trailing finds the Invariant and Variant lines written inside a loop's
// body rather than above the loop: the ones no inner loop follows.
func (r *run) trailing(body *ast.BlockStmt) []*annot {
	var out []*annot
	for _, a := range r.blocks[body] {
		if a.kind != "Invariant" && a.kind != "Variant" {
			continue
		}
		var next ast.Stmt
		for _, s := range body.List {
			if s.Pos() > a.pos {
				next = s
				break
			}
		}
		if !isLoop(next) {
			out = append(out, a)
		}
	}
	return out
}

// rangeStart declares the counter of a range loop, under the name the
// program gives it if it gives it one, and finds where the counting stops.
func (r *run) rangeStart(st *state, s *ast.RangeStmt) (string, *expr) {
	if s.Tok == token.ASSIGN {
		r.no(s, "a range loop has to declare its variables with :=")
	}
	index := "range counter"
	if id, ok := s.Key.(*ast.Ident); ok && id.Name != "_" {
		index = id.Name
	}
	for _, name := range r.assigned(&loop{body: s.Body}) {
		if name == index {
			r.no(s, "the body assigns to the loop's own counter")
		}
	}
	var bound *expr
	if id, ok := s.X.(*ast.Ident); ok {
		if b := r.binding(st, id.Name); b != nil && b.kind == kSlice {
			bound = mk(opLen, b.hist[0])
		}
	}
	if sel, ok := s.X.(*ast.SelectorExpr); ok && bound == nil {
		if x, ok := sel.X.(*ast.Ident); ok {
			if b := r.binding(st, x.Name+"."+sel.Sel.Name); b != nil && b.kind == kSlice {
				bound = mk(opLen, b.hist[0])
			}
		}
	}
	if bound == nil {
		if s.Value != nil {
			r.no(s, "only a slice of integers or an integer can be ranged over")
		}
		bound = r.value(st, s.X)
		if isBool(bound) || bound.sort == sArr {
			r.no(s, "only a slice of integers or an integer can be ranged over")
		}
	}
	st.declare(index, &binding{kind: kInt, hist: []*expr{num(0)}})
	return index, bound
}

// assigned lists the variables a loop can change.
func (r *run) assigned(l *loop) []string {
	seen := map[string]bool{}
	visit := func(n ast.Node) bool {
		switch s := n.(type) {
		case *ast.AssignStmt:
			for _, x := range s.Lhs {
				if id, ok := x.(*ast.Ident); ok {
					seen[id.Name] = true
				}
			}
		case *ast.IncDecStmt:
			if id, ok := s.X.(*ast.Ident); ok {
				seen[id.Name] = true
			}
		case *ast.RangeStmt:
			for _, x := range []ast.Expr{s.Key, s.Value} {
				if id, ok := x.(*ast.Ident); ok {
					seen[id.Name] = true
				}
			}
		}
		return true
	}
	ast.Inspect(l.body, visit)
	if l.post != nil {
		ast.Inspect(l.post, visit)
	}
	out := make([]string, 0, len(seen))
	for n := range seen {
		out = append(out, n)
	}
	sort.Strings(out)
	return out
}
