// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

#set document(title: lit-title)
#set page(paper: "a4", margin: (x: 2.3cm, top: 2.4cm, bottom: 2.6cm), numbering: "1")
#set text(font: "Libertinus Serif", size: 10.5pt)
#set par(justify: true)
#show heading: set block(above: 1.8em, below: 0.9em)
#show heading.where(level: 1): it => {
  if it.outlined { pagebreak(weak: true) } // but not before "Contents"
  set text(size: 1.3em)
  it
}
#show link: set text(fill: rgb("#0a58ca"))
#set table(stroke: none, inset: (x: 6pt, y: 4pt))
#show figure.where(kind: table): set block(breakable: true)
#show figure.where(kind: table): set par(justify: false)

#let divider() = line(length: 100%, stroke: 0.5pt + luma(170))
#let horizontalrule = divider()

#show raw: set text(font: "DejaVu Sans Mono")
#show raw.where(block: false): set text(size: 0.92em)
#show raw.where(block: true): it => {
  set par(justify: false)
  if it.lang == "diagram" {
    // Lines set solid, so that box-drawing characters join up.
    set par(leading: 0pt)
    set text(size: 7.5pt, top-edge: "ascender", bottom-edge: "descender")
    align(center, block(breakable: false, above: 1.4em, below: 1.4em, it))
  } else {
    block(width: 100%, fill: luma(246), radius: 3pt, inset: (x: 8pt, y: 7pt), text(size: 7.8pt, it))
  }
}

#let lit-literal = state("lit-literal", false)
#let lit-reference = regex("<<\\s*([^<>]+?)\\s*>>")
#let lit-slug(name) = "chunk-" + lower(name).replace(regex("[^a-z0-9]+"), "-").trim("-")
#let lit-name(name) = text(font: "Libertinus Serif", style: "italic", size: 1.2em)[⟨#name⟩]
#let lit-link(id, name) = if id in lit-chunks { link(label(id), lit-name(name)) } else { lit-name(name) }

#show raw.where(block: true): it => {
  show lit-reference: found => context {
    if lit-literal.get() { found } else {
      let name = found.text.match(lit-reference).captures.at(0).replace(regex("\\s+"), " ")
      lit-link(lit-slug(name), name)
    }
  }
  it
}

#let lit-chunk(id, name, sign, uses) = {
  let where = if uses.len() == 0 { [never used] } else {
    [used in ] + uses.map(u => if u.at(0) == "" { u.at(1) } else { lit-link(u.at(0), u.at(1)) }).join(", ")
  }
  let head = block(above: 1.5em, below: 0.5em, sticky: true, {
    lit-name(name) + h(0.4em) + text(size: 1.2em, sign) + h(1fr) + text(size: 8pt, fill: luma(110), where)
  })
  if id == "" { head } else [#head #label(id)]
}

#let lit-file(path) = block(above: 2.2em, below: 1em, sticky: true, {
  line(length: 100%, stroke: 0.5pt + luma(170))
  v(-0.4em)
  text(font: "DejaVu Sans Mono", size: 8.5pt, weight: "bold", fill: luma(90), "▸ " + path)
})

#block(below: 0.8em, text(size: 22pt, weight: "bold", lit-title))
#block(below: 2em, text(size: 9pt, fill: luma(110), lit-summary))

#if lit-contents {
  outline(depth: 2, indent: auto)
  pagebreak(weak: true)
}
