// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package weave

import (
	_ "embed"
	"fmt"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/tlehman/litgo/internal/lit"
)

func rawTypst(code string) string { return "```{=typst}\n" + code + "\n```\n" }

// typstString writes s as a Typst string literal.
func typstString(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`).Replace(s) + `"`
}

var typstTarget = target{
	chunk: func(id, name, sign string, uses []use) string {
		var pairs strings.Builder
		for _, u := range uses {
			pairs.WriteString("(" + typstString(u.ID) + ", " + typstString(u.Name) + "), ")
		}
		return rawTypst(fmt.Sprintf("#lit-chunk(%s, %s, %s, (%s))", typstString(id), typstString(name), typstString(sign), pairs.String()))
	},
	file: func(path string) string { return rawTypst("#lit-file(" + typstString(path) + ")") },
	literal: [2]string{
		rawTypst("#lit-literal.update(true)"),
		rawTypst("#lit-literal.update(false)"),
	},
	diagrams:  true,
	dropTitle: true,
}

//go:embed preamble.typ
var preamble string

// Typst returns the document as Typst markup.
func Typst(d *lit.Doc) (string, error) {
	body, err := pandoc(weave(d, typstTarget), "--to", "typst")
	if err != nil {
		return "", err
	}
	var anchors strings.Builder
	chapters := 0
	for _, c := range d.Chunks() {
		if len(c.Blocks) > 0 {
			anchors.WriteString(typstString(slug(c.Name)) + ", ")
		}
	}
	for i, l := range d.Lines {
		if strings.HasPrefix(l, "# ") && d.BlockAt(i) == nil {
			chapters++
		}
	}
	var sb strings.Builder
	fmt.Fprintf(&sb, "#let lit-title = %s\n", typstString(Title(d)))
	fmt.Fprintf(&sb, "#let lit-summary = %s\n", typstString(Summary(d)))
	fmt.Fprintf(&sb, "#let lit-chunks = (%s)\n", anchors.String())
	fmt.Fprintf(&sb, "#let lit-contents = %t\n", chapters > 1)
	sb.WriteString(preamble)
	sb.Write(body)
	return sb.String(), nil
}

// PDF weaves through Typst. The source goes in on standard input and the
// document's directory is the root, so images it refers to are found.
func PDF(d *lit.Doc, out string) error {
	src, err := Typst(d)
	if err != nil {
		return err
	}
	bin, err := exec.LookPath("typst")
	if err != nil {
		return fmt.Errorf("typst is not installed (https://typst.app); `litgo weave --to html` needs only pandoc")
	}
	cmd := exec.Command(bin, "compile", "--root", filepath.Dir(d.Path), "-", out)
	cmd.Dir = filepath.Dir(d.Path)
	cmd.Stdin = strings.NewReader(src)
	if msg, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("typst: %v\n%s\n(`litgo weave --to typ` writes the source for a closer look)", err, msg)
	}
	return nil
}
