// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package weave

import (
	"fmt"
	"html"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/tlehman/litgo/internal/lit"
	"github.com/tlehman/litgo/internal/mermaid"
)

var slugRe = regexp.MustCompile(`[^a-z0-9]+`)

// slug is the anchor of a chunk, the same in every format.
func slug(name string) string {
	return "chunk-" + strings.Trim(slugRe.ReplaceAllString(strings.ToLower(name), "-"), "-")
}

// use is a place a chunk is referenced from. An empty ID is the program
// itself: an unnamed block.
type use struct{ ID, Name string }

// target is how one output format writes the things litgo adds.
type target struct {
	chunk     func(id, name, sign string, uses []use) string
	file      func(path string) string
	meta      func(text string) string // goes under the title; nil leaves it out
	literal   [2]string                // put around blocks whose references are only text
	diagrams  bool                     // draw Mermaid here: the format cannot run mermaid.js
	figure    func(svg string) string  // places a diagram that mermaid.js drew
	figures   map[int]string           // those drawings, by the line their block opens on
	dropTitle bool                     // the format sets the title itself
}

func weave(d *lit.Doc, t target) string {
	before, replace, after := map[int]string{}, map[int]string{}, map[int]string{}
	until := map[int]int{} // a replacement at line i stands for lines i to until[i]

	usedIn := map[string][]use{}
	for _, c := range d.Chunks() {
		seen := map[string]bool{}
		for _, r := range c.Refs {
			u := use{Name: "the program"}
			if b := d.BlockAt(r.Line); b != nil && b.Chunk != "" {
				u = use{slug(b.Chunk), b.Chunk}
			}
			if !seen[u.Name] {
				seen[u.Name] = true
				usedIn[c.Name] = append(usedIn[c.Name], u)
			}
		}
	}
	count := map[string]int{}
	for _, b := range d.Blocks {
		if b.Chunk == "" || !b.Tangled() {
			continue
		}
		count[b.Chunk]++
		id, sign := slug(b.Chunk), "≡"
		if count[b.Chunk] > 1 {
			id, sign = "", "+≡"
		}
		replace[b.ChunkLine] = t.chunk(id, b.Chunk, sign, usedIn[b.Chunk])
	}
	for _, f := range d.Files[1:] {
		replace[f.Line] = t.file(f.Path)
	}
	if t.diagrams {
		for _, b := range d.Blocks {
			if b.Lang != "mermaid" || b.Strip > 0 {
				continue
			}
			if svg, ok := t.figures[b.Open]; ok {
				replace[b.Open], until[b.Open] = t.figure(svg), b.Close
				continue
			}
			lines, err := mermaid.Render(strings.Join(d.Lines[b.First():b.Last()+1], "\n"))
			if err != nil {
				continue
			}
			replace[b.Open], until[b.Open] = "```diagram\n"+strings.Join(lines, "\n")+"\n```\n", b.Close
		}
	}
	if t.literal[0] != "" {
		for _, b := range d.Blocks {
			if (b.Tangled() && !b.Verbatim) || b.Strip > 0 {
				continue
			}
			if _, drawn := replace[b.Open]; drawn {
				continue
			}
			for i := b.First(); i <= b.Last(); i++ {
				if len(lit.RefsIn(d.Lines[i], i)) > 0 {
					before[b.Open] += t.literal[0]
					after[min(b.Close, len(d.Lines)-1)] += t.literal[1]
					break
				}
			}
		}
	}
	title := titleLine(d)
	if title >= 0 && t.dropTitle {
		replace[title] = ""
	}
	if t.meta != nil {
		if title >= 0 {
			after[title] += "\n" + t.meta(Summary(d))
		} else {
			before[0] = t.meta(Summary(d)) + "\n" + before[0]
		}
	}

	var sb strings.Builder
	for i := 0; i < len(d.Lines); i++ {
		sb.WriteString(before[i])
		if r, ok := replace[i]; ok {
			sb.WriteString(r)
			i = max(i, until[i])
			continue
		}
		sb.WriteString(d.Lines[i] + "\n")
		sb.WriteString(after[i])
	}
	return sb.String()
}

// drawn returns the SVG of each Mermaid block that mermaid-cli could draw,
// by the line the block opens on.
func drawn(d *lit.Doc) map[int]string {
	var at []int
	var srcs []string
	for _, b := range d.Blocks {
		if b.Lang == "mermaid" && b.Strip == 0 {
			at = append(at, b.Open)
			srcs = append(srcs, strings.Join(d.Lines[b.First():b.Last()+1], "\n"))
		}
	}
	if len(srcs) == 0 {
		return nil
	}
	bin, err := exec.LookPath("mmdc")
	if err != nil {
		fmt.Fprintln(os.Stderr, "litgo: mmdc is not installed (npm install -g @mermaid-js/mermaid-cli), so diagrams are drawn as text")
		return nil
	}
	svgs := mmdc(bin, srcs)
	if svgs == nil && len(srcs) > 1 {
		svgs = make([]string, len(srcs))
		for i, src := range srcs {
			if one := mmdc(bin, []string{src}); one != nil {
				svgs[i] = one[0]
			}
		}
	}
	figures := map[int]string{}
	for i, svg := range svgs {
		if svg != "" {
			figures[at[i]] = svg
		}
	}
	return figures
}

// mmdc draws every diagram in one run of mermaid-cli, or returns nil.
func mmdc(bin string, srcs []string) []string {
	dir, err := os.MkdirTemp("", "litgo-mermaid")
	if err != nil {
		return nil
	}
	defer os.RemoveAll(dir)
	var md strings.Builder
	for _, src := range srcs {
		md.WriteString("```mermaid\n" + src + "\n```\n\n")
	}
	os.WriteFile(filepath.Join(dir, "in.md"), []byte(md.String()), 0o644)
	os.WriteFile(filepath.Join(dir, "config.json"), []byte(`{"htmlLabels": false, "flowchart": {"htmlLabels": false}}`), 0o644)
	cmd := exec.Command(bin, "-i", "in.md", "-o", "out.svg", "-c", "config.json", "-b", "transparent", "-q")
	cmd.Dir = dir
	if err := cmd.Run(); err != nil {
		return nil
	}
	svgs := make([]string, len(srcs))
	for i := range srcs {
		svg, err := os.ReadFile(filepath.Join(dir, fmt.Sprintf("out-%d.svg", i+1)))
		if err != nil {
			return nil
		}
		svgs[i] = string(svg)
	}
	return svgs
}

// titleLine is the line of the first top-level heading, or -1.
func titleLine(d *lit.Doc) int {
	for i, l := range d.Lines {
		if strings.HasPrefix(l, "# ") && d.BlockAt(i) == nil {
			return i
		}
	}
	return -1
}

// Title is the first top-level heading, or the file name.
func Title(d *lit.Doc) string {
	if i := titleLine(d); i >= 0 {
		return strings.TrimSpace(d.Lines[i][2:])
	}
	return filepath.Base(d.Path)
}

// Summary says in a line what the document tangles to.
func Summary(d *lit.Doc) string {
	def := d.Files[0]
	if len(d.Files) > 1 {
		return fmt.Sprintf("tangles to %d files", len(d.Tangle().Files))
	}
	var parts []string
	if def.Package != "" {
		parts = append(parts, "package "+def.Package)
	}
	if len(def.Imports) > 0 {
		var names []string
		for _, imp := range def.Imports {
			names = append(names, imp.Path)
		}
		parts = append(parts, "imports "+strings.Join(names, ", "))
	}
	parts = append(parts, "tangles to "+filepath.Base(d.OutPath(def)))
	return strings.Join(parts, " · ")
}

func pandoc(markdown string, args ...string) ([]byte, error) {
	bin, err := exec.LookPath("pandoc")
	if err != nil {
		return nil, fmt.Errorf("pandoc is not installed; `litgo weave --to md` needs nothing, everything else needs pandoc")
	}
	args = append([]string{"--from", "markdown+tex_math_dollars+tex_math_single_backslash-implicit_figures"}, args...)
	cmd := exec.Command(bin, args...)
	cmd.Stdin = strings.NewReader(markdown)
	var stderr strings.Builder
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("pandoc: %v\n%s", err, stderr.String())
	}
	return out, nil
}

var htmlTarget = target{
	chunk: func(id, name, sign string, uses []use) string {
		if id != "" {
			id = ` id="` + id + `"`
		}
		var places []string
		for _, u := range uses {
			if u.ID == "" {
				places = append(places, u.Name)
			} else {
				places = append(places, fmt.Sprintf(`<a href="#%s">⟨%s⟩</a>`, u.ID, html.EscapeString(u.Name)))
			}
		}
		where := "never used"
		if len(places) > 0 {
			where = "used in " + strings.Join(places, ", ")
		}
		return fmt.Sprintf(`<div class="lit-chunk"%s><span class="lit-name">⟨%s⟩ %s</span> <span class="lit-uses">%s</span></div>`+"\n",
			id, html.EscapeString(name), sign, where)
	},
	file: func(path string) string {
		return `<div class="lit-file">` + html.EscapeString(path) + "</div>\n"
	},
	meta: func(text string) string {
		return `<div class="lit-meta">` + html.EscapeString(text) + "</div>\n"
	},
}

// Markdown returns the woven Markdown, with litgo's additions as HTML.
func Markdown(d *lit.Doc) string { return weave(d, htmlTarget) }

// HTML weaves a standalone page.
func HTML(d *lit.Doc, out string) error {
	tmp, err := os.MkdirTemp("", "litgo-weave")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)
	header := filepath.Join(tmp, "header.html")
	if err := os.WriteFile(header, []byte(headerHTML), 0o644); err != nil {
		return err
	}
	_, err = pandoc(Markdown(d), "--to", "html5", "--standalone", "--katex",
		"--metadata", "pagetitle="+Title(d), "--include-in-header", header, "--output", out)
	return err
}

const headerHTML = `<style>
:root { --fg:#1f2328; --bg:#ffffff; --muted:#656d76; --accent:#0a58ca; --code-bg:#f6f8fa; --rule:#d0d7de; }
@media (prefers-color-scheme: dark) {
  :root { --fg:#e6edf3; --bg:#0d1117; --muted:#8b949e; --accent:#79b8ff; --code-bg:#161b22; --rule:#30363d; }
}
html { color: var(--fg); background: var(--bg); }
body { max-width: 46em; margin: 0 auto; padding: 2.5em 1em 6em; font: 17px/1.6 Georgia, "Iowan Old Style", serif; }
h1, h2, h3 { font-family: system-ui, sans-serif; line-height: 1.25; }
h2 { margin-top: 2.2em; border-bottom: 1px solid var(--rule); padding-bottom: .2em; }
a { color: var(--accent); text-decoration: none; } a:hover { text-decoration: underline; }
code { font: 0.86em/1.5 "JetBrains Mono", ui-monospace, Menlo, monospace; }
pre, div.sourceCode { background: var(--code-bg); border-radius: 6px; }
pre { padding: .8em 1em; overflow-x: auto; margin: 0; }
div.sourceCode { margin: 0 0 1.2em; }
.lit-meta { color: var(--muted); font: 14px system-ui, sans-serif; margin: -0.6em 0 2em; }
.lit-chunk { font: 15px system-ui, sans-serif; margin: 1.4em 0 .3em; display: flex; justify-content: space-between; gap: 1em; align-items: baseline; }
.lit-name { font-weight: 600; font-style: italic; }
.lit-file { font: 600 13px "JetBrains Mono", ui-monospace, monospace; color: var(--muted); border-top: 1px solid var(--rule); margin: 2.4em 0 1em; padding-top: .5em; }
.lit-file::before { content: "▸ "; }
.lit-uses { color: var(--muted); font-size: 13px; }
a.lit-ref { font-style: italic; font-family: Georgia, serif; }
:target { scroll-margin-top: 1em; } .lit-chunk:target .lit-name { background: color-mix(in srgb, var(--accent) 22%, transparent); }
pre.mermaid { background: transparent; text-align: center; }
@media (prefers-color-scheme: dark) { pre.sourceCode span { filter: brightness(1.7) saturate(.8); } }
</style>
<script type="module">
// Chunk references are ordinary Go comments in the source; here they become
// links to the definition.
const slug = s => 'chunk-' + s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
for (const span of document.querySelectorAll('pre code span.co, pre code span.cm')) {
  const m = span.textContent.match(/^\s*(?:\/\/|\/\*|--\[\[|--|#)\s*<<\s*(.+?)\s*>>\s*(?:\*\/|\]\])?\s*$/);
  if (!m) continue;
  const a = document.createElement('a');
  a.className = 'lit-ref'; a.href = '#' + slug(m[1].replace(/\s+/g, ' ')); a.textContent = '⟨' + m[1] + '⟩';
  span.replaceChildren(a);
}
const diagrams = document.querySelectorAll('pre.mermaid');
if (diagrams.length) {
  for (const pre of diagrams) { const code = pre.querySelector('code'); if (code) pre.textContent = code.textContent; }
  const { default: mermaid } = await import('https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs');
  mermaid.initialize({ startOnLoad: false, theme: matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'default' });
  await mermaid.run({ nodes: diagrams });
}
</script>
`
