// Code generated by litgo from litgo.lit.md; DO NOT EDIT.

package weave

import (
	"strings"
	"testing"

	"github.com/tlehman/litgo/internal/lit"
)

const doc = "<!-- package: main -->\n\n# Title\n\n```mermaid\ngraph LR\n  a --> b\n```\n\n" +
	"```go\nfunc main() {\n\t// <<say \"hi\">>\n}\n```\n\n<!-- chunk: say \"hi\" -->\n```go\nprintln(1)\n```\n\n" +
	"<!-- notangle -->\n```go\n// <<only an illustration>>\n```\n"

func TestWeaveForTypst(t *testing.T) {
	d := lit.Parse("/x/t.lit.md", []byte(doc))
	out := weave(d, typstTarget)
	for _, want := range []string{
		`#lit-chunk("chunk-say-hi", "say \"hi\"", "≡", (("", "the program"), ))`,
		"```diagram\n┌───┐",
		"#lit-literal.update(true)\n```\n```go\n// <<only an illustration>>\n```\n```{=typst}\n#lit-literal.update(false)",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("woven Markdown lacks %q:\n%s", want, out)
		}
	}
	if strings.Contains(out, "# Title") || strings.Contains(out, "```mermaid") {
		t.Errorf("the title and the diagram source should be gone:\n%s", out)
	}
	drew := typstTarget
	drew.figures = map[int]string{4: `<svg id="a"/>`}
	if out := weave(d, drew); !strings.Contains(out, `#lit-figure("<svg id=\"a\"/>")`) || strings.Contains(out, "```diagram") {
		t.Errorf("the drawn diagram should stand in for the block:\n%s", out)
	}
	if Title(d) != "Title" || Summary(d) != "package main · tangles to t.go" {
		t.Errorf("title %q, summary %q", Title(d), Summary(d))
	}
}

func TestWeaveForHTML(t *testing.T) {
	out := Markdown(lit.Parse("/x/t.lit.md", []byte(doc)))
	for _, want := range []string{
		"# Title\n\n<div class=\"lit-meta\">package main · tangles to t.go</div>",
		`<div class="lit-chunk" id="chunk-say-hi"><span class="lit-name">⟨say &#34;hi&#34;⟩ ≡</span> <span class="lit-uses">used in the program</span></div>`,
		"```mermaid",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("woven Markdown lacks %q:\n%s", want, out)
		}
	}
}
